### ISSUE TITLE
Library is old need to update location

### ISSUE THREAD

**Issue by krishbhattacharyya** [rebeccahughes/react-native-device-info#109]
Hi,

I am getting error on timeZone. When I print timezone. It is shown Asia/Calcutta where as it should show Asia/Kolkata.

Can you solve this problem? 

Another question is how can I get the App Name? Is there any option to get this?
![timezone](https://cloud.githubusercontent.com/assets/10433734/19848704/3c52d508-9f75-11e6-9ff8-69f89f61fdf2.png)

**Comment by Naoto-Ida** [comment]
As for the timezone issue, not sure. Are you sure your timezone is correct?
I am in Tokyo but once had my timezone reset to Osaka...

Check my [Gist](https://gist.github.com/Naoto-Ida/e6f89f8c69c38e9962bde573de27be13) for the simplest way. I've used this fool proof one liner in production apps.

**Comment by krishbhattacharyya** [comment]
Hi @Naoto-Ida ,
Yes the problem is exist. Actually kolkata was calcutta once so in the old database it was "Asia/Calcutta", the name has been changed to kolkata. 
And I got the information from android developers they got the timezone "Asia/Kolkata" instead of "Asia/Calcutta". 
So I think it should be updated.

**Comment by machour** [comment]
@krishbhattacharyya I'm not sure I understand your problem.
Is it something similar to #215 where the Timezone don't change after having been initially calculated, or is it Calcutta being reported instead of Kolkata ?

If it's the later, then we have no control over this as we're simply using `java.util.Timezone` in android.

**Comment by machour** [comment]
Closed by mistake 😄

**Comment by machour** [comment]
Closing this stale issue.
