### ISSUE TITLE
Is it possible to get SIM data?

### ISSUE THREAD

**Issue by sigrlami** [rebeccahughes/react-native-device-info#112]
Can we get SIM information like https://github.com/pbakondy/cordova-plugin-sim ?

**Comment by Udbhav12** [comment]
Is there any way to get SIM number using react-native-device-info ?

**Comment by mikehardy** [comment]
The right repo would be https://github.com/ianlin/react-native-carrier-info I think - it operates on SIM information and does not have overlap here
