### ISSUE TITLE
Does not support react-native 0.35

### ISSUE THREAD

**Issue by akbarik** [rebeccahughes/react-native-device-info#114]
I'm trying to install the package into my project which is written on react-native 0.35 using this command:
npm install --save react-native-device-info

This outputs an error:
├── UNMET PEER DEPENDENCY react-native@0.35.0
├── react-native-device-info@0.9.6 
└── UNMET PEER DEPENDENCY whatwg-fetch@^1.0.0

Can you tell which version of react-native-device-info supports react-native 0.35? I've tried to downgrade several versions including 0.9.6 to 0.9.0, had no success.

**Comment by aiossa** [comment]
I use it within react 0.36.0 and it works fine. Try to manually link package like it is described in description, and preliminary install Google repository in SDK manager

**Comment by machour** [comment]
Closing this old stale issue, please re-open if you're still facing a problem!
