### ISSUE TITLE
Will we have a way to tell if the current device is using TV device?

### ISSUE THREAD

**Issue by codetony25** [rebeccahughes/react-native-device-info#116]
Currently I am building a react native application which works for android and iOS mobile, but I am also currently working on TV devices as well such as Amazon FireStick and tvOS. It would be awesome to have this: DeviceInfo.isMobile() and DeviceInfo.isTv() :)

**Comment by mikehardy** [comment]
@machour I believe this is closable, https://github.com/rebeccahughes/react-native-device-info#getDeviceType should return "Tv" if it is a TV
