### ISSUE TITLE
.isTablet() is not a function

### ISSUE THREAD

**Issue by annelorraineuy** [rebeccahughes/react-native-device-info#117]
The method to detect if device type is tablet is missing. This method is available in the docs. (iOS)

**Comment by annelorraineuy** [comment]
I checked the source code on master and the committed files are there. When I ran npm install or yarn add I don't see the isTablet code on my package though. Verified its version 0.9.6.

**Comment by jmfirth** [comment]
Ran across this as well.  Any ETA on publish?

**Comment by GantMan** [comment]
released 0.9.7 🎉

**Comment by ovr** [comment]
@rebeccahughes Issue should be closed ;)
