### ISSUE TITLE
Can't add file in ios (Add the .xcodeproj file)

### ISSUE THREAD

**Issue by Msspl-PrashenjeetRoy** [rebeccahughes/react-native-device-info#119]
I can't add .xcodeproj in this location node_modules/react-native-device-info as mentioned in documentation. 
I have projectname.xcodeproj file but inactive state... can't select why anybody tell me.

**Comment by GantMan** [comment]
did you try `react-native link` instead of the manual steps?

**Comment by Zadvornyi** [comment]
I had the same issues

**Comment by machour** [comment]
Closing this issue as no feedback was provided. @Zadvornyi please open a new issue if you're still facing the same problem.
