### ISSUE TITLE
Use releases

### ISSUE THREAD

**Issue by neiker** [rebeccahughes/react-native-device-info#122]
Now it's really hard to find what changes on each release.

This project don't use [releases](https://github.com/rebeccahughes/react-native-device-info/releases), not even [tags](https://github.com/rebeccahughes/react-native-device-info/tags) :(

**Comment by GantMan** [comment]
agreed.  I'll start to remedy this.   Seems Rebecca used to use a changelog.md file.  But I'll be moving ot releases and tags form here forward.
