### ISSUE TITLE
Android causes errors when app uses Firebase

### ISSUE THREAD

**Issue by StevePotter** [rebeccahughes/react-native-device-info#123]
Our CI build broken after adding this.  Upon further inspection, it's a conflict that stems from instanceId using GCM.  I would suggest removing instanceId entirely, as it will avoid any Google Play dependencies, plus it doesn't work for Firebase anyway.

**Comment by GantMan** [comment]
I'm inclined to make this change... I feel this dependency causes lots of headache.

Go ahead and do a PR to remove it, and I'll discuss with a few people to get this pushed through.

**Comment by StevePotter** [comment]
You got it.  Give me a few days and I'll hit you up with the PR.

**Comment by GantMan** [comment]
@StevePotter - glad you're on it. When it's 100% I'll release version 0.10.0

**Comment by dannycochran** [comment]
@StevePotter did you ever fork or do a PR here?

**Comment by machour** [comment]
Closing this in favor of #187 which contains more comments.
