### ISSUE TITLE
DeviceInfo.getDeviceLocale not working on emulator

### ISSUE THREAD

**Issue by Eldelshell** [rebeccahughes/react-native-device-info#130]
Currently I'm testing DeviceInfo on an Android emulator using API level 24 and I'm always getting "und" as a response.

 Is DeviceInfo capable of working with a virtual device?

Note: I haven't tested it on a real device just yet.

Thanks! Nice library BTW!

**Comment by Eldelshell** [comment]
So, I've tested on a real device and this works just fine.

**Comment by Ehesp** [comment]
@Eldelshell I know this isn't a fix/helpful for this lib, but react-native-i18n gives the locale on emulator if you really need it.

**Comment by Eldelshell** [comment]
Thanks Rebecca, I can live with this without having to add another dep.
