### ISSUE TITLE
Android's deviceLocale returns legacy locales for Indonesian, Hebrew and Yiddish

### ISSUE THREAD

**Issue by dleshem** [rebeccahughes/react-native-device-info#132]
Retrieving the device's locale on Android returns the non-standard ```iw-IL```  locale for Hebrew (Israel), instead of the standard ```he-IL``` locale. Same goes for Indonesian: standard locale is ```id-ID```, this code returns the non-standard ```in-ID```.

iPhone version does not exhibit this behavior.

From Java's [Locale](https://docs.oracle.com/javase/7/docs/api/java/util/Locale.html) documentation-

> Legacy language codes
> 
> Locale's constructor has always converted three language codes to their earlier, obsoleted forms: he maps to iw, yi maps to ji, and id maps to in. This continues to be the case, in order to not break backwards compatibility.

I think the right approach is to explicitly fix these problematic language codes in this library, as in an RN context these legacy locales are not expected (leaky implementation).

**Comment by machour** [comment]
Maybe something to consider for 1.0.0 as it introduces a BC break (#307).
Closing this issue as it will be handled from the 1.0.0 issue.
