### ISSUE TITLE
For React Native 0.40

### ISSUE THREAD

**Issue by Richard-Cao** [rebeccahughes/react-native-device-info#135]
[iOS Breaking Change](https://github.com/facebook/react-native/releases/tag/v0.40.0)

**Comment by Richard-Cao** [comment]
@rebeccahughes

**Comment by GantMan** [comment]
@Richard-Cao - will you be doing an update?

I can assign you :)

**Comment by Richard-Cao** [comment]
I will try next week.

**Comment by geldarhb** [comment]
@Richard-Cao wasn't it implemented already? 
https://github.com/rebeccahughes/react-native-device-info/commit/5834bf6c4c48d26b555cf90abb0a6e5537a54f06

**Comment by Richard-Cao** [comment]
Thanks! I think it should be no problem
