### ISSUE TITLE
undefined is not an object (evaluating 'u.uniqueId')

### ISSUE THREAD

**Issue by xjbw** [rebeccahughes/react-native-device-info#137]
I used this on android system.
It has good performance on debug version.
But when I release my app,  this error occurred in the release version when running DeviceInfo.getUniqueID() 

01-10 11:40:43.714 23837 23872 E ReactNativeJS: undefined is not an object (evaluating 'u.uniqueId')

It's the msg from adb logcat. 
How to solve this issue?

**Comment by xjbw** [comment]
My English is limited, maybe some expressions are impolite......Thanks

**Comment by jinxac** [comment]
Did you run ```link``` command mentioned in the ReadMe? If you havent do that and try recompiling your project. It should work.

**Comment by Doshirak** [comment]
Have the same issue. 
react@15.4.2 and react-native@0.40.0 are installed.

**Comment by Doshirak** [comment]
Reinitialized my project with `react-native init` and copied my code. It helped.

**Comment by kevinhylant** [comment]
I have the same versions of react & react-native installed, ran `react-native link` and am experience the same issue. Will try the manual process.

It's not an option for me to reinitialize my project unfortunately

**Comment by jinxac** [comment]
I dont think reinitializing is required. Try following steps:-

1. link this library as mentioned in docs
2. Clean your xcode project
3. Kill the running process for xcode laucher
4. Compile and run again

it worked for me

**Comment by DavidPeralvo** [comment]
I use react-native 0.42

1º npm install --save react-native-device-info
2º react-native link react-native-device-info
3º Clean xcode project
4º Compile and run

it worked for me . Good luck

**Comment by Symous** [comment]
Just run react-native run-ios again , and it will worked. :)

**Comment by Airomad** [comment]
You have to full recompile your project. Use command in the comment above

**Comment by machour** [comment]
@xjbw is having a problem with Android, not iOS :)

**Comment by machour** [comment]
@xjbw can you still reproduce the problem with 0.14.0 ?

**Comment by machour** [comment]
Closing this stale issue. Please open a new one if you're still facing the problem.

**Comment by riskaverse** [comment]
DeviceInfo is an object which includes "default" object so, in order to access the function getUniqueID() you need to do something like this DeviceInfo.default.getUniqueID()
