### ISSUE TITLE
[Android] Build failed in emulator. Could anyone help me???

### ISSUE THREAD

**Issue by lelup** [rebeccahughes/react-native-device-info#143]
![screen shot 2017-01-19 at 21 34 42](https://cloud.githubusercontent.com/assets/19283388/22112994/7a05c6ec-de97-11e6-8a15-73fbe534fbc8.png)

**Comment by danieljoonlee** [comment]
I'm getting the same problem as well

**Comment by danieljoonlee** [comment]
Found the issue.  Please refer to this link: http://stackoverflow.com/questions/17155475/could-not-find-com-google-android-gmsplay-services3-1-59-3-2-25-4-0-30-4-1-32

If you do not have `Google Repository` or `Google Play Services` it will give you the error above
