### ISSUE TITLE
crash in DeviceUID

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [rebeccahughes/react-native-device-info#148]
`dwarfdump  --arch arm64 C83A0732-54C6-31F5-B1F9-84132CDA33AA.dSYM --lookup 0x00000001000d1690
----------------------------------------------------------------------
 File: C83A0732-54C6-31F5-B1F9-84132CDA33AA.dSYM/Contents/Resources/DWARF/diff (arm64)
----------------------------------------------------------------------
Looking up address: 0x00000001000d1690 in .debug_info... found!

0x00021104: Compile Unit: length = 0x0000013e  version = 0x0002  abbr_offset = 0x00000000  addr_size = 0x08  (next CU at 0x00021246)

0x0002110f: TAG_compile_unit [1] *
             AT_producer( "Apple LLVM version 8.0.0 (clang-800.0.42.1)" )
             AT_language( DW_LANG_ObjC )
             AT_name( "/Users/lin/Project/react-native/diff/node_modules/react-native-device-info/RNDeviceInfo/DeviceUID.m" )
             AT_stmt_list( 0x00036895 )
             AT_comp_dir( "/Users/lin/Project/react-native/diff/node_modules/react-native-device-info" )
             AT_APPLE_optimized( 0x01 )
             AT_APPLE_major_runtime_vers( 0x02 )
             AT_low_pc( 0x00000001000d109c )
             AT_high_pc( 0x00000001000d1a70 )

0x000211b2:     TAG_subprogram [2]
                 AT_low_pc( 0x00000001000d15dc )
                 AT_high_pc( 0x00000001000d174c )
                 AT_name( "+[DeviceUID valueForKeychainKey:service:]" )
Line table file: '/Users/lin/Project/react-native/diff/node_modules/react-native-device-info/RNDeviceInfo/DeviceUID.m' line 94, column 5 with start address 0x00000001000d1690

Looking up address: 0x00000001000d1690 in .debug_frame... not found.`

crash in here

**Comment by Darkhorse-Fraternity** [comment]
CrashReporter Key:   6fdd8f7bf390b9f067682589c17d262578b1350c
Hardware Model:      xxx
Process:             diff [3366]
Path:                /private/var/containers/Bundle/Application/2BBD4C29-0341-460E-AB04-C252E7F55580/diff.app/diff
Identifier:          com.sword.diff
Version:             1 (1.0)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.sword.diff [1999]


Date/Time:           2016-12-21 05:14:33.7150 +0800
Launch Time:         2016-12-21 05:14:32.2411 +0800
OS Version:          iPhone OS 10.1.1 (14B100)
Report Version:      104

**Comment by cbartondock** [comment]
Any word on this? If I try to add this module my Android app builds but crashes instantly without an error message. React Native 0.42.3

**Comment by machour** [comment]
Closing this as no feedback was provided.
