### ISSUE TITLE
TypeError: Cannot read property 'bundleId' of undefined when running Jest tests

### ISSUE THREAD

**Issue by arunshan** [rebeccahughes/react-native-device-info#159]
Geetting the following error when running jest tests:

Error:
```
TypeError: Cannot read property 'bundleId' of undefined
```

Code:
```
import DeviceInfo from 'react-native-device-info'
const bundleId = DeviceInfo.getBundleId()
```

package.json:

```
"react": "~15.4.1",
"react-native": "^0.38.1"
```

**Comment by zhen639** [comment]
Similar issue.
Mine is: 
```
 TypeError: Cannot read property 'uniqueId' of undefined

      at Object.getUniqueID (node_modules/react-native-device-info/deviceinfo.js:9:20)
      at Object.Utils.getDeviceToken (js/utils.js:229:40)
      at Object.<anonymous> (js/services/request.js:104:470)
      at Object.<anonymous> (js/containers/AssetDetail/actions.js:170:277)
```
How to solve this? 
mock it?

**Comment by carloscuesta** [comment]
Just mock the method you're using @zhen639 @arunshan 

```
jest.mock('react-native-device-info', () => {
  return {
    getUniqueID: jest.fn()
  }
})
```

**Comment by dan-me** [comment]
terminate the packager by exiting the terminal window

then

manually start with:

```
$ react-native start
```
I hope this helps somehow!

**Comment by vspedr** [comment]
If someone else runs into this error, try creating a folder named `__mocks__` in the same folder 
 as `node_modules` then add a file named `react-native-device-info.js` in the folder you just created, with contents:

```
module.exports = {
  getBundleId: jest.genMockFunction(),
  // add more methods as needed
};
```

**Comment by fpena** [comment]
I tried creating the `__mocks__` folder with the `react-native-device-info` file in it. It seems it's not detecting this file. How can I make sure it's being read?

**Comment by vspedr** [comment]
I guess you should also call `jest.mock('react-native-device-info');` in your test file and jest will know where to look for the mock files.

**Comment by fpena** [comment]
I have this inside my `describe` function.

```
beforeEach(() => {
        jest.mock('react-native-device-info');
});
```

Still complains because it's `undefined`.

**Comment by machour** [comment]
The solution provided by @carloscuesta worked for me.

package.json:
```
  "jest": {
    "setupFiles": [
      "./testenv.js"
    ],
    // ...
```

testenv.js:
```
jest.mock('react-native-device-info', () => {
  return {
    getModel: jest.fn(),
  };
});
```

**Comment by Damoness** [comment]
> jest.mock('react-native-device-info', () => { return { getUniqueID: jest.fn() } })

thanks

**Comment by Kushal-DesaiMobiquity** [comment]
**Who invented test cases?**
I tried mocking 'react-native-device-info' by adding that .js file.
Error: react-native-image-picker is null.
I tried mocking 'react-native-image-picker'.
Error: in some other library.
**WHO INVENTED TEST CASES???**
