### ISSUE TITLE
Consider removing peerDependencies?

### ISSUE THREAD

**Issue by hswolff** [rebeccahughes/react-native-device-info#16]
I just upgraded my project to use the latest rc version of react-native and when I went to `npm install` I got thrown an error by npm2. I found this [GitHub issue](https://github.com/npm/npm/issues/8854) which discusses how npm2 ignores rc versions when trying to reconcile peerDependencies. I was curious if you'd be open to removing the peerDependencies requirement of this project to avoid this error?

**Comment by hswolff** [comment]
Fixed via https://github.com/rebeccahughes/react-native-device-info/commit/bea9cae1a718e8d886bddb7c3f4d49aaab372fa5 ! Woohoo!

**Comment by rebeccahughes** [comment]
It should be on npm now :)
