### ISSUE TITLE
I want to get device imei

### ISSUE THREAD

**Issue by jijunpeng** [rebeccahughes/react-native-device-info#160]
I didn't found it in current version.
this is the demo code
```
public static String getDeviceIMEI(Context context) {
        TelephonyManager tm = (TelephonyManager) context.getSystemService(Context.TELEPHONY_SERVICE);
        String myIMEI = tm.getDeviceId();
        if (myIMEI == null || "".equals(myIMEI)) {
            myIMEI = "999999999";
        }
        return myIMEI;
    }
```

**Comment by gabsima** [comment]
See pull request #250

**Comment by koswarabilly** [comment]
use [react-native-imei](https://github.com/SimenCodes/react-native-imei) instead it works anyway but you might have to edit a line of the code inside node-module, when you first compile if you encounter error, dont panic , see the error and remember which line, delete the line that cause you error and it is done

**Comment by machour** [comment]
Duplicate of #127
