### ISSUE TITLE
[Android] missing dependency google play-services-gcm after react-native-link

### ISSUE THREAD

**Issue by chung-nguyen** [rebeccahughes/react-native-device-info#162]
After installing react-native-device-info, and followed the step-by-step instructions, I could not use react-native-device-info to get the device unique id due to the undefined error of its native module.

The reason was that Android's react-native-device-info depends on 'com.google.android.gms:play-services-gcm:9.4.0', so I added this line in build.gradle and the issue was gone:
compile 'com.google.android.gms:play-services-gcm:9.4.0'

Please consider rework on react native linking to add above line.

This seems related to this issue: https://github.com/rebeccahughes/react-native-device-info/issues/52

**Comment by carloscuesta** [comment]
I'm having the same problem when building  from gradlew

**Comment by deepaksisodiya** [comment]
@chung-nguyen 
Thanks

**Comment by chung-nguyen** [comment]
@carloscuesta : Sorry to reply very lately now, but I think installing android "google play services" library will fix your issue. The installation can be done using "Android Sdk Manager".
![image](https://cloud.githubusercontent.com/assets/14791553/25066955/fb55fc3e-225e-11e7-8a24-734efbb9d0f1.png)

**Comment by machour** [comment]
Is this still happening with the last release?
