### ISSUE TITLE
Getting error in npm test

### ISSUE THREAD

**Issue by krishbhattacharyya** [rebeccahughes/react-native-device-info#163]
Hi,

I am getting error in npm test ( jest test ). Is there any solution? Also this is creating problem in mobile center when running unit test.

![testresult copy](https://cloud.githubusercontent.com/assets/10433734/24145555/a67d1df2-0e57-11e7-8aee-ce1513982f34.png)

**Comment by machour** [comment]
Duplicate of #159 (you need to mock this lib)
