### ISSUE TITLE
android buildToolsVersion "25.0.2" is too high for us

### ISSUE THREAD

**Issue by BBBOND** [rebeccahughes/react-native-device-info#166]
Can you reduce it's version to 23.0.1 ?
Thanks!

**Comment by mikedevel** [comment]
hi...me need 23.0.1 too... thanx

**Comment by johncblandii** [comment]
Please don't. Just fork the lib and drop it to your needs.

**Comment by RobertSheaO** [comment]
BTW, you can put this into your `build.gradle`, NOT the one inside the `android/app` directory

```
ext {
    compileSdkVersion = 25
    buildToolsVersion = "25.0.1"
}
subprojects { subproject ->
    afterEvaluate{
        if((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
            }
        }
    }
}
```

Inside your `android/app/build.gradle` file, change `compileSdkVersion` and `buildToolsVersion` to the following

```
compileSdkVersion rootProject.ext.compileSdkVersion
buildToolsVersion rootProject.ext.buildToolsVersion
```

This will force subprojects to compile with the build tools that you use.

**Comment by machour** [comment]
Closing this as we won't downgrade and a proper solution was provided.
