### ISSUE TITLE
Warning: License for package Android SDK Build-Tools 25.0.2 not accepted.

### ISSUE THREAD

**Issue by flyjennyetn** [rebeccahughes/react-native-device-info#167]
useNewCruncher has been deprecated. It will be removed in a future version of th
e gradle plugin. New cruncher is now always enabled.
Checking the license for package Android SDK Build-Tools 25.0.2 in D:\android\sd
k\licenses
Warning: License for package Android SDK Build-Tools 25.0.2 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-device-info'.
      > You have not accepted the license agreements of the following SDK compon
ents:
[Android SDK Build-Tools 25.0.2].
Before building your project, you need to accept the license agreements and comp
lete the installation of the missing components using the Android Studio SDK Man
ager.
Alternatively, to learn how to transfer the license agreements from one workstat
ion to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 8.81 secs

**Comment by edmofro** [comment]
Same here - no issues using 0.9.9

**Comment by GeoffreyPlitt** [comment]
+1

**Comment by zachrnolan** [comment]
+1

**Comment by eenchev** [comment]
+1

**Comment by GeoffreyPlitt** [comment]
For anyone else having this problem, what finally solved it for me (using a CI tool that runs Ubuntu):

brew install Caskroom/cask/android-sdk
export ANDROID_HOME='/usr/local/share/android-sdk' (or whatever the correct path is)
Always use $ANDROID_HOME/tools/bin/sdkmanager for sdkmanager commands. There are other paths with "sdkmanager" somehow, which will not work.

**Comment by eenchev** [comment]
Thanks. Had my $PATH variable messed up, too.

**Comment by yuyongmao** [comment]
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-device-info'.
      > Could not resolve all dependencies for configuration ':react-native-device-info:_debugPublishCopy'.
         > Could not find any matches for com.google.android.gms:play-services-gcm:+ as no versions of com.google.android.gms:play-services-gcm are available.
           Required by:
               ALCS:react-native-device-info:unspecified


how to fix it?thanks!

**Comment by eenchev** [comment]
@yuyongmao Your error has nothing to do with the current topic(package licences not accepted). Try installing Google Repo in the Android SDK.

**Comment by joshjo** [comment]
Update the lib sdk tools to the latest version works for me.

**Comment by dan-me** [comment]
我遇到的问题 :
```
Warning: License for package Android SDK Build-Tools 25.0.2 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-device-info'.
      > You have not accepted the license agreements of the following SDK compon
ents:
[Android SDK Build-Tools 25.0.2].
Before building your project, you need to accept the license agreements and comp
lete the installation of the missing components using the Android Studio SDK Man
ager.
Alternatively, to learn how to transfer the license agreements from one workstat
ion to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED
```
下载android studio  配置的sdk目录（如 :F:\android-sdk-windows，我的android sdk 是通过Android SDK Manager下载的）， 用android studio打开项目目录下的android 文件，android studio会下载依赖文件，下载完成后运行    ``` react - native run - android```.

或者用android studio 新建项目，看能否运行起来，缺少那些依赖文件。

**Comment by flyher** [comment]
@GeoffreyPlitt 
Thank you ,you saved my day!

**Comment by GantMan** [comment]
Perhaps a PR to the readme to help others?

**Comment by labidiaymen** [comment]
Installing   Android SDK Build-tools from the command line works for me

/android-sdk-linux/tools/android list sdk --all
  ....
  10- Android SDK Build-tools, revision 25.0.3
  11- Android SDK Build-tools, revision 25.0.2
  12- Android SDK Build-tools, revision 25.0.1
  ...
/android-sdk-linux/tools/android update sdk -u -a -t 11
