### ISSUE TITLE
Is there a way to identify a unique Android device?

### ISSUE THREAD

**Issue by pearlismylove** [rebeccahughes/react-native-device-info#173]
First of all, Thanks for the great library. We use it for our commercial project and it's really helpful.

We are doing a referral program (or MGM) now where users can invite their friends and get benefits after their friends joined in our app. (Like what Uber & Dropbox did)

And one of our policies is that one device can use the referral only once in a life time and we identify the device by checking the combination of unique ID + Manufacturer + Device Model + non rooted device using this library.

but there are a lot of abusers who keep changing the unique ID and keep getting the benefits.

I don't know exactly how they change the unique ID without rooting the device but I read some articles about how to change the unique ID of the device without rooting.

We also verify their email address and phone number by asking them to input the verification code but they are creating tons of disposable email addresses (even the domains are gmail.com, yahoo.com and outlook.com) and they can buy active simcards in a very cheap price here in Indonesia. So it's not difficult for them to verify both the email address and the phone number .

So my question is...is there's a way / method to identify if it's really unique device or not? some kind of unique and immutable value?

**Comment by jason2li** [comment]
Did you ever figure this out?  We're looking for the same thing.
