### ISSUE TITLE
'React/RCTDefines.h' file not found

### ISSUE THREAD

**Issue by SanlinBlackball** [rebeccahughes/react-native-device-info#175]
when i run bulid in ios ,it can not work and show the error that 'React/RCTDefines.h' file not found, what should i do?

**Comment by AlexDM0** [comment]
Repeat react-native upgrade fixed it for me

**Comment by SanlinBlackball** [comment]
do  you mean that i should upgrade react-native to fix it?  but my  react-native is the last version  。and the error will appear when i upgrade react-native

**Comment by AlexDM0** [comment]
No, I mean if you run the command react-native upgrade it will replace all your Xcode files with the default ones for that version. After that run react-native link and restore any manual imports. I only had to replace the xcodeproj and schemes.

**Comment by rexfng** [comment]
It fixed it for me. I had react-native 0.46 before. So I changed the react-native version inside package.json and did nothing. Then decided to use react-native upgrade to 0.47. Then things worked out. This is so weird. My error was missing the Define file as well. If anyone needs help please leave a comment. It's been quite frustrating especially with deadlines coming up.

**Comment by camnicklaus** [comment]
I'm having this issue as well.
I ran the upgrade command and the link command. I've removed node_modules and reinstalled. anything else to try?

**Comment by yuanwy** [comment]
I'm having this issue as well.
but update npm doesn't work.
what should I do?

**Comment by machour** [comment]
@yuanwy @camnicklaus did you get this sorted using AlexDM0 comment?

**Comment by machour** [comment]
Closing this as no feedback was provided.

**Comment by vysotsky** [comment]
I'm also having this issue. 
I used @AlexDM0 solution but this didn't help. 
RN v0.54.2

**Comment by Kikketer** [comment]
There are a few bugs reported on this.  I'm getting it with a fresh react-native@0.59.8.
1. react-native init someproject && cd someproject
2. yarn add react-native-device-info
3. react-native init
4. Open xcode and attempt to run

**Comment by mikehardy** [comment]
please open a fresh issue
but also react-native link, not init for step 3
and are you using pods or not? which thing did you open xcode if pods (project or workspace)?
In other words, all the details, specific steps...
