### ISSUE TITLE
DeviceInfo native module is not installed correctly after updating to RN0.44.0

### ISSUE THREAD

**Issue by georgest** [rebeccahughes/react-native-device-info#176]
After updating React Native to 0.44.0 I get the error that DeviceInfo module is not installed correctly:

![screen shot 2017-05-10 at 12 48 11 pm](https://cloud.githubusercontent.com/assets/3203859/25893120/46cb34a8-357f-11e7-87cf-17e0ded3e7a6.png)

"react": "^16.0.0-alpha.6",
"react-native": "^0.44.0",

**Comment by georgest** [comment]
rm -rf node_modules && npm install is fixing the issue.

**Comment by moorthysubu** [comment]
rm -rf node_modules && npm doesn't seems works :(

**Comment by chrisbolin** [comment]
@moorthysubu I had to stop my iOS simulator as well as reinstall. then running `react-native run-ios` recompiled my project for the new version of RN

**Comment by chuckern** [comment]
I have the same issue.
And I run project at Xcode while have jsbundle in my project.
When I click Button and load the bundle that the simulator show this error.
I run rm -rf node_modules && npm install at rn root but does not work.
Please anyone can solve this problem help me.

**Comment by lucibit** [comment]
After doing all of the above and not working, I also uninstalled the app in my emulator (android uninstall by dragging it away) and recompiled (react-native run-ios) and it worked!

**Comment by hujiaweibujidao** [comment]
I have the same issue for both platforms, and the reason is that the version of RN libraries (integrates them into an old project) is not the same with the RN version used to build the bundle file. Check the versions if you have the same problem. :-)

**Comment by martsie** [comment]
I had this issue because I had another react-native project open with its packager still running. Close that packager and rebuild the current project and all working again,

**Comment by gustavjf** [comment]
Thanks @martsie, that was it for me.
