### ISSUE TITLE
Could not find com.atlassian.mobile.video:okhttp-ws-compat:3.7.0-atlassian1.

### ISSUE THREAD

**Issue by bristoljon** [rebeccahughes/react-native-device-info#180]
Building our project has suddenly begun failing with below error:

`Could not find com.atlassian.mobile.video:okhttp-ws-compat:3.7.0-atlassian1.
           Required by:
               Novo:react-native-device-info:unspecified > com.facebook.react:react-native:0.42.3-atlassian-1
`

Any idea how to resolve this? Thanks

**Comment by Almouro** [comment]
Hit the same bug and used https://github.com/facebook/react-native/issues/14223#issuecomment-304509104 :) it worked for me!

**Comment by GantMan** [comment]
feel free to add this to the readme

**Comment by peterchibunna** [comment]
I had the same issue. It's something I added inside` build.gradle`

**Comment by bristoljon** [comment]
cool, thanks for the quick response guys. looks like upgrading RN will resolve the issue. Currently on `0.41.0` but as the error message seems to state `0.42.3` is required

**Comment by shrutic** [comment]
I am using a custom fork of 0.43.3 react-native and the fix suggested by @Almouro doesnt work and fails with the error "Error:Failed to resolve: com.facebook.react:react-native:0.43.3". Is there a way we can resolve this for react-native compiled from source

**Comment by aouaki** [comment]
Fix given by @janaka120 in the same issue in react-native-fetch-blob :

Add this code to your build.gradle (not the one in `android/`, not in `android/app/`) :
```
allprojects {
     configurations.all {
        resolutionStrategy {
            eachDependency { DependencyResolveDetails details ->
                if (details.requested.group == 'com.facebook.react' && details.requested.name == 'react-native') {
                    def file = new File("$rootDir/../node_modules/react-native/package.json")
                    def version = new groovy.json.JsonSlurper().parseText(file.text).version
                    details.useVersion version
                }
            }
        }
    }  
}
```

**Comment by machour** [comment]
Closing this as it was a react-native issue.
