### ISSUE TITLE
React native link does not working

### ISSUE THREAD

**Issue by gayancharith** [rebeccahughes/react-native-device-info#181]
when using this command 'react-native link react-native-device-info'. It gives the following error.
Something went wrong while linking. Error: Expected "/* Begin ", "/* End ", "\"", or [A-Za-z0-9_.] but "<" found. 
Please file an issue here

**Comment by joshyg** [comment]
I am seeing the same thing

**Comment by lukevenediger** [comment]
Me too - this is what I get:

```
$ react-native link react-native-device-info
Scanning 969 folders for symlinks in /Users/lukevenediger/ucam-src/ucam-client/node_modules (6ms)
$
```

**Comment by mehdijjz** [comment]
I have the same problem

**Comment by davidgruebl** [comment]
got the same output as @lukevenediger but not only for this plugin but basically any plugin I'm trying to link
```
$ react-native -v
react-native-cli: 2.0.1
react-native: 0.46.0
```

seems like an issue of the react-native cli
manually linking works just fine

**Comment by 3210jr** [comment]
Does this have a solution?

**Comment by grovertb** [comment]
+1

**Comment by budiga** [comment]
+1!
$ react-native -v
react-native-cli: 2.0.1
react-native: 0.46.0

**Comment by rclaes1995** [comment]
+1

**Comment by GantMan** [comment]
Can someone with the problem find a fix?  I'll write the code, but I'm not sure what the issue is.

**Comment by rclaes1995** [comment]
It's a problem with the linking with iOS. If you manually link iOS and then run `react-native link` it works. @GantMan

**Comment by Azmeer-crescent** [comment]
After I install CLI it worked for me:
`npm install -g react-native-cli`

**Comment by machour** [comment]
Is this still happening with the last version?

**Comment by percivalruiz-bibo** [comment]
Have you tried doing `react-native upgrade` before `react-native link`? That worked for me.
