### ISSUE TITLE
Add support for 10.5" ipad Pro

### ISSUE THREAD

**Issue by clozr** [rebeccahughes/react-native-device-info#183]
Please add support detecting 10.5" ipad pro.

**Comment by clozr** [comment]
@"iPad7,1"   :@"iPad Pro 12.9-inch",// iPad Pro 12.5-inch - Wifi
                              @"iPad7,2"   :@"iPad Pro 12.9-inch",// iPad Pro 12.5-inch - Cellular
                              @"iPad7,3"   :@"iPad Pro 10.5-inch",// iPad Pro 12.5-inch - Wifi
                              @"iPad7,4"   :@"iPad Pro 10.5-inch",// iPad Pro 12.5-inch - Cellular

**Comment by nolan-m** [comment]
https://github.com/rebeccahughes/react-native-device-info/issues/183

Here you go

**Comment by machour** [comment]
Added in #230

**Comment by seraj-ahmad** [comment]
iPad8,1 : iPad Pro 3rd Gen (11 inch, WiFi)
iPad8,2 : iPad Pro 3rd Gen (11 inch, 1TB, WiFi)
iPad8,3 : iPad Pro 3rd Gen (11 inch, WiFi+Cellular)
iPad8,4 : iPad Pro 3rd Gen (11 inch, 1TB, WiFi+Cellular)
iPad8,5 : iPad Pro 3rd Gen (12.9 inch, WiFi)
iPad8,6 : iPad Pro 3rd Gen (12.9 inch, 1TB, WiFi)
iPad8,7 : iPad Pro 3rd Gen (12.9 inch, WiFi+Cellular)
iPad8,8 : iPad Pro 3rd Gen (12.9 inch, 1TB, WiFi+Cellular)

Add support for these now

**Comment by machour** [comment]
Open a PR for these now if you want that.

Don't comment on closed issues. 

Use at least a hello, please or thank you when addressing people. People are not walls.
