### ISSUE TITLE
cannot build for iOS 8 device?

### ISSUE THREAD

**Issue by jihopark** [rebeccahughes/react-native-device-info#19]
The iOS Deployment Target on RNDeviceInfo.xcodeproj has been set to iOS 9.0, so I couldn't build it since my app targets 8.0. So I had to change it to 8.0 on the library project file. I tested it on the 8.1 device on the simulator and had no problems. 

I am wondering if there is a potential problem lowering this?

**Comment by jaggs6** [comment]
+1

**Comment by jaggs6** [comment]
+1 @rebeccahughes

**Comment by rebeccahughes** [comment]
This is fixed and is on npm now

**Comment by nicholasc** [comment]
I would like to re-open this. I installed 0.16.0 a minute ago and the xcodeproj is still targeting  iOS 9.0.
I am willing to submit a PR for this if approved by maintainers.

**Comment by machour** [comment]
Will happily approve a PR for this, provided in doesn't brake anything compatibility wise :)

**Comment by machour** [comment]
This was fixed in 0.17.2, thank you again @nicholasc !
