### ISSUE TITLE
[Move to React Native Community] Is this package maintained?

### ISSUE THREAD

**Issue by D1no** [rebeccahughes/react-native-device-info#190]
If not, what are alternatives.

Edit:
https://github.com/react-native-community

**Comment by GantMan** [comment]
Kinda... I can tell you this.  @rebeccahughes doesn't have time to maintain it.

I try to help with merging PRs and checking them to make sure nothing came in to break it, but I don't actively work on it.   I would suggest if someone needs this for their product, we should move it to https://github.com/react-native-community and have everyone pitch in!

**Comment by D1no** [comment]
That sounds like s pretty good idea 👍

**Comment by brennanerbz** [comment]
Does anyone have this package working on RN 0.45 or above?

**Comment by GantMan** [comment]
yes, it's working in 0.45 I believe with our conference app

https://github.com/infinitered/ChainReactApp

**Comment by rebeccahughes** [comment]
If someone wants to maintain it then let me know and I can make you a contributor.

**Comment by GantMan** [comment]
@rebeccahughes - I think we should move this repo to the react-community (https://github.com/react-community)

From there I can handle adding permissions to everyone who wants to help.  I think this will stop people from pinging you.  Let me know if this sounds good.

**Comment by rebeccahughes** [comment]
If you open an issue and assign it to me I am happy to add/remove permissions for people as and when :)

**Comment by machour** [comment]
Closing this as the move is not going to happen. 
I'm currently trying to clean the issues pipes and will do my best to help maintaining this package!
