### ISSUE TITLE
Is IDFV collection is permitted by Apple?

### ISSUE THREAD

**Issue by Symous** [rebeccahughes/react-native-device-info#193]
Hi,awesome lib!

Just want to confirm that if we use getUniqueID to get IDFV on iOS, is that permitted by Apple and whether  it will be rejected by AppStore? Thanks a lot. : )

**Comment by egold** [comment]
IDFV is totally fine. It stands for "Identifier for Vendor" -- it's unique to only apps you own. For instance, if you owned two apps with the bundle IDs of:

```
com.symous.myApp1
com.symous.myApp2
```

they would both have access to the same IDFV. But my app

```
com.egold.myApp
```

would have a different value for IDFV.

You're probably thinking of IDFA, the advertiser one that was created to replace using UDID, but has been abused from time to time (in Apple's eyes). IDFA has legitimate uses, but also illegitimate uses.

More info on IDFV: https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor

**Comment by Symous** [comment]
thank u my friend. :)

**Comment by koswarabilly** [comment]
@egold so can i use it do identify if certain task was done in the same device?

**Comment by dule-vikki** [comment]
@egold 
How about if them same bundleId but Apple TeamId is difference?
