### ISSUE TITLE
Serious BUG of this lib !!!

### ISSUE THREAD

**Issue by Symous** [rebeccahughes/react-native-device-info#194]
when we run
```
 npm install --save react-native-device-info
```

to install this lib , it will remove some lib in node_modules folder directly, 
```js
//after install
react-native-device-info@0.10.2
removed 4 packages and updated 316 packages in 110.567s
```
as a result , the app will not start.

for me it delete 4 lib of my app:
1. fb-watchman
2. jest-docblock 
3. big-integer
4. (haven't found)

Please why this happened ?

**Comment by amorenew** [comment]
you got voted down because of bug title

**Comment by Symous** [comment]
I have found out that it might be a result of my node version is not working well with my npm version...
 :(
