### ISSUE TITLE
Cannot find module 'NativeModules' when using mocha to test the module

### ISSUE THREAD

**Issue by IbraheemAlSaady** [rebeccahughes/react-native-device-info#195]
I'm trying to test a module which I'm using **react-native-device-info**, but when I run my tests, it throws 
```
Cannot find module 'NativeModules'
```
Anyone knows what's wrong?

**Comment by wz366** [comment]
Workaround: https://github.com/wz366/react-native-device-info

**Comment by machour** [comment]
You need to mock this library (check #159 for a jest example)
