### ISSUE TITLE
RN47.0 has removed `createJSModules` method 

### ISSUE THREAD

**Issue by lslvxy** [rebeccahughes/react-native-device-info#197]
RN47.0 change log [`https://github.com/facebook/react-native/releases/tag/v0.47.0`](https://github.com/facebook/react-native/releases/tag/v0.47.0)

**Comment by deathemperor** [comment]
+1. It was this commit https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8

**Comment by patw0929** [comment]
+1

Please bump new version for use the newest commit.

**Comment by deathemperor** [comment]
I just checked, it's merge here https://github.com/rebeccahughes/react-native-device-info/pull/191

**Comment by GantMan** [comment]
0.11.0 is out folks!

**Comment by AlanFoster** [comment]
Successfully rebuilt a production app using the 0.11 release :+1:
