### ISSUE TITLE
DeviceInfo.isTablet returning wrong value 

### ISSUE THREAD

**Issue by victorileaf** [rebeccahughes/react-native-device-info#198]
DeviceInfo.isTablet is true for both Nexus 7, Nexus 4 and Nexus 5.
check using Emulator.

**Comment by samueljseay** [comment]
If you look at the implementation of `isTablet` it is just checking screen sizes. There isn't afaik a truly reliable way to determine whether the device is a tablet or phone (at least for Android I don't know of one, therefore its not gonna be cross platform).

**Comment by machour** [comment]
The problem is that there is not real way in Android to tell if we're on a Tablet, and detection have become harder & harder with new phones having extra high definitions..

Anyone have an idea on how to address this? 🤔

**Comment by samueljseay** [comment]
This looks promising: https://stackoverflow.com/a/24701063/472987

**Comment by machour** [comment]
Doesn't seem really reliable either, according to the comments right below :/

**Comment by mikpalm** [comment]
Just tried to alter this and so far it looks good. But needs alot more testing and I bet its not reliable. This is what Im doing right now.
RNDeviceModule.java
`private Boolean isTablet() {
    //int layout = getReactApplicationContext().getResources().getConfiguration().screenLayout & Configuration.SCREENLAYOUT_SIZE_MASK;
    //layout = (Configuration.SCREENLAYOUT_SIZE_LARGE || layout == Configuration.SCREENLAYOUT_SIZE_XLARGE);
    boolean layout = (getReactApplicationContext().getResources().getConfiguration().screenLayout & Configuration.SCREENLAYOUT_SIZE_MASK) >= Configuration.SCREENLAYOUT_SIZE_LARGE;
    if (layout) {
      DisplayMetrics metrics = new DisplayMetrics();
      getCurrentActivity().getWindowManager().getDefaultDisplay().getMetrics(metrics);

      if (metrics.densityDpi == DisplayMetrics.DENSITY_DEFAULT
              || metrics.densityDpi == DisplayMetrics.DENSITY_HIGH
              || metrics.densityDpi == DisplayMetrics.DENSITY_MEDIUM
              || metrics.densityDpi == DisplayMetrics.DENSITY_TV
              || metrics.densityDpi == DisplayMetrics.DENSITY_XHIGH) {
        return true;
      } else {
        return false;
      }
    }
    return false;
  }`

**Comment by machour** [comment]
@mikpalm could you open a PR for this so we can work/adjust the code there? Thank you mate!

**Comment by mikpalm** [comment]
Done.

**Comment by machour** [comment]
Thank you! PR #313 was opened to deal with this.

**Comment by machour** [comment]
The PR was merged in 0.17.2, thank you again @mikpalm  & @Ingibjorg  !
