### ISSUE TITLE
Add support for Device ID in iOS

### ISSUE THREAD

**Issue by chris-erickson** [rebeccahughes/react-native-device-info#2]
Nice library.  Does a bunch of things I could make use of, except the device ID (ie. iPhone2,1).  I was thinking of just doing a PR for it myself if it's not something already in the works.  I imagine doing it something [like this](http://stackoverflow.com/a/20062141) - with only the raw ID, or human friendly name - either works ok for me.  What do you think @rebeccahughes?

**Comment by rebeccahughes** [comment]
Sounds good... add whatever you need :)

**Comment by adbl** [comment]
+1

**Comment by rebeccahughes** [comment]
This is in 0.5.0 which should now be on npm. I tweaked it so on iOS you get the proper human friendly model name e.g. "iPhone 6" and then you can get the raw device ID (e.g. iPhone7,2) by calling `getDeviceId` if you need it.

**Comment by chris-erickson** [comment]
Awesome!!
