### ISSUE TITLE
Device Unique ID will change after reinstall on IOS

### ISSUE THREAD

**Issue by narychen** [rebeccahughes/react-native-device-info#20]
It's the same on android. But not on ios.

**Comment by LeBlaaanc** [comment]
This module uses IDFV (Identifier for Vendor) which will change if you no longer have an app installed from the same vendor on a user's device. @rebeccahughes do we think we should rename this function to `getIdentifierForVendor()` or even just document it?

**Comment by rebeccahughes** [comment]
Thanks @LeBlaaanc :)

**Comment by narychen** [comment]
just document it a bit will be ok.

**Comment by hpelitebook745G2** [comment]
@narychen in current API list, what did you use to get ID for iOS?
