### ISSUE TITLE
[Warning?] Are readme instructions somehow harmfull?

### ISSUE THREAD

**Issue by Mazuh** [rebeccahughes/react-native-device-info#201]
I executed:

```sh
npm install --save react-native-device-info
```
It made my whole repository environment stop working. I had to execute ```npm install``` again, and here's the output:

> added 794 packages, removed 2 packages and updated 33 packages in 63.55s

I'm yet adapting myself to react-native and even npm itself. But it seems to me that readme instructions made me downgrade my modules and even removed hundreds of stuff from here!

So if I'm mistaken or did something wrong, please tell me -- it is my best interest to understand more about it. Otherwise, isn't better to put a warning there or something? Maybe tell people to run ```npm install``` right after this installation step? Idk.

**Comment by ODelibalta** [comment]
I had the same issue. Removed node_modules and re-ran npm install. 

Now I have the another problem after running the link command.

**Comment by nolan-m** [comment]
I've used this before (0.10.2) and did not have any problems getting it running.  I'm about to use it again on another project.  I can report back if I run into any problems installing.

**Comment by machour** [comment]
@Mazuh this is a weird issue .. are you still able to reproduce it? @ODelibalta ?

**Comment by Mazuh** [comment]
It had been a long time since I already did a rollback on it, and I'm not planning to use it again.

Let's wait for @ODelibalta or @nolan-m's feedbacks.

**Comment by nolan-m** [comment]
Sorry, I never replied.  I didn't have any problems using this either time.

**Comment by machour** [comment]
Closing this as it seems ok now.
