### ISSUE TITLE
Is there a working example? 

### ISSUE THREAD

**Issue by ODelibalta** [rebeccahughes/react-native-device-info#202]
I was extremely excited about this lib but everything broke beginning from the install command. 
After I fixed the install, link command broke everything. 

I would love to see a working example of this library anywhere. 

Any of you have a repo of a working example? or . Is there an alternative? Thank you!

My setup

```
"dependencies": {
    "axios": "^0.16.2",
    "lodash": "^4.17.4",
    "native-base": "^2.3.0",
    "react": "16.0.0-alpha.12",
    "react-native": "0.46.4",
    "react-native-navigation": "^1.1.143",
    "react-native-vector-icons": "^4.2.0",
    "react-redux": "^5.0.5",
    "redux": "^3.7.2",
    "redux-persist": "^4.8.2",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "2.1.0",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.12"
  },
```

**Comment by betoharres** [comment]
I also could not got this working, I literally created a new app with ``react-native init`` command and installed this lib and linked in this fresh new app and I get this error message to all methods:
```
undefined is not an object (evaluating 'RNDeviceInfo.uniqueId')
```

**Comment by machour** [comment]
Check https://github.com/machour/react-native-device-info-test for a working example
