### ISSUE TITLE
How can I find out Ipad on using DeviceInfo

### ISSUE THREAD

**Issue by lavarajallu** [rebeccahughes/react-native-device-info#204]
if I want tab in android to findout like Deviceinfo.isTablet(){
}
similarly how Can we find out IPAD

**Comment by nolan-m** [comment]
`DeviceInfo.getDeviceId().indexOf('iPad') > -1`

**Comment by machour** [comment]
DeviceInfo.isTablet() was added in 0.97
Please reopen an issue if you still got problems (check #198 first)
