### ISSUE TITLE
getUniqueID() problem.

### ISSUE THREAD

**Issue by sandropoluan** [rebeccahughes/react-native-device-info#205]
Documentation say that getUniqueID() will return value with format like this 'FCDBD8EF-62FC-4ECB-B2F5-92C9E79AC7F9' but I got this '665deb085e1c03fe' instead. Is that normal?

Platform Android
React-native 0.44
react-native-device-info 0.11.0

**Comment by Shubham-Sinha** [comment]
Hey did you find a solution to this one.

**Comment by sandropoluan** [comment]
Not yet.

**Comment by jjdp** [comment]
that's normal https://stackoverflow.com/questions/2785485/is-there-a-unique-android-device-id

**Comment by Norfeldt** [comment]
close #205

**Comment by machour** [comment]
Fixed while reformatting the documentation:
  https://github.com/rebeccahughes/react-native-device-info/blob/master/README.md#getuniqueid
