### ISSUE TITLE
[ANDROID] Error after upgrading react native to v0.47

### ISSUE THREAD

**Issue by pgonzalez-santiago** [rebeccahughes/react-native-device-info#206]
Hi guys, I am getting this error trying to run my APP in android.

`.../node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceInfo.java
Error:(26, 3) error: method does not override or implement a method from a supertype`

I am using:
 
"react-native": "0.47.1",
"react-native-device-info": "^0.10.2"

Also, I had this error with other packages but I solved it by upgrading them to the latest versions.

Any ideas?

Thank you.

**Comment by Vycen** [comment]
Hello there,

This error comes from the 0.47 version of React-Native, where the `createJSModule()` method has been deprecated (see [https://github.com/facebook/react-native/releases/tag/v0.47.0](url)). 

The react-native-device-info hasn't been updated yet, so meanwhile you can just safely remove the method from your RNDeviceInfo.js file in the node_module.

Hope it helps !

**Comment by felipemartim** [comment]
Actually it was fixed on v0.11.0.

**Comment by sibelius** [comment]
fixed on latest version
