### ISSUE TITLE
How to get the IMEI?

### ISSUE THREAD

**Issue by LzxHahaha** [rebeccahughes/react-native-device-info#21]

**Comment by L3V147H4N** [comment]
why was this closed without an anwser?

**Comment by LzxHahaha** [comment]
@L3V147H4N Because I found iOS 7+ refuse to let devlopor get the IMEI

**Comment by L3V147H4N** [comment]
Ok! Thx for replying.

**Comment by sam9010** [comment]
plz help me
how to get imei?

**Comment by mikehardy** [comment]
@sam9010 
- do not post on old issues
- please query stackoverflow: https://stackoverflow.com/questions/55173823/i-am-getting-imei-null-in-android-q

It is not possible
