### ISSUE TITLE
CHANGELOG outdated

### ISSUE THREAD

**Issue by dantman** [rebeccahughes/react-native-device-info#216]
The CHANGELOG.md has not been updated with information for `0.9.8`, `0.10.0`, `0.9.9`, `0.10.1`, `0.10.2`, and `0.11.0`.

**Comment by GantMan** [comment]
correct.  It's mostly been "keep parity with React Native" updates.

If you'd like to write up changes retroactively, that would be awesome as a PR

**Comment by antoinerousseau** [comment]
the changelog should be updated by the person releasing tags to npm... (and I advise to add corresponding git tags, and ideally github releases)

**Comment by jkimbo** [comment]
This can be closed now since https://github.com/rebeccahughes/react-native-device-info/pull/237 was merged
