### ISSUE TITLE
is this project still alive???

### ISSUE THREAD

**Issue by thg303** [rebeccahughes/react-native-device-info#219]
too many PR and issues without answer. is this project alive?

**Comment by GantMan** [comment]
Somewhat.  I'm trying to help keep the project going with existing features... not so sure it should take on all these new features.  And I don't have time to test them all.

@rebeccahughes is pretty busy and can't maintain the project.

Ideally, we'd have a good way to test the features and make sure they aren't just bloat, but that's not something easy to determine.
