### ISSUE TITLE
Can't use this component on Android

### ISSUE THREAD

**Issue by DeforeChen** [rebeccahughes/react-native-device-info#220]
My RN version is 0.47.1 and I do the steps as the tutorials, which works in my iOS but fails in Android.

The following sentence can't be recognized by AS
`compile "com.facebook.react:react-native:0.20+" //compile ‘com.facebook.react:react-native:0.20.+’
compile project(':react-native-device-info')`

The AS always shows
```
Gradle sync failed: Could not find method compile() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
				Consult IDE log for more details (Help | Show Log)
```

I have tried many ways to solve it and I'm an iOS developer indeed.

**Comment by GantMan** [comment]
what version of the component do you have?  Latest?

**Comment by machour** [comment]
Closing this as no feedback was provided.
