### ISSUE TITLE
Get current iPhone total storage?

### ISSUE THREAD

**Issue by betoharres** [rebeccahughes/react-native-device-info#227]
Hello, I've noticed it's missing the phone total storage, or free space/used space.
Doing a quick research I've crossed with this question on SO:
https://stackoverflow.com/questions/5310445/check-enough-space-on-iphone-device-before-downloading-files

what do you guys think? I know nothing about obj-c so I'm just making a suggestion :D 
Would be hard to do it?

**Comment by nolan-m** [comment]
Check out https://github.com/itinance/react-native-fs#getfsinfo-promisefsinforesult

You would have to add another library, but this does what you are looking for.

**Comment by betoharres** [comment]
Thanks @nolan-m ! I'm going to check out, great tip! =]
