### ISSUE TITLE
Unable to install current version

### ISSUE THREAD

**Issue by artkulakow** [rebeccahughes/react-native-device-info#229]
I have upgraded to the latest version of react native and xcode and am unable to update to the latest version

[npm-debug.log](https://github.com/rebeccahughes/react-native-device-info/files/1330225/npm-debug.log)

**Comment by nolan-m** [comment]
Try `0.11.0`?  Looks like you are installing `0.9.9` from what I can tell in the logs.

Also looks like you have a peerDependency error.

`125 verbose stack Error: The package react@16.0.0-alpha.12 does not satisfy its siblings' peerDependencies requirements!`

I'm running `0.11.0` with RN `0.47.1` and Xcode 9 just fine.

**Comment by machour** [comment]
Please try with the latest version and open a new issue if this is still happening
