### ISSUE TITLE
undefined is not an object (evaluating 'RNDeviceInfo.systemManufacturer' in IOS

### ISSUE THREAD

**Issue by ShaileshPrajapati-BTC** [rebeccahughes/react-native-device-info#234]
```
"react": "^16.0.0-alpha.12",
"react-native": "0.48.0",
"react-native-device-info": "^0.11.0"
```

**Comment by viethaca** [comment]
Open your project in Xcode, 
select RNDeviceInfo.xcodeproj then build
open Link Binary With Libraries  Link Binary With Libraries, add libRNDeviceInfo.a
remove libRNDeviceInfo-tvOS.a

**Comment by machour** [comment]
@ShaileshPrajapati-BTC can you test with 0.14.0?

**Comment by machour** [comment]
Confirmed, it still happens.
This is in fact #258 when the app is already running in the Simulator (started before adding this package to your app).
Marking this as a duplicate

**Comment by garrettboatman** [comment]
Had is issue. `react-native link` didn't work.

Fixed it by dragging `RNDeviceInfo.xcodeproj` into my Xcode Libraries, went to `[My Target] > Build Phases > Link Binary with Libraries` and added `libRNDeviceInfo.a`

**Comment by mlaco** [comment]
@garrettboatman sorry if I should know this, but where can I obtain `libRNDeviceInfo.a`?

**Comment by garrettboatman** [comment]
@mlaco it should be added to Xcode automatically when you drag in `RNDeviceInfo.xcodeproj` from `node_modules`.
