### ISSUE TITLE
Cannot read property 'appVersion' of undefined

### ISSUE THREAD

**Issue by longpq18** [rebeccahughes/react-native-device-info#236]
[Android]
My react-native:
react-native-cli: 2.0.1
react-native: 0.45.1

**Comment by athomaj** [comment]
Happened to me on simulator(iphone7, ios11). works well on physical device.

**Comment by athomaj** [comment]
Happened to me on simulator, I just had to restart it.

**Comment by baijunjie** [comment]
Same question at 0.49.3

**Comment by calcazar** [comment]
Seeing this on react-native: 0.49.5

```deviceInfo.getVersion();```

**Comment by MrToph** [comment]
Same issue RN `0.46.3`

**Comment by ap-simplesystems** [comment]
Same issue React Native 0.44.2

**Comment by jaschaio** [comment]
Same issue. Actually no method works as `deviceInfo` itself is undefined. Using React Native 0.50.1

**Comment by rajeshpanwar007** [comment]
+1

**Comment by donnes** [comment]
+1

**Comment by mikefrancis** [comment]
Same problem for me, in the meantime I am just using the following:

```javascript
import { version } from '../../package.json';
```

**Comment by GantMan** [comment]
Can someone verify that master now works for them?  Fixing the issue above?

**Comment by vysotsky** [comment]
@GantMan the latest commit from master still doesn't work

**Comment by rajeshpanwar007** [comment]
Hi All,


I created the project using expo and then detached the project.
In my case my expo module was using 9.8.0 version of play-services-gcm but react-native-device-info was using latest version of play-services-gcm. 

**Solution :** 

1. Option
I forked the react-native-device-info and set the 9.8.0 version of play-services-gcm and it worked for me and directly installed the module from github.

For reference, my forked github repo: 
https://github.com/rajeshpanwar007/react-native-device-info

2. Option
If you are not able to fork, set version and installed directly,
a). Just simple add below line in under dependencies in package.json 
`"react-native-device-info": "git+https://git@github.com/rajeshpanwar007/react-native-device-info.git",`
b). Run `npm install react-native-device-info`

**Comment by sfratini** [comment]
Can we re open this issue? I am having the exact same problem. All the modules are undefined and I have no idea why. I have tried many things, including manual link and forcing GCM version.

**Comment by machour** [comment]
Reopened, please share more details about what you've tried

**Comment by sfratini** [comment]
@machour This was my bad actually. I tried Android Studio and it worked and I could not understand why RN assembleDebug was not. I forgot that I fixed another issue by changing the build directory and I had an automatic script installing the APK and it was using the old directory, so I was reinstalling the old APK without the library. 

Everything working right now by installing the correct APK. You can go ahead and close this one, sorry. Leaving the explanation in case this happens to someone else.

**Comment by machour** [comment]
No worries mate, glad you find out the problem

**Comment by afilp** [comment]
I have the same problem in Android, none of the methods work. It says `Cannot read property "bundleId` of undefined` and I have linked properly.

**Comment by machour** [comment]
@afilp could you open a new issue describing what you did?
From what I can see, linking have failed.

**Comment by afilp** [comment]
@machour I have re-linked manually and it works. I am on Windows and the `compile` code is not inserted automatically, not sure why.

**Comment by Tom29** [comment]
after relinking and still doesn't work.

**Comment by hpmax00** [comment]
same problem with 0.55.4

**Comment by hpmax00** [comment]
It is ok, after rnpm link

**Comment by roysG** [comment]
Same problem

**Comment by machour** [comment]
Please don't comment on closed issues. Open a new one a follow the template to give us all details.
