### ISSUE TITLE
Removing the bluetooth permission

### ISSUE THREAD

**Issue by cosmith** [rebeccahughes/react-native-device-info#24]
Hi,

Thanks for the module.
Would you consider removing the `<uses-permission android:name="android.permission.BLUETOOTH"/>` from `Manifest.xml` since it is optional?

Every time I do a release of my app I realize when I upload to Google Play that a permission has been added because it comes back when I run `npm install`... So I have to manually edit the manifest and recompile the whole thing.

It's a minor nuisance but it's really easy to prevent.

We could add a descriptive error message when the permission is not granted for newcomers to be warned about this.

Thanks!

**Comment by rebeccahughes** [comment]
All fixed :)

**Comment by cosmith** [comment]
Thanks!
