### ISSUE TITLE
TypeError: undefined is not a function (evaluating 'DeviceInfo.getAPILevel()')

### ISSUE THREAD

**Issue by prashant-agarwala** [rebeccahughes/react-native-device-info#240]
Android version 7.1.1
"react": "16.0.0-alpha.12",
"react-native": "0.48.3",
"react-native-device-info": "^0.11.0",

**Comment by jkimbo** [comment]
@prashant-agarwala `getAPILevel` hasn't been released yet (see [CHANGELOG](https://github.com/rebeccahughes/react-native-device-info/blob/master/CHANGELOG.md#upcoming))

**Comment by machour** [comment]
This should be supported in last releases
