### ISSUE TITLE
Failed resolution of: Lcom/google/android/gms/iid/InstanceID

### ISSUE THREAD

**Issue by connercms** [rebeccahughes/react-native-device-info#245]
Build is failing with this library. Error is thrown in RNDeviceModule.java on line 12 at
`import com.google.android.gms.iid.InstanceID;`

If I remove this line and line 112 
    `constants.put("instanceId", InstanceID.getInstance(this.reactContext).getId());`, my app builds successfully. Anybody have a permanent or better fix?

**Comment by redbluenat** [comment]
it helps me 
```
  compile ("com.google.android.gms:play-services-gcm:10.0.1") {
        force = true;
    }
```


my gardle file:
```
  compile(project(':react-native-device-info')) {
        exclude group: 'com.google.android.gms'
    }
    compile(project(':react-native-maps')) {
        exclude group: 'com.google.android.gms'
    }
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:26.0.0"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile("com.google.android.gms:play-services-base:10.2.4") {
        force = true
    }
    compile("com.google.android.gms:play-services-maps:10.2.4") {
        force = true;
    }
    compile ("com.google.android.gms:play-services-gcm:10.2.4") {
        force = true;
    }
```

**Comment by peteroid** [comment]
To give more information why @redbluenat 's fix works, this lib actually requires the `com.google.android.gms:play-services-gcm` (https://github.com/rebeccahughes/react-native-device-info/blob/master/android/build.gradle#L23). So I guess you did exclude the whole group of `com.google.android.gms` and this causes the crash of the app.

Therefore the fix is simply to add the excluded lib back to your project. Thanks @redbluenat !

**Comment by Rewieer** [comment]
Your solution works for me, thanks you :)

**Comment by redbluenat** [comment]
I am glad that it works for you guys :)

**Comment by Rewieer** [comment]
For people coming next, actually [this link](https://medium.com/@suchydan/how-to-solve-google-play-services-version-collision-in-gradle-dependencies-ef086ae5c75f) explains all of this very well.

**Comment by machour** [comment]
Documented how to disable com.google.android.gms in the [troubleshooting]( https://github.com/rebeccahughes/react-native-device-info#troubleshooting) section.
Will probably be dropped with next BC breaking release.
