### ISSUE TITLE
TypeError: Cannot read property 'timezone' of undefined

### ISSUE THREAD

**Issue by baldurpan** [rebeccahughes/react-native-device-info#248]
Getting this error when calling getTimezone() in iOS.
Works fine in Android.

Using RN version 0.49.3

**Comment by melanconz** [comment]
[https://github.com/rebeccahughes/react-native-device-info/issues/251](url)  The solution to this issue has fixed this issue for me. I think the TVos link is causing issues.

**Comment by machour** [comment]
@baldurpan please try the solution suggested in #258, I think that @melanconz is right

**Comment by machour** [comment]
Closing as no feedback was provided.
