### ISSUE TITLE
Cannot read property 'isTablet' of undefined

### ISSUE THREAD

**Issue by andreystarkov** [rebeccahughes/react-native-device-info#253]
Cant run on Android. Everything's linked. Any suggestions?

RN 0.46.3, 26 SDK

**Comment by ManUtd27** [comment]
I'm having the same issues on iOS. 
Unable to run any of the functions 


e.g.
import DeviceInfo from 'react-native-device-info';

DeviceInfo.getSystemName()

**Comment by andreystarkov** [comment]
Checked again about how its linked.
Seems like "react-native link react-native-device-info" does't work for android.

Linked manually and its fine!

**Comment by ntomallen** [comment]
Same issue for my iOS.. was putting stuff in #262 . Someone said it didn't work on emulators, but it doesn't work for emulators or physical devices for me.

**Comment by ntomallen** [comment]
I resolved this by navigating to the ios directory of the project and running `pod install`. I guess that doesn't get run in the linking stage for iOS? I also had to fix a couple of gradle things, but all of those functions work properly now on iOS and Android - both real and emulated devices for each system.

**Comment by machour** [comment]
Closing this issue as the original problem was solved
