### ISSUE TITLE
Can't read property 'deviceId' of undefined 

### ISSUE THREAD

**Issue by tkc** [rebeccahughes/react-native-device-info#262]
After installing and linking react-native-device-info .
I get the following error on iso simulator.

```
Can't read property 'deviceId' of undefined 
```

packege.json
```
"dependencies": {
		"react": "16.0.0",
		"react-native": "0.50.3",
		"react-native-device-info": "^0.12.1",
		"react-native-fcm": "^10.0.3",
		"react-native-router-flux": "^4.0.0-beta.23",
	},
```

<img width="393" alt="screen shot 2017-11-11 at 13 59 40" src="https://user-images.githubusercontent.com/181991/32686472-b642fdde-c6e8-11e7-8547-40ee3b2e2ad8.png">

**Comment by rajeshpanwar007** [comment]
Getting same error .... Any solution ?

**Comment by gusbueno** [comment]
+1

**Comment by melanconz** [comment]
[https://github.com/rebeccahughes/react-native-device-info/issues/251](url)  The solution to this issue has fixed this issue for me.

**Comment by Naoto-Ida** [comment]
Have you logged `DeviceInfo`?
This usually happens when the linking failed somewhere.

**Comment by luco** [comment]
=1

**Comment by barbaragomes** [comment]
That happens only in the simulator.

**Comment by ntomallen** [comment]
@barbaragomes Does it not work in the simulator?

**Comment by barbaragomes** [comment]
@ntomallen at least not for me.

What I did was add a check, before trying to retrieve any information, in order to verify if the code was running in the simulator:

`const model = DeviceInfo.isEmulator() ? "Simulator" :  DeviceInfo.getModel()`

**Comment by ntomallen** [comment]
Interesting. Yeah I was trying to get the following on an iPhone X emulator:
```
let deviceInfo = {
      model: DeviceInfo.getModel(),
      name: DeviceInfo.getDeviceName(),
      sysName: DeviceInfo.getSystemName(),
      sysVersion: DeviceInfo.getSystemVersion()
}
```
and I tried commenting out the various lines, but they all failed. I verified that the DeviceInfo object is initialized properly with a `console.log` as well. I'm using `import * as DeviceInfo from 'react-native-device-info'` to import the functions.

So I tried your solution (which would be pretty handy), but I'm now getting `cannot read property 'isEmulator' of undefined` for that function too! I'm going to try importing the functions directly now...

**Comment by ntomallen** [comment]
Still getting the same error from: `import {getModel, getSystemName, getSystemVersion, getDeviceName, isEmulator} from 'react-native-device-info'`. I also tried the typical `import DeviceInfo from 'react-native-device-info` but that didn't work either. I verified that it did link via `react-native link`...

**Comment by ntomallen** [comment]
@melanconz I tried that solution but the library had already been removed, I guess. I'm going to try nuking the node_modules folder and rebuilding the app now.

**Comment by ntomallen** [comment]
It didn't work. I also tried logging `isEmulator` and it is being correctly imported as far as I can tell. Both iOS and Android show up as having already been linked when running `react-native link react-native-device-info`

**Comment by ntomallen** [comment]
It doesn't work on my iPhone 7 either.

**Comment by ntomallen** [comment]
I resolved this by navigating to the ios directory of the project and running `pod install`. I guess that doesn't get run in the linking stage for iOS? I also had to fix a couple of gradle things, but all of those functions work properly now on iOS and Android - both real and emulated devices for each system.

**Comment by gusbueno** [comment]
remove libRNDeviceinfo-tvOS.a it works for me ;)

**Comment by machour** [comment]
@tkc did you ever get this to work?

**Comment by jblancoh** [comment]
you link manual the library in Xcode, it worked for me

**Comment by machour** [comment]
Closing this as no feedback was provided.

**Comment by saaksshi** [comment]
same error.

TypeError: Cannot read property 'isEmulator' of undefined

This error is located at:
    in Dashboard (at SceneView.js:9)
    in SceneView (at ResourceSavingSceneView.js:55)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in ResourceSavingSceneView (at TabView.js:35)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in AnimatedComponent (at TabViewPagerPan.js:249)
    in TabViewPagerPan (at TabView.js:125)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in TabViewAnimated (at TabView.js:187)
    in TabView (at createNavigator.js:59)
    in Navigator (at createNavigationContainer.js:376)
    in NavigationContainer (at Dashboard.js:10)
    in Dashboard (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:574)
    in RCTView (at View.js:43)
    in AnimatedComponent (at StackViewCard.js:12)
    in Card (at createPointerEventsContainer.js:28)
    in Container (at StackViewLayout.js:612)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:63)
    in RCTView (at View.js:43)
    in Transitioner (at StackView.js:21)
    in StackView (at createNavigator.js:59)
    in Navigator (at createKeyboardAwareNavigator.js:11)
    in KeyboardAwareNavigator (at createNavigationContainer.js:376)
    in NavigationContainer (at App.js:10)
    in App (at renderApplication.js:32)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in AppContainer (at renderApplication.js:31)

Checked manual and automatic linking as well didn't work.,

![simulator screen shot - iphone 6 - 2018-08-03 at 10 33 48](https://user-images.githubusercontent.com/9267263/43625132-e545292c-9708-11e8-83ea-59e41e4d2bca.png)

**Comment by machour** [comment]
Please open a new issue, comments on closed issues are not taken care of.
