### ISSUE TITLE
DeviceInfo.getPhoneNumber() return null

### ISSUE THREAD

**Issue by ewall-cauc** [rebeccahughes/react-native-device-info#267]
HI, I am a newbier to andorid developer and react-native-device-info.
when i use react-native-device-info function DeviceInfo.getPhoneNumber() for getphonenumber,but it return nothing, when i goto the deviceinfo.d.ts find getPhoneNumber() undefined, my react-native-device-info is "version": "0.12.1"
![2017-11-21 11-09-09](https://user-images.githubusercontent.com/10722143/33053081-c53bca20-ceac-11e7-9fae-8cc45ce8ab65.png)

**Comment by tehong** [comment]
DeviceInfo.getPhoneNumber() returned "undefined" for me as well on RN Android. MY device-info version 0.13.0.

**Comment by machour** [comment]
Unfortunately this information is [not always available](https://developer.android.com/reference/android/telephony/TelephonyManager.html#getLine1Number()) in Android. It should return `null` in that case. 

If you're getting undefined, you probably didn't set one of READ_PHONE_STATE, READ_SMS or READ_PHONE_NUMBERS permissions.

**Comment by machour** [comment]
This is now documented in [getPhoneNumber()](https://github.com/rebeccahughes/react-native-device-info#getphonenumber).
