### ISSUE TITLE
App gets stuck on getBrand() and getModel() methods on iOS (not tested on Android)

### ISSUE THREAD

**Issue by pramjeet** [rebeccahughes/react-native-device-info#279]
On running any `DeviceInfo.getBrand()` or `DeviceInfo.getModel()`, app gets stuck and I have to reload it.

- Library version = 0.13.0
- RN version = 0.50.4

Edit: I tried with version 0.12.1, but the problem is still there.
My iOS version is 11.1.2

**Comment by machour** [comment]
@pramjeet are you getting any output in the logs tab when the problem occurs?
