### ISSUE TITLE
Will getTimezone() always work?

### ISSUE THREAD

**Issue by nekapoor** [rebeccahughes/react-native-device-info#281]
Are there instances in which getting the timezone from a device won't work? Or is this information always available for a given device? 

Thanks!

**Comment by machour** [comment]
Hi @nekapoor! Generally the best way to find out is to check what is called under the hood:

**iOS:** https://github.com/rebeccahughes/react-native-device-info/blob/master/RNDeviceInfo/RNDeviceInfo.m#L186 (localTimeZone is documented here: https://developer.apple.com/documentation/foundation/nstimezone/1387209-localtimezone)

**Android:** https://github.com/rebeccahughes/react-native-device-info/blob/master/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L186 (Timezone.getDefault() is documented here: https://developer.android.com/reference/java/util/TimeZone.html#getDefault())

Looks to me that the information will only be available.
