### ISSUE TITLE
is possible add a number of memory devices?

### ISSUE THREAD

**Issue by mounlion** [rebeccahughes/react-native-device-info#285]
is possible add a number of memory devices?

**Comment by IjzerenHein** [comment]
What do you mean by "memory devices" ?

**Comment by mounlion** [comment]
device capacity

**Comment by IjzerenHein** [comment]
You mean the total amount of memory on the device, or max available to the react-native process?

**Comment by mounlion** [comment]
total amount of memory on the device

**Comment by IjzerenHein** [comment]
Okay. I've been working to add some memory functions to get the total & available mem for the process. Will let you know when that's done.

**Comment by IjzerenHein** [comment]
Added in PR #289

**Comment by mounlion** [comment]
Thanks you very math!
