### ISSUE TITLE
No Compile on iOS `ld: library not found for -lRNDeviceInfo-tvOS`

### ISSUE THREAD

**Issue by ercpereda** [rebeccahughes/react-native-device-info#286]

**Comment by pqminh** [comment]
me too

**Comment by bjacog** [comment]
Same issue here, can work around this by running 0.12.1.

**Comment by TrustTheBoy** [comment]
me too

**Comment by TheLittleBlack** [comment]
楼上6666

**Comment by machour** [comment]
Is this still happening on 0.14.0? We did ship some additional tvOS fixes

**Comment by machour** [comment]
Yes it is. Closing this issue as it's a duplicate of #258
