### ISSUE TITLE
How to get Devicetoken for IOS devices

### ISSUE THREAD

**Issue by HAPENLY** [rebeccahughes/react-native-device-info#288]
How to get Devicetoken for IOS devices

**Comment by enoch232** [comment]
If this is for mobile notifications, you need to use libraries like react-native-push-notification, react-native-fcm, not this one.

**Comment by julietm1797** [comment]
wtf is this as i dont use this site as it hacked from Africa hacking my damn device as these are linked to my gmail wtf

**Comment by GantMan** [comment]
@julietm1797 eloquently put.

**Comment by AustinPaquette** [comment]
@julietm1797 Well then... welcome to Github!

**Comment by machour** [comment]
As mentioned by @enoch232, you need a push library as the devicetoken is push specific
