### ISSUE TITLE
24hr time or 12hr time

### ISSUE THREAD

**Issue by Noitidart** [rebeccahughes/react-native-device-info#290]
Is it possible to get support for if 24hr time or 12hr time?

**Comment by GantMan** [comment]
I'm not sure I understand this question.

**Comment by Noitidart** [comment]
Hi @GantMan I was thinking of alt to https://github.com/brentvatne/react-native-device-clock-format - something that tells us what clock format is in use, military time or 12 hour time.

**Comment by GantMan** [comment]
Ah, I see.

**Comment by machour** [comment]
@Noitidart There seems to be an undocumented  `is24Hour()` function since 0.12.1

**Comment by Noitidart** [comment]
Oh whoa cool thanks @machour !
