### ISSUE TITLE
Duplicated uuid on 2 Android app use react-native-device-info

### ISSUE THREAD

**Issue by pptoan23** [rebeccahughes/react-native-device-info#296]
I am developing 2 different apps use react-native-device-info package. At now, I installed 2 apps on an Android device and 2 apps have the same uuid. What's the problem with me?

React Native version: 0.46.4
react-native-device-info: 0.11.0
Device info: Nexus 5 with Android 6.0.1

**Comment by machour** [comment]
On Android, the UUID is read from Secure.ANDROID_ID. Prior to Oreo, it will always be the same once you set up your phone :
   https://developer.android.com/reference/android/provider/Settings.Secure.html#ANDROID_ID

**Comment by machour** [comment]
Documented in README.md
