### ISSUE TITLE
ATTN: Rebecca Hughes 

### ISSUE THREAD

**Issue by GantMan** [rebeccahughes/react-native-device-info#300]
@rebeccahughes - I've bee a maintainer of this repo for over a year now and would love to bring in smart and helpful people like @machour

Please give me admin access to this repo so I can better manage it.  It would be ideal if we could make it part of the community.  Which is really is.

You have my twitter, and I have sent you a DM, but I know you're a busy person so I'm messaging you in many different ways :D 

Cheers, and I hope to get access soon!  
-Gant

**Comment by machour** [comment]
Thank you both!
