### ISSUE TITLE
Command failed: /usr/bin/git clone -q git://github.com/athombv/react-native-device-info.git /Users/iryna/.npm/_cacache/tmp/git-clone-bb918ce6 370 error /Users/user/.npm/_cacache/tmp/git-clone-bb918ce6/.git: Permission denied

### ISSUE THREAD

**Issue by Luckygirlllll** [rebeccahughes/react-native-device-info#304]
I'm getting such error while running npm install. How to fix it?

**Comment by machour** [comment]
Users/user/.npm/_cacache/tmp/git-clone-bb918ce6/.git: **Permission denied**

Fix your permissions on that path

**Comment by zidzid1234** [comment]
Use Yarn!!!
sudo yarn add packageName --dev/-D
If Yarn gives you error like: Missing list of packages to add to your project
YOU NEED TO PUT PACKAGE NAMES IN FRONT OF THE --dev/-D !!!
