### ISSUE TITLE
Method throws error

### ISSUE THREAD

**Issue by Tennesseesunshine** [rebeccahughes/react-native-device-info#317]
Version ======> 0.14 
Affected OS=======>ios
OS Version =======> 10.3.3

When I connect ipad test, the introduction of documents in the console print log can see a lot of ways, but calling one will throw an error. For example, I call 'DeviceInfo.getBrand ()' method, the program will throw the error 'Can not read property' brand 'of undefined'. I do not know what is the reason, please trouble you help me solve the problem.

**Comment by Lawris** [comment]
Hello, how did you solve your problem please ?

**Comment by Tennesseesunshine** [comment]
I am so sorry, I did not reply to your message because of the celebration of the Spring Festival. This problem has not been solved, I need to test again after work.When Match 1.

**Comment by Tennesseesunshine** [comment]
I am so sorry, I did not reply to your message because of the celebration of the Spring Festival. That problem is because the operation lost one step.Thanks.
