### ISSUE TITLE
Does not work on android API 17 ?

### ISSUE THREAD

**Issue by Stettinum** [rebeccahughes/react-native-device-info#318]
Java exception in 'NativeModules'

java.lang.NoSuchMethodError: 
android.os.StatFs.getBlockCountLong

**Comment by machour** [comment]
Oopsy, it appears that the disk size related methods introduced in 0.15.0 use getBlockCountLong() which is only available in API 18+.

A quickfix for you would be to use version 0.14.0 if you don't need the new methods. Or to modify the relevant [piece of code](https://github.com/rebeccahughes/react-native-device-info/blob/master/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L130-L138) to support prior versions and open a PR for this bug fix.

**Comment by Stettinum** [comment]
@machour thank you ;)

**Comment by machour** [comment]
Fixed in 0.15.1, would you mind testing it and report back? Thank you 🙏

**Comment by Stettinum** [comment]
@machour  with pleasure. Thank you for great library !

**Comment by machour** [comment]
I tested this on a API 16 emulator, seems to be working fine.
Don't hesitate to reopen if you find out otherwise!
