### ISSUE TITLE
Getting undefined is not an object: reactNativeDeviceInfo.DeviceInfo.getAPILevel is

### ISSUE THREAD

**Issue by sahil290791** [rebeccahughes/react-native-device-info#321]
## Summary
I have recently upgraded to RN: 0.45.1, react-native-device-info: 0.15.1, and whenever I try to query for api level the app crashes with an error.

| | |
| ----------- | --- |
| Version     | 0.15.1   |
| Affected OS | Android   |
| OS Version  | 8.0.0   |

## Current behavior
Getting this error in sentry:
```
undefined is not an object (evaluating 'reactNativeDeviceInfo.DeviceInfo.getAPILevel')
```

This was working in previous version of RN 44.0 and react-native-device-info: 0.13.0

## Expected behavior
**getAPILevel** should give the api level

**Comment by sahil290791** [comment]
I have linked the library and checked the manual steps also.

**Comment by machour** [comment]
This is obviously a linking problem as `reactNativeDeviceInfo.DeviceInfo` seems to be undefined.

**Comment by sahil290791** [comment]
Thanks @machour , sorry I noticed that as it was working in other components of my app, in one particular component i was importing it in a incorrect way: 
```
// incorrect way
import { DeviceInfo } from 'react-native-device-info'`;

// correct way
import DeviceInfo from 'react-native-device-info';
```

**Comment by machour** [comment]
No problems, thank you for reporting back!
