### ISSUE TITLE
Add support for web

### ISSUE THREAD

**Issue by peacechen** [rebeccahughes/react-native-device-info#323]
## Description

I'm using [react-native-web](https://github.com/necolas/react-native-web) to build a RN project for the browser.  React-native-device-info tries to call native methods which of course don't exist in the browser. 

## Use Case

I've started creating a `web` folder that simply returns an object with the data/methods that react-native-device-info supports.  Most of it is empty since the browser doesn't have much of the information (the few exceptions include userAgent).  `deviceinfo.js` checks whether the Platform.OS is web and conditionally requires the web module or the native module.

Would a PR be accepted?

**Comment by machour** [comment]
Hey @peacechen, I heard of react-native-web, and I'm really curious about seeing a real-life example where it's used. Is your project available for iOS, Android AND web? (if it's a public project, I'd love to check it out).

This being said, go ahead and open the PR, even if it's still a work in progress. We'll figuring things out from there.

**Comment by peacechen** [comment]
We have an iOS app live:
https://itunes.apple.com/us/app/onceconnect/id1308143592?ls=1&mt=8

Android will be released eventually.  Current priority is a web release.  This is a full production app with lots of pieces.  Getting it all sorted out is a bit daunting.  react-native-device-info is one of a number dependencies that I'll need to sort out.

**Comment by peacechen** [comment]
Created PR #324 .  Let me know if you need any more information.

**Comment by machour** [comment]
After reviewing the PR, I must say I'm really doubtful about merging this PR ..

Wouldn't it be possible to find a solution within your app codebase instead?
  Check this article part: https://medium.com/@mitchoneill/react-native-for-web-16c5c96f7165#994a

**Comment by peacechen** [comment]
It may be necessary to split the app up into native and non-native pieces.  Bundling the RN JS for web is problematic imports (and CJS require) are done statically.  Even though the RNDeviceInfo implementation is require'd conditionally, the bundler grabs both which then pukes on the native references.

It would be ideal if RNDeviceInfo could handle this internally, but I don't have a solution for that.

**Comment by machour** [comment]
What are the errors being thrown? 🤔 

If anything we could check if `Platform.OS === "web"` and bail out in `deviceinfo.js` as a courtesy, but adding an almost empty & inaccurate implementation definitely sounds like a big no-no. 
(especially since it would add ~25% of red crosses in a matrix we'd like to keep as green as possible 😄 )

**Comment by peacechen** [comment]
The bundler (webpack in this case) is unable to resolve the native code.  `react-native-web` uses a babel plugin to transpile `react-native` imports to `react-native-web` which has web equivalent implementations for RN components.  Of course none of the native pieces including `NativeModules` is implemented which throws an exception.

Referencing NativeModules anywhere causes this problem, even if conditionally require'd.  Additionally, the babel plugin only looks at `import` not `require`.  The plugin could possibly be enhanced, but that may not help the NativeModules reference.

**Comment by machour** [comment]
Would it be possible for you to create a minimalistic repository with react-native & react-native-web showing this issue? 🙏
That would make it easier for me to poke around and find a good compromise.

**Comment by peacechen** [comment]
Sure, I'll post a repo to repro this.  However I believe that we'll need some help from react-native-web to get this working.
https://github.com/necolas/react-native-web/issues/818

**Comment by peacechen** [comment]
Here's a minimal repo that you can test with:
https://github.com/peacechen/rn-device-info-web

Building will generate a slew of transpilation errors.  This is because the babel plugin doesn't support require chaining.  The fix is to replace this line in `react-native-device-info/deviceinfo.js`:
```
var RNDeviceInfo = require('react-native').NativeModules.RNDeviceInfo;
```

with:
```
import {NativeModules} from 'react-native';

var RNDeviceInfo = NativeModules.RNDeviceInfo;

if (!RNDeviceInfo && Platform.OS === 'web') {
  // conditional path for web...
  RNDeviceInfo = {
    // polyfill...
  };
}
```

While the Readme may not look pretty for the Web column, I feel it's important for the documentation to reflect what is and isn't supported for web.

**Comment by machour** [comment]
`0.17.0` should be out in a few minutes shipping this new feature, enjoy!

**Comment by machour** [comment]
0.17.1* 😅

**Comment by endel** [comment]
I'm having this error when using `react-native-web`:

```
export 'default' (imported as 'DeviceInfo') was not found in 'react-native-device-info'
```

Is it just me? 😅

**Comment by machour** [comment]
Hi @endel, could you please open a new issue with this problem? It's really hard to keep track of comments on closed issues. 🙏

**Comment by peacechen** [comment]
@endel  How are you importing `react-native-device-info` ?  This library doesn't export `default`.

**Comment by machour** [comment]
@peacechen could you possibly have a look at #403?
