### ISSUE TITLE
getPhoneNumber returns undefined on an Android device running Android 7.

### ISSUE THREAD

**Issue by varungupta85** [rebeccahughes/react-native-device-info#327]
## Summary
I am trying to use the `getPhoneNumber` to get user's phone number on Android. I have added the required `<uses-permission android:name="android.permission.READ_PHONE_STATE" />` to the AndroidManifest.xml file. I am running it on an actual device running Android 7. The phone number is returned as `undefined` using the API. I am running the app via Android Studio on the device. Surprisingly, when I run the same code on an emulator, it returns back some number. I am not sure if I am missing something in the code or the API may return `undefined` in some cases. I am using below line of code to print the number

    console.tron.log('Phone number is ' + DeviceInfo.getPhoneNumber())

I don't see any errors or exceptions in the logcat. It appears that people are able to use the API successfully. I would like some guidance on how to get it to work in case there are any gotchas.

|             |     |
| ----------- | --- |
| Version     | 0.14.0   |
| Affected OS | Android  |
| OS Version  | 7 |

## Current behavior
Phone number returned as `undefined`.

## Expected behavior
Actual phone number is printed.

**Comment by machour** [comment]
Hi @varungupta85, unfortunately getting the phone number from an Android is not an exact science :/
Check this answer: https://stackoverflow.com/questions/35167273/how-to-get-phone-number-of-the-device-in-android-activity

**Comment by varungupta85** [comment]
@machour Thanks for the quick reply. Please let me know if I should close the issue. I see that you have added some labels. Not sure if you mean to add some documentation for it and then close it.

**Comment by machour** [comment]
Yes, we need to document this in the README file so I'm keeping this issue open as a reminder.
Feel free to open a PR for this, that would be helpful!

**Comment by varungupta85** [comment]
Okay, I will send a PR.
