### ISSUE TITLE
Undefined is not an object deviceCountry() in emulator. And elsewhere?

### ISSUE THREAD

**Issue by paintedbicycle** [rebeccahughes/react-native-device-info#330]
## Summary

|             |     |
| ----------- | --- |
| Version     | 15.3   |
| Affected OS | Android   |
| OS Version  | 8   |

## Current behavior

I received this undefined object error when using deviceCountry() in an emulator. I do not have a physical Android device to test with, so I can't verify if it's emulator specific, but I'm assuming the emulator is not returning a device country and so it's crashing. 

I would imagine however, that this is theoretically possible on a physical device too and should be fixed.

One last thing to note is that because of a conflict with Google Play Services versions I edited RNDeviceInfo to remove that dependency and installed it project-wide instead. I don't think it's related, but it could be, so I thought I'd mention it.

<img width="233" alt="screen shot 2018-02-19 at 4 08 28 pm" src="https://user-images.githubusercontent.com/371114/36384566-012c5ca0-1590-11e8-83ff-9491f540eb56.png">

## Expected behavior

We should return a device country or null if none found.

**Comment by machour** [comment]
Hi @paintedbicycle, I think that in this case, it's RNDeviceInfo which is undefined.
Can you make sure that you linked the library properly?

**Comment by paintedbicycle** [comment]
Oh how weird. OK, yep you're right, it became unlinked.

**Comment by lmichailian** [comment]
@paintedbicycle how you solve this ?

**Comment by paintedbicycle** [comment]
@lmichailian - My react-native-device-info package had become unlinked in Android. Check to make sure:

This is in settings.gradle:
`
include ':react-native-device-info'
project(':react-native-device-info').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-device-info/android')
` 

This is in /app/build.grade:
`
dependencies {
    compile project(':react-native-device-info')
}
`

and these are in MainApplication.java:
`
import com.learnium.RNDeviceInfo.RNDeviceInfo;
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new MainReactPackage(),
        new RNDeviceInfo(),
      );
    }
`
