### ISSUE TITLE
getFreeDiskStorage returns negative number

### ISSUE THREAD

**Issue by L3V147H4N** [rebeccahughes/react-native-device-info#331]
## Summary
Happens on multiple devices
![image](https://user-images.githubusercontent.com/5846479/36487176-0dba5fa6-16ff-11e8-9967-f5811c5a1635.png)

Windows 10 PRO

## Current behavior

Returns negative number for Free Disk Storage

## Expected behavior

Returns number of bytes for Free Disk Storage

**Comment by machour** [comment]
Weird, here's the code again for this: https://github.com/rebeccahughes/react-native-device-info/blob/master/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L144

I'm wondering if we're not overflowing the Integer here.. what's the actual free disk space on the affected devices?

**Comment by L3V147H4N** [comment]
sadly I don't have access to those devices, they are used by employees of my client and we are not in the same city so I would not be able to tell, I have a few devices of my own I'll test to see if the same bug appears in one of them

**Comment by L3V147H4N** [comment]
Perhaps tomorrow I could get some more information

**Comment by DracoBlue** [comment]
I think a long should be ok, too.

**Comment by DracoBlue** [comment]
A possible solution could be to add a new function, which returns the storage in mb with everything after the `.` beeing the kb.

So we get rid of the long/int and have float.

E.g: 1200000 becomes 1.2

**Comment by winadiw** [comment]
i also got that problem when getting `getTotalDiskCapacity()`, how to solve this problem?

**Comment by jamninetyfive** [comment]
any new？getTotalDiskCapacity thx@machour

**Comment by hannigand** [comment]
Any progress on this? `getFreeDiskStorage` and `getTotalDiskCapacity` are both returning negative numbers.

Device: OnePlus 3
OS: OxygenOS Version 5.0.5
Android Version: 8.0.0

**Comment by katieisnell** [comment]
I am also having this issue with both `getFreeDiskStorage` and `getTotalDiskCapacity` on emulators and my phone

Device: Pixel 2
Android version: 8.1.0

and also on

Device: OnePlus 3T
OS: OxygenOS 4.5.1
Android vers: 7.1.1

My Pixel is 1GB with 100MB external storage but `getFreeDiskStorage` gives me 576454656
and `getTotalDiskCapacity` is -1694711808.

**Comment by jamninetyfive** [comment]
> 任何新的？thx @machour

**Comment by jamninetyfive** [comment]
@knot123 thx
