### ISSUE TITLE
getFreeDiskStorage returns internel or external? Docs wrong?

### ISSUE THREAD

**Issue by L3V147H4N** [rebeccahughes/react-native-device-info#332]
## Summary

I tested on android 6.

The Note on the Docs says it returns external free space for Android but in my case it's actually returning (correctly) the internal free Storage, this is good, but are the docs wrong?

## Current behavior

returns internal free disk storage

## Expected behavior

?

**Comment by machour** [comment]
Hi @L3V147H4N, here's the java function used to retrieve the info:
  https://github.com/rebeccahughes/react-native-device-info/blob/master/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L143

Looking at its [documentation](https://developer.android.com/reference/android/os/Environment.html#getExternalStorageDirectory()), it seems like you're right:

> Note: don't be confused by the word "external" here. This directory can better be thought as media/shared storage. It is a filesystem that can hold a relatively large amount of data and that is shared across all applications (does not enforce permissions). Traditionally this is an SD card, but it may also be implemented as built-in storage in a device that is distinct from the protected internal storage and can be mounted as a filesystem on a computer.

Would you like to open a PR to fix the documentation in the README.md file?

**Comment by L3V147H4N** [comment]
Sure, I'll get to it tonight 👍
