### ISSUE TITLE
library not found for -lRNDeviceInfo-tvOS

### ISSUE THREAD

**Issue by nasy** [rebeccahughes/react-native-device-info#336]
I just installed the library, and before the project was building fine, now I just get this error:

react-native run-ios
-------------

Error:

ld: library not found for -lRNDeviceInfo-tvOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

**Comment by machour** [comment]
Hi, this is a know problem with a known solution:
  https://github.com/rebeccahughes/react-native-device-info#troubleshooting

**Comment by nasy** [comment]
Sorry I did not see that section! Works great now :
