### ISSUE TITLE
Label this issue as question

### ISSUE THREAD

**Issue by koswarabilly** [rebeccahughes/react-native-device-info#340]
can anyone tell me what it means by this? 
**This is IDFV so it will change if all apps from the current apps vendor have been previously uninstalled.**

what condition that will change device IDFV ?? apps vendor? who is the app vendor?

**Comment by machour** [comment]
Check https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor (which is now linked from the README.md file)
