### ISSUE TITLE
iOS automatic linking is not working. 

### ISSUE THREAD

**Issue by rohitgoyal** [rebeccahughes/react-native-device-info#353]
## Summary

Version: 0.17.4 

## Current behavior

RNDeviceInfo automatic linking fails on iOS while it shows success on terminal.
## Expected behavior

RNDeviceInfo should be present in Libraries in Xcode.

**Comment by machour** [comment]
Hi, what's the command you're using?

**Comment by dougjedwards** [comment]
I'm having exactly the same issue.

I'm using:
react-native link react-native-device-info

**Comment by SandroMachado** [comment]
Same here!

**Comment by machour** [comment]
Just tested this on a ejected CRNA, the library gets correctly linked for me:

<img width="275" alt="screen shot 2018-03-12 at 5 42 12 pm" src="https://user-images.githubusercontent.com/304450/37296982-cfa90686-261c-11e8-94df-cd9a8dd2be8a.png">

If however, you're facing the following error : `ld: library not found for -lRNDeviceInfo-tvOS`
You can manually delete libRNDeviceInfo-tvOS.a in Xcode -> [Your iOS build target] -> Build Phrases -> Link Binary with Libraries. It's a react-native link bug.

**Comment by SandroMachado** [comment]
My project uses `lerna` and so on, so, probably can be related to that.

**Comment by schumannd** [comment]
@machour i am getting that exact error. Shouldn't this be handled by `react-native link`?

**Comment by machour** [comment]
@schumannd it currently works for me so I'm not seeing the problem.. could you investigate a bit?

**Comment by tamhv** [comment]
```
1. yarn add react-native-device-info
2. react-native link react-native-device-info
3. react-native run-ios
4. console.log("DEVICE NAME",DeviceInfo.getDeviceName())
```
I got js error `TypeError: undefined is not an object (evaluating 'RNDeviceInfo.deviceName')` 

I notice there is a line `pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'` in my Podfile after i ran `react-native link` 

Do i need to `cd ios && pod install` ?

Actually i've tried to pod install
```
# cd ios
# pod install
Analyzing dependencies
Fetching podspec for `RNDeviceInfo` from `../node_modules/react-native-device-info`
Downloading dependencies
...
Installing RNDeviceInfo (0.21.2)
...
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 7 dependencies from the Podfile and 14 total pods installed.
```
Then xcode can't build, error 
```
RCTBridgeModule.h' file not found
In file included from /node_modules/react-native-device-info/RNDeviceInfo/RNDeviceInfo.m
```

```
version:
npm                5.5.1
node               9.3.0
react-native-cli   2.0.1
app rn version     0.50.4
xcode              9.2
```

**Comment by whatvn** [comment]
got same problem, DeviceInfo.getFontScale() always return undefined

**Comment by machour** [comment]
@whatvn if it returns undefined instead of erroring because "Device info" is undefined, it's not the same problem. 
Please open a new issue for that.

**Comment by machour** [comment]
@tamhv : you shouldn't be mixing "link" and pods. 

If you use the pods, you must define your React pod dependency in your own Podfile. 

If you're using link, check the manual linking section to see what went wrong in the automatic process. 

I currently don't have any problem with link, so I really can't do a thing about this issue :/

**Comment by tamhv** [comment]
@machour yeah i'm ok with `add *.xcodeproj *.a for ios and react-native link for android`, so because i was using pods for other packages then i can't use react-native link right?

After run react-native link, android works, i have to remove the line `pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'` from my Podfile, then `add *.xcodeproj and *.a` for ios

**Comment by rhdeck** [comment]
Problem is that react-native link is more persnickety about where the IOS code should be. To fix, move to the /ios subdirectory of module. implementation at rhdeck/react-native-device-info, and submitted PR #374

**Comment by whatvn** [comment]
@machour if Device Info is undefined, app should be crash. How can you call DeviceInfo.getFontScale() and it return `undefined` when DeviceInfo is undefined? It's the same problem. I believe @rhdeck 's solution work

**Comment by machour** [comment]
@whatvn Reading your first comment, I understand that `DeviceInfo` is not undefined in your case, but `DeviceInfo.getFontScale()` returns undefined. Which is an issue. But a different one. 

This is why I encouraged you to open a new issue, distinct from this one.

Now if I didn't understand your comment, which is totally possible, just re-explain things to me :)

**Comment by machour** [comment]
@rhdeck thanks for the PR man, just shipped it in 0.21.3 

@rohitgoyal @dougjedwards @SandroMachado @schumannd : could you give this new release a try?

**Comment by sdovenor** [comment]
@machour this seems to be a breaking change for anyone that is currently using 
```
pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
```
in their Podfile without having to manually update their Podfile to /ios or re-link, see #376

**Comment by machour** [comment]
Thank you so much for spotting that @sdovenor, 0.21.4 is out with your fix!

**Comment by tkhwang** [comment]
I'm a total newbie, but I got the same error above even with the new patched version  `0.21.4`.

```
ld: library not found for -lRNDeviceInfo-tvOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **
```

* version:

```
"react-native-device-info": "^0.21.4",
npm                4.6.1
node               8.9.4
react-native-cli   2.0.1
react-native       0.52.0
xcode              9.2
```

* Command

```
- create-react-native-app projectName
- npm run eject
- yarn add react-native-device-info
- react-native link react-native-device-info
- react-native run-ios
```

But I could delete `libRNDeviceInfo-tvOS.a` for the build success.

```
You can manually delete libRNDeviceInfo-tvOS.a in Xcode -> [Your iOS build target] -> Build Phrases -> Link Binary with Libraries. It's a react-native link bug.
```

**Comment by machour** [comment]
@tkhwang this is not what this PR was trying to solve, so it's normal ;)

**Comment by tkhwang** [comment]
@machour 👍 I got it. Thanks a lot.

**Comment by benevbright** [comment]
I'm sorry. 
But I don't understand why this module needs Pod and linking command adds that line on `Podfile` since it can work without Pod?

**Comment by machour** [comment]
@benevbright I'm not sure I understand your question. You can either use "react-native link" OR the pods way.

**Comment by ishan123456789** [comment]
What I found was that `Podfile.lock` file wasn't updated after running `react-native link react-native-device-info` so I fixed by running `pod install` again in the IOS folder and it said installing RNDeviceInfo that means you need to run `pod install` after running `react-native link react-native-device-info`

**Comment by mikehardy** [comment]
Ah, that makes sense. Any time you alter your Podfile, you must run pod install, yes. This sort of thing (the class of misunderstandings) will become important to have good documentation on as Pods will be the recommended react-native way from RN0.60 on. @ishan123456789 - is there some part of the README.md file that could be improved for this? If so, do you want to propose a PR to improve it?

**Comment by ishan123456789** [comment]
Sure I'll do that @mikehardy
