### ISSUE TITLE
Device information in one line

### ISSUE THREAD

**Issue by antofa** [rebeccahughes/react-native-device-info#360]
Hi, buddies. If is there method for getting device information by one call or any other solution for this?

Something like this:
Android v25.0.2, Redmi Note 3, ru.
iOS v10, iPad 6,3, en.

Thanks.

**Comment by machour** [comment]
Hi @antofa, there's no such method as its output would really depends on your requirements.
You can use getBrand(), getModel(), getSystemVersion() etc to achieve this.
