### ISSUE TITLE
Unable to build - more than one library with package name 'com.google.android.gms.license'

### ISSUE THREAD

**Issue by GaudamThiyagarajan** [rebeccahughes/react-native-device-info#366]
## Current behavior
react-native run-android

:react-native-device-info:processReleaseManifest
:react-native-device-info:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-device-info:processReleaseResources'.
> Error: more than one library with package name 'com.google.android.gms.license'

BUILD FAILED

Total time: 42.342 secs

## Expected behavior

It was working fine the previous day. no changes was made to build.gradle files

## dependecies

```
dependencies {
    compile project(':react-native-splash-screen')
    compile project(':react-native-svg')
    compile project(':react-native-linear-gradient')
    compile 'com.facebook.fresco:fresco:1.5.0'
    compile 'com.facebook.fresco:animated-gif:1.5.0'
    compile project(':react-native-fetch-blob')
    compile group: 'net.lingala.zip4j', name: 'zip4j', version: '1.3.2'
    compile project(':appcenter-crashes')
    compile project(':appcenter-analytics')
    compile project(':appcenter')
    compile project(':react-native-code-push')
    compile project(':react-native-sentry')
    compile 'com.amplitude:android-sdk:2.13.4'
    compile project(':react-native-amplitude-analytics')
    compile project(':react-native-fbsdk')
    compile(project(":react-native-google-signin")){
      exclude group: "com.google.android.gms" // very important
    }
    compile 'com.google.android.gms:play-services-auth:9.2.1' // should be at least 9.0.0
    compile project(':react-native-orientation-locker')
    compile(project(':react-native-device-info')) {
      exclude group: "com.google.android.gms" // very important
    }
    compile project(':react-native-vector-icons')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:27.0.2"
    compile "com.facebook.react:react-native:+"  // From node_modules
}
```

**Comment by yangtaufoo** [comment]
Please refer to #365

**Comment by GaudamThiyagarajan** [comment]
allprojects {
    repositories {
        configurations.all {
            resolutionStrategy {
                force "com.google.android.gms:play-services-gcm:11.8.0"
            }
        }
        ....
   }
}

adding this to my build.gradle file fixed the issue.

> note: I had to add  force "com.google.android.gms:play-services-auth:11.8.0" as i was using google sign in.

**Comment by machour** [comment]
Hi @GaudamThiyagarajan, 

Instead of the resolutionStrategy thing, could you try defining the following variable in your `android/build.gradle` file:

 ext {
    googlePlayServicesVersion = "11.8.0"
}

that would tell react-native-device-info to use that version for com.google.android.gms.

Let me know if that fixes the issue for you so that I can make this clearer in the README (it's actually hidden under Android linking)

**Comment by dverma4u** [comment]
@machour after adding your suggested variable new build error came
* What went wrong:
Execution failed for task ':react-native-google-signin:processReleaseResources'.
> Error: more than one library with package name 'com.google.android.gms.license'

**Comment by machour** [comment]
@dverma4u that line tells react-native-device-info which version to use. Is there another or others packages specifying different versions of com.google.android.gms ?

**Comment by dverma4u** [comment]
@machour yes react-native-onesignal also uses google services.

**Comment by ikhsanalatsary** [comment]
@machour I got this error after added your solution
```
* What went wrong:
Execution failed for task ':react-native-fcm:processReleaseResources'.
> Error: more than one library with package name 'com.google.android.gms.license'
```

**Comment by ikhsanalatsary** [comment]
I've got the solution [here](https://github.com/evollu/react-native-fcm/issues/857)

**Comment by vliedel** [comment]
Hey @GaudamThiyagarajan it does make the version change to 11.8.0 (checked with `./gradlew -q app:dependencies`, but i still get the same error. Any idea?

**Comment by jstheoriginal** [comment]
Indeed this is what solved it for me.

https://github.com/facebook/react-native/issues/18479#issuecomment-374849967

**Comment by nhancv** [comment]
My approach is can all android project and update version of google play services directly to each module build.gradle
Detail here: https://medium.com/p/2fd245027832
Hope it can help you.

**Comment by otusweb** [comment]
@machour your fix fixed it for me. 
In the instructions it is marked as optional and there is not explanation as to why one might want to do this. It would be great to explain this.

**Comment by machour** [comment]
Let's move this to #365
