### ISSUE TITLE
Maintainers Wanted

### ISSUE THREAD

**Issue by joanbarros** [rebeccahughes/react-native-device-info#37]
Hi,

Mi name is Joan Barros. I'm currently trying to use this module in a project of mine and If no one else can do it then I guess I could maintain it.

Other candidates please comment on this issue with your proposal.

Regards.

**Comment by jeroenbourgois** [comment]
I want to give it a go too, or help at least :)

**Comment by rebeccahughes** [comment]
I've made you both committers although you'll need to create npm accounts before I add you on there too

**Comment by GantMan** [comment]
Question:  Why wouldn't this info be added to React Native's Platform object?  Seems like it's mature and stable enough.

As of right now, RN has the stub for Platform detection, and even version on Android.  It seems like if this project is needing maintainers, it would be idea to try to get it into React Native core as properties we could expect from this, and all future devices.

Platform ios -> https://github.com/facebook/react-native/blob/235b16d93287061a09c4624e612b5dc4f960ce47/Libraries/Utilities/Platform.ios.js

Platform android -> https://github.com/facebook/react-native/blob/235b16d93287061a09c4624e612b5dc4f960ce47/Libraries/Utilities/Platform.android.js

**Comment by rebeccahughes** [comment]
I actually have a PR that does just that but the RN team wanted it in a separate module
Question:  Why wouldn't this info be added to React Native's Platform object?  Seems like it's mature and stable enough.

As of right now, RN has the stub for Platform detection, and even version on Android.  It seems like if this project is needing maintainers, it would be idea to try to get it into React Native core as properties we could expect from this, and all future devices.

Platform ios -> https://github.com/facebook/react-native/blob/235b16d93287061a09c4624e612b5dc4f960ce47/Libraries/Utilities/Platform.ios.js

Platform android -> https://github.com/facebook/react-native/blob/235b16d93287061a09c4624e612b5dc4f960ce47/Libraries/Utilities/Platform.android.js

---

**Comment by GantMan** [comment]
That's really interesting @rebeccahughes - Thanks!

**Comment by lilach** [comment]
I would like to maintain (or at least help with maintaining) this module too :)

**Comment by sgaurav** [comment]
Hi,

I am Gaurav and have been using this package in my production app. If you are looking for more maintainers, I would love to be a part.

My npm id is same as github.

Thanks,
Gaurav

**Comment by GantMan** [comment]
I'd like to be a maintainer as well.   Then I think it might be time to remove the maintainers wanted from github README. :)

I'll consider it my first task.

**Comment by lilach** [comment]
Hi Rebecca,
Thank you for making me a collaborator on this repository. Please also add me as one to npm: [@lilach](https://www.npmjs.com/~lilach)
