### ISSUE TITLE
Import instructions in .d.ts file seems off

### ISSUE THREAD

**Issue by kasl** [rebeccahughes/react-native-device-info#372]
About usage this library: 
Readme [here](https://github.com/rebeccahughes/react-native-device-info#usage) said that I should import the following way: `import DeviceInfo from 'react-native-device-info'`, but this not worked and i found in `deviceinfo.d.ts`  [the following comment](https://github.com/rebeccahughes/react-native-device-info/blob/master/deviceinfo.d.ts#L2)
```
// should be imported this way:
// import * as DeviceInfo from 'react-native-device-info';
```

**Comment by machour** [comment]
@kasl README is correct, the .d.ts should be fixed.
Wanna do your first PR here?

**Comment by kasl** [comment]
unfortunately I'm new to type script. Last i see this PR https://github.com/rebeccahughes/react-native-device-info/pull/221 where fixed ts definitions and [here](https://github.com/rebeccahughes/react-native-device-info/issues/208#issuecomment-365624420) you says that all right. Why now d.ts incorrect?

**Comment by machour** [comment]
@kasl I really didn't notice the import change in #221. To be honest, I was just trying to close some old issues as I took over this project maintenance :D 

Definitely worth investigating, thank you for spotting this.

**Comment by mikehardy** [comment]
@machour this is closable, my app uses TypeScript and after the PR for the PIN method ( #588  ) the module integrates cleanly with no errors using the documentation provided
