### ISSUE TITLE
Crash Android

### ISSUE THREAD

**Issue by leventyildirim61** [rebeccahughes/react-native-device-info#380]
Hello everyone.

I have a problem about these. When upgrade compileSdkVersion in android, app is crash. Crash looks like these.
![ekran resmi 2018-04-04 11 11 59](https://user-images.githubusercontent.com/3340969/38296276-940681aa-37f9-11e8-9a64-170a55403847.png)

**Comment by machour** [comment]
Hi @leventyildirim61 

FYI, The Bluetooth thing can be ignored, as the error is catched by the library.

**Comment by mikehardy** [comment]
@machour this is closable - it will be something user-specific, the module installs and runs fine on a clean react-native app right now
