### ISSUE TITLE
ID Methods Should be Named Consistently

### ISSUE THREAD

**Issue by micodel** [rebeccahughes/react-native-device-info#385]
## Description

As a developer, I would find it beneficial for ID methods to be named consistently.

For example:
getBundleId() and getDeviceId() have a lowercase "d"

Whereas:
getInstanceID() and getUniqueID() have an uppercase "D"

I typically lean towards "Id", but thats completely up to you, just whatever pattern you choose please be consistent! :)

Thanks in Advance

**Comment by machour** [comment]
Thank you for raising this issue. Should be addressed in v1.x (#307)
