### ISSUE TITLE
Be able to check 32-bit or 64-bit

### ISSUE THREAD

**Issue by 7kfpun** [rebeccahughes/react-native-device-info#386]
## Description

Able to check 32-bit or 64-bit.

## Use Case

Some feature need at least 64-bit architecture, this would be very useful to check the system architecture.

**Comment by mikehardy** [comment]
@machour -- this is closable I think - should be a duplicate / an upvote on #578 - I left a note there recently, there's implementation information for iOS and Android but it needs a PR
