### ISSUE TITLE
Error:getDeviceCountry is not a function  in jest

### ISSUE THREAD

**Issue by leogeng** [rebeccahughes/react-native-device-info#390]
## Summary

| ----------- | --- |
| Version     | 
"jest": "21.2.1",
"babel-jest": "21.2.0",
"react": "^16.3.0-alpha.1",
    "react-native": "0.53.0",
    "react-native-device-info:"v0.17.3"
|
| Affected OS | ?   |
| OS Version  | macOS   |

## Current behavior

● Test suite failed to run

    TypeError: _reactNativeDeviceInfo2.default.getDeviceCountry is not a function

**Comment by machour** [comment]
Hi @leogeng, you need to lock this library for jest

**Comment by machour** [comment]
See last entry here: https://github.com/rebeccahughes/react-native-device-info/blob/290ad0163a97b5eab8d4011f4721956d229c993d/README.md#troubleshooting
