### ISSUE TITLE
getApplicationName undefined

### ISSUE THREAD

**Issue by qq912276337** [rebeccahughes/react-native-device-info#391]
why getApplicationName() is undefined use version 0.21.5 iOS

**Comment by enricotelesca-ada** [comment]
I have a similar issue: getBundleId of undefined. 
0.21.5 iOS
RN 0.54.2

**Comment by machour** [comment]
Use the template to report a problem.

**Comment by billxie1988** [comment]
remove the libRNDeviceInfo-tvOS.a work for me
