### ISSUE TITLE
Installing is stuck

### ISSUE THREAD

**Issue by sandropoluan** [rebeccahughes/react-native-device-info#395]
Installing is stuck here

λ npm i --save react-native-device-info
[          ........] | extract:fsevents: sill extract fsevents@1.2.2 extracted to C:\ReactProject\ArtherChat\node_modules\.staging\fsevents-46551938 (618ms)

[**Windows 10**]

**Comment by machour** [comment]
@sandropoluan is this still happening for you?

**Comment by sandropoluan** [comment]
I decided to not using this lib for a while.
And today I trying to install it  And I got this problem

```
"λ npm i --save react-native-device-info
npm WARN tarball tarball data for react-native-device-info@^0.21.5 (sha512-Bvl7TyVMDbBH3wzvZx0xj3deMhWVRDHdOdjP1MjGVxVVH+bSlCi6oYDScaX2yz5rfi2OvevWWCg8jUqFKeepjA==) seems to be corrupted. Trying one more time.
[            ......] \ extract:react-native: WARN tarball tarball data for react-native-device-info@^0.21.5 (sha512-Bvl7TyVMDbBH3wzvZx0xj3deMhWVRDHdOdjP1MjGVxVVH+bSlCi
"
```
And then it stuck

**Comment by Belal13ify** [comment]
i have the same problem, did you find any solution to this tarball data for react native problem?

**Comment by guptahim2000** [comment]
hi ,
is this problem solved?

**Comment by kaixiniOSTT** [comment]
not solved
