### ISSUE TITLE
getBatteryLevel() always returns -1 using real iOS device

### ISSUE THREAD

**Issue by anwarhamr** [rebeccahughes/react-native-device-info#396]
## Summary

|             |     |
| ----------- | --- |
| Version     | 21.5   |
| Affected OS | iOS  |
| OS Version  |  11.3 |

when getBatteryLevel promise resolves the value is always -1.

**Comment by machour** [comment]
Waiting for your input on #404

**Comment by mikehardy** [comment]
#404 just merged, but note @hickeyadamc it was mostly a documentation update. You need to add an enabling calling in your AppDelegate, the API docs point out what to do

@machour my favorite -> should close, already merged
