### ISSUE TITLE
IsTablet false on every Ipad emulator

### ISSUE THREAD

**Issue by kashifsulaiman** [rebeccahughes/react-native-device-info#397]
## Description

I've checked that isTablet is false on every Ipad but seems working on Android correctly.

## Use Case

![image](https://user-images.githubusercontent.com/11738465/39692646-dbb41164-51fa-11e8-939c-fd75adf90b76.png)

**Comment by machour** [comment]
Hi @kashifsulaiman, is your app setup as an iPhone-only app, an iPad-only app, or as a universal app?

**Comment by kashifsulaiman** [comment]
@machour yes, it was IPhone-only, when I switch to iPad-only, it worked. Closing
