### ISSUE TITLE
com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependencyCacheDir(Ljava/io/File;)V

### ISSUE THREAD

**Issue by mounlion** [rebeccahughes/react-native-device-info#398]
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-device-info'.
      > Failed to notify project evaluation listener.
         > com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependencyCacheDir(Ljava/io/File;)V

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

```

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.google.gms:google-services:3.2.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

```
"react-native-device-info": "^0.21.5"
```

**Comment by mounlion** [comment]
I forgot update build:gradle to 
```
classpath 'com.android.tools.build:gradle:3.1.2'
```

**Comment by haron68** [comment]
Did you solve this issue? Because I am currently encountering exactly the same thing during my build process.

**Comment by kapil708** [comment]
> I forgot update build:gradle to
> 
> ```
> classpath 'com.android.tools.build:gradle:3.1.2'
> ```

also work for me thanks

**Comment by bklutse20** [comment]
I am having this issue. can anyone help?

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-fs'.
      > Failed to notify project evaluation listener.
         > com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependencyCacheDir(Ljava/io/File;)V

**Comment by XeeshanAnsari** [comment]
please update the files

android/gradle/gradle-wrapper.properties
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip

android/build.gradle
classpath 'com.android.tools.build:gradle:3.0.1'

and also add the google() in the buildscript/repositories
buildscript {
    repositories {
        jcenter()
        google()
    }
}
