### ISSUE TITLE
getUniqueID in iOS looks persistent

### ISSUE THREAD

**Issue by akiradeveloper** [rebeccahughes/react-native-device-info#399]
In README it describes `getUniqueID` in iOS is IDFV and it's reset after uninstalled

> iOS: This is IDFV so it will change if all apps from the current apps vendor have been previously uninstalled.

but from the actual implementation I feel like it's not

```
/*! Returns the Device UID.
    The UID is obtained in a chain of fallbacks:
      - Keychain
      - NSUserDefaults
      - Apple IFV (Identifier for Vendor)
      - Generate a random UUID if everything else is unavailable
    At last, the UID is persisted if needed to.
 */
- (NSString *)uid {
    if (!_uid) _uid = [[self class] valueForKeychainKey:_uidKey service:_uidKey];
    if (!_uid) _uid = [[self class] valueForUserDefaultsKey:_uidKey];
    if (!_uid) _uid = [[self class] appleIFV];
    if (!_uid) _uid = [[self class] randomUUID];
    [self save];
    return _uid;
}
```

because it saves the IDFV in the key chain and restore it the next time as https://api.playfab.com/docs/tutorials/landing-players/best-login advices as the best pratice.

> For iOS devices, the ID the player has changes if they uninstall your games and then re-install. One way to make sure you have a consistent ID on iOS is to save the Device ID for the player to the iTunes KeyChain, so that you can read it from there on game start, and use it to sign in.

Is the README wrong? In that case, let's fix it as it is just confusing.

**Comment by machour** [comment]
@akiradeveloper just to be clear:

The actual result you get is either the IFV or a random UUID.

What is read from Keychain / NSUserDefaults is one of the above values, that we cached when we first computed the uid. Both these stores are cleared when the app is uninstalled.

And if the user uninstall all apps from the same vendor, then the IFV value may change the next time it's read.

Are we on the same page?

How would you update the documentation for this part ?

**Comment by lefloh** [comment]
Does this mean that a user may become the same ID on a new device if he restores a backup from an other device (if the keychain is part of the backup)?
