### ISSUE TITLE
Accessing device attributes from native code

### ISSUE THREAD

**Issue by chris-erickson** [rebeccahughes/react-native-device-info#4]
Is it possible to access these attributes from native code (Swift in my case) somehow?  This is one of the few modules that it would be really helpful to make use of that info, instead of duplicating much of it.  I understand this is a bit of an edge case and I'd be happy to make a PR if it's even a thing.

Works great in React, though!

**Comment by rebeccahughes** [comment]
I've never really used Swift so I don't know what i'd be doing. Happy to accept PR's though :)

**Comment by chris-erickson** [comment]
Well [this won't generate a PR](http://stackoverflow.com/a/34166462/2057885), but maybe it's a solution?  It might be terrible, but I rarely need this and it gets the job done.  In any case, I can close this issue for now.

**Comment by chris-erickson** [comment]
Looks like we have [a winner.](http://stackoverflow.com/a/34166990/2057885)

**Comment by rebeccahughes** [comment]
Great :)
