### ISSUE TITLE
getIPAddress is not working

### ISSUE THREAD

**Issue by sarathvad1811** [rebeccahughes/react-native-device-info#400]
The function getIPAddress() is not working. It says "cannot find function RNDeviceInfo.getIpAddress"

All other functions related DeviceInfo working fine only this one doesn't work.
| Version     | 0.21.5 |
| Affected OS | iOS, Android  |
| OS Version  | ios9, Android 7  |

## Current behavior

Promise of the function DeviceInfo.getIPAddress() returns an error saying "cannot find function RNDeviceInfo.getIpAddress". 

Please Help!! Thanks in advance!!

**Comment by domoniquecarter35** [comment]
I have also seen this issue.

**Comment by machour** [comment]
This is really weird. Can you try editing the native module to see what is going wrong?

**Comment by gohabereg** [comment]
Getting the same issue on iOS. 
Seems there is no exported `getIpAddress` method in RNDeviceInfo.m file.

https://github.com/rebeccahughes/react-native-device-info/blob/master/ios/RNDeviceInfo/RNDeviceInfo.m#L267

**Comment by johhansantana** [comment]
I'm getting something similar when doing any of the functions:
![1](https://user-images.githubusercontent.com/9933887/40792501-15f02964-64c8-11e8-88f0-98186186c777.png)

**Comment by hzburki** [comment]
![screen shot 2018-06-12 at 4 48 29 am](https://user-images.githubusercontent.com/17387720/41262719-df665fc0-6dfb-11e8-98b5-c6668cb30df5.png)

Getting the same error ... help please.

**Comment by jason2li** [comment]
Any updates on this?  I'm getting the same thing.

**Comment by machour** [comment]
Added `getIpAddress` and `getMacAddress` for iOS in 0.22.0

**Comment by sarathvad1811** [comment]
Thank you !!! <3
