### ISSUE TITLE
getDeviceName does not return device name on android

### ISSUE THREAD

**Issue by amirmatin** [rebeccahughes/react-native-device-info#402]
## Summary

|             |     |
| ----------- | --- |
| Version     | react-native: 0.55.3 |
| Affected OS | Android  |
| OS Version  | API 26   |

## Current behavior

getDeviceName returns unknown in Android. I have added following to AndroidManifest.xml

    uses-permission android:name="android.permission.BLUETOOTH"
    uses-permission android:name="android.permission.BLUETOOTH_ADMIN"

## Expected behavior

To return device name. 
Any help is much appreciated. thanks

**Comment by machour** [comment]
Hi @amirmatin, for what react-native-device-info version? What device are you using for your tests?

**Comment by amirmatin** [comment]
it is sorted now. there was an error in auto linking
