### ISSUE TITLE
Android can't run

### ISSUE THREAD

**Issue by showtan001** [rebeccahughes/react-native-device-info#413]
## Summary

|             |     |
| ----------- | --- |
| Version     | 0.21.5  |
| Affected OS | Android   |
| OS Version  | 7.0   |

## Current behavior
`* What went wrong:
A problem occurred configuring project ':react-native-device-info'.
> Could not resolve all dependencies for configuration ':react-native-device-inf
o:_debugPublishCopy'.
   > Could not find com.android.support:support-v4:26.1.0.
     Searched in the following locations:
         file:/D:/Android/sdk/extras/android/m2repository/com/android/support/su
pport-v4/26.1.0/support-v4-26.1.0.pom
         file:/D:/Android/sdk/extras/android/m2repository/com/android/support/su
pport-v4/26.1.0/support-v4-26.1.0.aar
         file:/D:/project/read/android/sdk-manager/com/android/support/support-v
4/26.1.0/support-v4-26.1.0.aar
     Required by:
         yuecai:react-native-device-info:unspecified > com.facebook.react:react-
native:0.46.4 > com.android.support:appcompat-v7:23.0.1
   > Could not find com.android.support:support-v4:26.1.0.
     Searched in the following locations:
         file:/D:/Android/sdk/extras/android/m2repository/com/android/support/su
pport-v4/26.1.0/support-v4-26.1.0.pom
         file:/D:/Android/sdk/extras/android/m2repository/com/android/support/su
pport-v4/26.1.0/support-v4-26.1.0.aar
         file:/D:/project/read/android/sdk-manager/com/android/support/support-v
4/26.1.0/support-v4-26.1.0.aar
     Required by:
         yuecai:react-native-device-info:unspecified > com.google.android.gms:pl
ay-services-gcm:15.0.1 > com.google.android.gms:play-services-basement:15.0.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.`

## Expected behavior

help me! thanks.

**Comment by JerryOSJ** [comment]
me too. help me! thanks.

**Comment by xwartz** [comment]
+1

**Comment by xPotion** [comment]
+1

**Comment by catnuxer** [comment]
Same here here debug.

> 
> les-2.1\com.squareup.okhttp3\okhttp-urlconnection\3.6.0\3f9b16b774f2c36cfd86dd2053d0b3059531dacc\okhttp-urlconnection-3.6.0.jar
> 14:54:28.886 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Found artifact 'android-jsc.aar (org.webkit:android-jsc:r174650)' in resolver cache: C:\Users\Nextglaptop\.gradle\caches\modules-2\files-2.1\org.webkit\android-jsc\r174650\880cedd93f43e0fc841f01f2fa185a63d9230f85\android-jsc-r174650.aar
> 14:54:28.887 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/E:/Workspace/www/gitlab/react-native/erbenetwork/node_modules/react-native/android/com/facebook/react/react-native/0.53.3/react-native-0.53.3.aar
> 14:54:28.888 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Detected non-existence of artifact 'play-services-basement.aar (com.google.android.gms:play-services-basement:15.0.1)' in resolver cache
> 14:54:28.914 [ERROR] [org.gradle.BuildExceptionReporter]
> 14:54:28.914 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
> 14:54:28.918 [ERROR] [org.gradle.BuildExceptionReporter]
> 14:54:28.918 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
> 14:54:28.918 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred configuring project ':app'.
> 14:54:28.918 [ERROR] [org.gradle.BuildExceptionReporter] > Could not resolve all dependencies for configuration ':app:_debugApk'.
> 14:54:28.922 [ERROR] [org.gradle.BuildExceptionReporter]    > A problem occurred configuring project ':react-native-device-info'.
> 14:54:28.922 [ERROR] [org.gradle.BuildExceptionReporter]       > Could not find play-services-basement.aar (com.google.android.gms:play-services-basement:15.0.1).
> 14:54:28.922 [ERROR] [org.gradle.BuildExceptionReporter]         Searched in the following locations:
> 14:54:28.922 [ERROR] [org.gradle.BuildExceptionReporter]             https://jcenter.bintray.com/com/google/android/gms/play-services-basement/15.0.1/play-services-basement-15.0.1.aar
> 14:54:28.922 [ERROR] [org.gradle.BuildExceptionReporter]
> 14:54:28.922 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
> 14:54:28.922 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.
> 14:54:28.922 [LIFECYCLE] [org.gradle.BuildResultLogger]
> 14:54:28.922 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
> 14:54:28.922 [LIFECYCLE] [org.gradle.BuildResultLogger]
> 14:54:28.922 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 8.708 secs


I try to update build tools, looking for good news here, 

I have try add
`compile ("com.google.android.gms:play-services-basement:+") { force = true; }`

But still not working.

**Comment by NunoFl** [comment]
+1

**Comment by LeiStudio** [comment]
me too, help me!!

**Comment by NunoFl** [comment]
+1 cake

**Comment by Richi2293** [comment]
I'm also finding this problem with other libraries, will it be a problem of https://jcenter.bintray.com?

**Comment by igorsilva20** [comment]
+1

**Comment by timborden** [comment]
+1

**Comment by Richi2293** [comment]
this is the problem for me
![image](https://user-images.githubusercontent.com/5848941/40607500-fb264912-6268-11e8-932a-488224b03e59.png)

and in fact if you go on this link returns 404 resource not found
https://jcenter.bintray.com/android/arch/lifecycle/runtime/1.0.0/runtime-1.0.0.jar

this is why I thought that the problem is with jcenter

**Comment by timborden** [comment]
There a slight difference in the URLs:
- https://jcenter.bintray.com/com/android/support/support-v4/26.1.0/support-v4-26.1.0.aar
- https://jcenter.bintray.com/com/android/support/support-v4/26.1.0/:support-v4-26.1.0.aar

**Comment by clarkkentzh** [comment]
me too

**Comment by NemanjaManot** [comment]
+1

**Comment by howg0924** [comment]
Same here

**Comment by rahmanmarija** [comment]
also

**Comment by xSmoggeRx** [comment]
What should we have to do, wait or?

**Comment by LPaeMoeye** [comment]
@ Richi2293 same problem

**Comment by machour** [comment]
There's obviously something wrong *today* with bintray.com. 
Please refrain from posting "me too" "me too". That doesn't help at all. Use reactions on the first comment.

**Comment by vdumontier** [comment]
Same problem here.

**Comment by roronoa89** [comment]
+1

**Comment by kayalukenvolatile** [comment]
Me too.

**Comment by machour** [comment]
See #414
