### ISSUE TITLE
Crashing on Android

### ISSUE THREAD

**Issue by sircEUNHO** [rebeccahughes/react-native-device-info#418]
## Summary

|             |     |
| ----------- | --- |
| Version     | 0.21.5   |
| Affected OS | Android   |
| OS Version  | ?   |

## Current behavior

The app is crashing after linking the library.  Here are some screenshots of my code

`settings.gradle`
![image](https://user-images.githubusercontent.com/30286632/40794419-ac14e2ea-6531-11e8-90b5-8ddedbfeb9b7.png)

`android/build.gradle`
![image](https://user-images.githubusercontent.com/30286632/40794467-d8587196-6531-11e8-939b-19aadf2e0a52.png)

`android/app/build.gradle`
![image](https://user-images.githubusercontent.com/30286632/40794548-1f12b114-6532-11e8-928d-7251d00e2399.png)
![image](https://user-images.githubusercontent.com/30286632/40794570-2b8e0236-6532-11e8-9363-d82e336f1611.png)

## Expected behavior

To work without any errors.

**Comment by machour** [comment]
Please provide the actual crash/error message

**Comment by playerfine** [comment]
+ 1
App Crashes on launch with no crash/error message

**Comment by sircEUNHO** [comment]
@machour Yeah App Crashes with no crash / error, doesnt have any error shown on react-native log-android

**Comment by machour** [comment]
Could you set up a public repo reproducing the error?

**Comment by sircEUNHO** [comment]
i'll try to make a new public repo with my current libraries, i'll send it later man

**Comment by sircEUNHO** [comment]
@machour try this one [https://github.com/sircEUNHO/ForTesting](url)

**Comment by bastolaxantos** [comment]
I added this library and got this error on launching the app. It works fine if i remove the react-native-fcm library, but whenever  i add both the app crashes. Here is the log of crash  :-

06-04 12:26:06.949 5578-5578/com.yudhaapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.yudhaapp, PID: 5578
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzbq;
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5153)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688)
        at android.app.ActivityThread.-wrap1(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzbq" on path: DexPathList[[zip file "/data/app/com.yudhaapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.yudhaapp-1/lib/x86, /data/app/com.yudhaapp-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:5153) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688) 
        at android.app.ActivityThread.-wrap1(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
    	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.common.internal.zzbq
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 13 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by bastolaxantos** [comment]
@sircEUNHO  Could be. Firebase and this library are not getting along.

**Comment by sircEUNHO** [comment]
I tried to remove my react-native-firebase but still the app is crashing without any errors showing, may i aks how you come up with the stack trace @bastolaxantos ?

**Comment by bastolaxantos** [comment]
@sircEUNHO I opened the project on Android Studio and run from it.

**Comment by diteshcrypto** [comment]
Adding the following line to the android build.gradle file 

configurations.all {
            resolutionStrategy.eachDependency { DependencyResolveDetails details ->
                def requested = details.requested
                if (requested.group == 'com.google.android.gms') {
                    details.useVersion '12.0.1'
                }
                if (requested.group == 'com.google.firebase') {
                    details.useVersion '12.0.1'
                }
            }
        }

and making the following change in the build.gradle file for react-native-device-info 

dependencies {
    compile 'com.facebook.react:react-native:+'
    compile 'com.google.android.gms:play-services-gcm:12.0.1'
}

solved it for us.

**Comment by diteshcrypto** [comment]
Adding the following line to the android build.gradle file

`configurations.all {
            resolutionStrategy.eachDependency { DependencyResolveDetails details ->
                def requested = details.requested
                if (requested.group == 'com.google.android.gms') {
                    details.useVersion '12.0.1'
                }
                if (requested.group == 'com.google.firebase') {
                    details.useVersion '12.0.1'
                }
            }
        }`

and making the following change in the build.gradle file for react-native-device-info

`dependencies {
    compile 'com.facebook.react:react-native:+'
    compile 'com.google.android.gms:play-services-gcm:12.0.1'
}`
solved it for us.

**Comment by sircEUNHO** [comment]
@diteshcrypto thanks i'll put the first line of codes on android/build.gradle right? while the second one is in android/app/build.gradle?

**Comment by sircEUNHO** [comment]
@diteshcrypto this doesn't work on my case. I'ts still crashing.

**Comment by bastolaxantos** [comment]
@sircEUNHO If you still facing crash problem then follow these steps. It worked in my case:

1. Open the project on Android Studio
2. On app level build.gradle file use same version on all firebase and gms dependencies.
  dependencies {
    compile project(':react-native-device-info')
    compile project(':react-native-fcm')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"
    compile 'com.google.firebase:firebase-core:10.0.1'
    compile 'com.google.firebase:firebase-messaging:10.0.1'
}
3. Open build.gradle file of react-native-device-info module
4. Put the same version of dependency on play-services-gcm
   dependencies {
    def googlePlayServicesVersion = project.hasProperty('googlePlayServicesVersion') ? 
 project.googlePlayServicesVersion : DEFAULT_GOOGLE_PLAY_SERVICES_VERSION

    compile 'com.facebook.react:react-native:+'
    compile "com.google.android.gms:play-services-gcm:10.0.1"
}
5. Open build.gradle of firebase module you installed. In my case it is react-native-fcm
6. Repeat the same process (use same version for all firebase dependencies)
dependencies {
    def googlePlayServicesVersion = project.hasProperty('googlePlayServicesVersion') ? project.googlePlayServicesVersion : DEFAULT_GOOGLE_PLAY_SERVICES_VERSION

    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.facebook.react:react-native:+'
    compile "com.google.firebase:firebase-core:10.0.1"
    compile "com.google.firebase:firebase-messaging:10.0.1"
    compile 'me.leolin:ShortcutBadger:1.1.17@aar'
}
7. Sync the gradle file and build the project

**Comment by sircEUNHO** [comment]
@bastolaxantos getting the stack trace on android studios and finding solutions for it fixed this for me. It had a conflict with my react-native-background-geolocation but its fixed now thanks for all the answes.

**Comment by anishroff** [comment]
@sircEUNHO What was the solution ? Can you post it here ? I am also stuck in the same situation and can get help.

**Comment by j-ornelas** [comment]
I had this issue and was able to fix by changing:

`def DEFAULT_GOOGLE_PLAY_SERVICES_VERSION = "+"`
to 
`def DEFAULT_GOOGLE_PLAY_SERVICES_VERSION = "<YOUR APPS VERSION>"

in node_modules/react-native-device-info/android/build.gradle

to the version my app was currently using. 

I was able to find the version my app was using in my app-level build.gradle.

`compile 'com.google.android.gms:play-services-gcm:<THE VERSION YOU'RE USING>'

**Comment by mikehardy** [comment]
@j-ornelas - that is a brittle way to change it, and no module should merge a change like that. If you look at the line referencing the google play version:

https://github.com/react-native-community/react-native-device-info/blob/master/android/build.gradle#L28

You'll see it is checking first: `project.hasProperty('googlePlayServicesVersion') ?` and using the project version if it exists.

So the correct fix is to take your app and put a real version in - like the example: https://github.com/react-native-community/react-native-device-info/blob/master/example/android/build.gradle#L4

You will be much happier with that (and with pinning all your versions in your application) in the long-run. This style is relatively new (maybe a year? maybe less?) but almost everyone has adopted it because it makes so much sense for future-proofing against these version mismatches

Hope this helps

**Comment by babarbahadur** [comment]
I was also having the same issue and i simply commented these 3 lines in node_modules/react-native-device-info/android/build.gradle.. It works for me!!!

if(firebaseIidVersion){
        // implementation "com.google.firebase:firebase-iid:$firebaseIidVersion"
    }else{
        // def iidVersion = safeExtGet('googlePlayServicesIidVersion', safeExtGet('googlePlayServicesVersion', '17.0.0'))
        // implementation "com.google.android.gms:play-services-iid:$iidVersion"
    }

**Comment by mikehardy** [comment]
@babarbahadur alternatively, did you attempt to define a googlePlayServicesVersion or googlePlayServicesIidVersion that was compatible with your build? Sounds like you have either old versions or incompatible versions. Google is moving lots of it's play services stuff to firebase, so the statement "I wasn't using firebase" may not mean much now or in the future as it might need this on the end ", but I was using functionality they implement in some of the firebase libraries"

**Comment by babarbahadur** [comment]
@mikehardy yeah i tried all of the above solution but non of them worked. I tried 'force' as well and also defined my googlePlayServicesVersion but it wasn't working. My current googlePlayServicesVersion is 17.0.0, react-native: 0.61.5
