### ISSUE TITLE
Some functions return '123'

### ISSUE THREAD

**Issue by joshdhenry** [rebeccahughes/react-native-device-info#419]
## Summary

|             |     |
| ----------- | --- |
| Version     | 0.21.5   |
| Affected OS | iOS   |
| OS Version  | 11.2   |

## Current behavior

I'm running getModel() and getBrand() functions. On multiple physical devices and in simulator, I only ever get '123' as the returned value. Other functions such as isTablet are returning the expected value, not returning '123'.

I've tried older versions of the library, manually linking, and using Cocoapods, but still I get this error.

## Expected behavior

I should be getting correct return values for functions instead of '123'.

**Comment by machour** [comment]
Hi! Well, this one is really weird. Could you set up a public repo reproducing the problem?

**Comment by machour** [comment]
No feedback provided.

**Comment by joshdhenry** [comment]
Found out what this was.  It was a problem in my local code and unrelated to this package.
