### ISSUE TITLE
support-media-compat-26.1.0.jar 这个文件在jcenter 仓库找不到了求指点 差文件报错

### ISSUE THREAD

**Issue by 15926332620** [rebeccahughes/react-native-device-info#421]
https://jcenter.bintray.com/com/android/support/support-media-compat/26.1.0/support-media-compat-26.1.0.jar  这个资源找不到了怎么办  用的版本0.10.2

**Comment by Mscynol** [comment]
me too  im crazy

**Comment by machour** [comment]
Hi, could you re open this issue in English? You'll probably get more support that way.
