### ISSUE TITLE
Automatic date & time / Automatic time zone flag values

### ISSUE THREAD

**Issue by VaishaliHawaldar** [rebeccahughes/react-native-device-info#422]
## Summary

|             |     |
| ----------- | --- |
| Version     | ?   |
| Affected OS | ?   |
| OS Version  | ?   |

**Comment by machour** [comment]
Please fill in a new issue with the requested information in the template

**Comment by VaishaliHawaldar** [comment]
@machour  i have opened a new issue 423, can you please have a look and let us know it is possible or not, as it is urgently needed for our requirement.
