### ISSUE TITLE
Deprecated accessing locale directly on Android

### ISSUE THREAD

**Issue by ghsdh3409** [rebeccahughes/react-native-device-info#425]
## Summary

|             |     |
| ----------- | --- |
| Version     | 0.21.5   |
| Affected OS | Android   |
| OS Version  | 7.0 (API 24)   |

## Current behavior

* `getDeviceCountry` and `getDeviceLocale` are implemented by accessing `locale` directly on Android.
* By the way, accessing `locale` directly is deprecated in API 24.
  * https://developer.android.com/reference/android/content/res/Configuration#locale
* Currently, I checked that deprecated one works even if API level 24.

## Expected behavior
* Android official document recommends using `getLocales().get(0)` to get primary locale.

**Comment by machour** [comment]
Released in 0.22.1, thank you so much @ghsdh3409 & @ohtangza
