### ISSUE TITLE
when i run it on the Android ,It have a problem like it Could not find support-media-compat.jar (com.android.support:support-media-compat:26.1.0).

### ISSUE THREAD

**Issue by Mscynol** [rebeccahughes/react-native-device-info#428]
## Current behavior
![1](https://user-images.githubusercontent.com/13941582/41019913-602434ce-6993-11e8-97fc-70636e255063.png)

## Expected behavior
it will be OK!

|             |     |
| ----------- | --- |
| Version     | 0.21.5   |
| Affected OS | Android  |
| OS Version  |   7.0 |

**Comment by Mscynol** [comment]
I have try it many times ,but never done,i'm crazy

**Comment by trungnb** [comment]
in your project / build.gradle add maven google above of jcenter then compile again
```
allprojects {
    repositories {
        mavenLocal()
        maven { url "https://maven.google.com" } <-- MOVE HERE
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```

**Comment by Mscynol** [comment]
yeah,perfect!

**Comment by rameez-dynamo** [comment]
I am still facing this. Does anyone have a solution to this?

**Comment by machour** [comment]
Please open a new issue.
