### ISSUE TITLE
Execution failed for task ':react-native-device-info:verifyReleaseResources'

### ISSUE THREAD

**Issue by whiteMu** [rebeccahughes/react-native-device-info#434]
## Summary

|             |     |
| ----------- | --- |
| Version     | 0.21.5  |
| Affected OS | Android   |
| OS Version  | 6.0   |

## Current behavior

I run the ./gradlew assembleRelease
Execution failed for task ':react-native-device-info:verifyReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
## Expected behavior
sorry ,my english is poor.

**Comment by machour** [comment]
Hi @whiteMu, can you put some more logs so that we can see what problem leads to this error?

**Comment by jovanxua** [comment]
Same here. Got similar error as below:

* What went wrong:
Execution failed for task ':react-native-device-info:prepareComGoogleAndroidGmsPlayServicesBasement1104Library'.
> Could not expand ZIP 'C:\Users\aux_j\AppData\Local\Android\Sdk\extras\google\m2repository\com\google\android\gms\play-services-basement\11.0.4\play-services-basement-11.0.4.aar'

**Comment by kashlo** [comment]
Same

* What went wrong:
Execution failed for task ':react-native-device-info:verifyReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by realtebo** [comment]
Same problem here

* What went wrong:

Execution failed for task ':react-native-device-info:incrementalReleaseJavaCompilationSafeguard'.
> java.io.IOException: Could not delete path '[cut]\node_modules\react-native-device-info\android\build\intermediates\classes\release\com\google\android'.

* Current RN-device-info version 
"react-native-device-info": "^0.21.5",

I'm on windows 10 professionale, with node 8.10.0

**Comment by opp100** [comment]
It is happening in RN 0.56, and it seems like the `com.android.support:appcompat-v7:26.1.0` has been used and it is incompatible with current react-native-device-info.

**Comment by AWDGroup** [comment]
I have the same issue

:react-native-device-info:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-device-info:verifyReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by opp100** [comment]
Hey guys, 
I found solution here: https://github.com/facebook/react-native/issues/19239#issuecomment-389939749.
Now the RN 0.56 + Gradle 3.0 is working for me.

**Comment by ArthurLDS** [comment]
I Had the same issue and  the @opp100 solucion worked for me

I just add this code in my  #andoid/build.gradle

`subprojects {
  project.configurations.all {
      afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 26
                buildToolsVersion '26.0.2'
            }
        }
    }
  }
}`

**Comment by whiteMu** [comment]
@opp100 thanks，is work for me. and thanks all

**Comment by alacret** [comment]
Still a big problem for me :'( 

https://github.com/rebeccahughes/react-native-device-info/issues/365#issuecomment-425609406

**Comment by alacret** [comment]
Solved like this:

https://github.com/rebeccahughes/react-native-device-info/issues/365#issuecomment-425609406

**Comment by mycoberago** [comment]
matching my compiledSdkVersion and buildToolsVersion in the respective node_module worked for me.  For example, in my project, my compiledSdkVersion is at 28 and buildToolsVersion is at 28.0.3.  I went to the react-native-device-info node module and modified the compiledSdkVersion and buildToolsVersion to match what I have.  I did it for each of the modules that threw the "verifyReleaseResources" error and it worked and was able to assembleRelease.

Hope it helps.

**Comment by mikehardy** [comment]
@mycoberago editing the module files directly is not what you want - what you want is to upgrade to the latest module here (1.4.1 at this point) and do something like this in your top-level build.gradle to pin the versions https://github.com/react-native-community/react-native-device-info/blob/master/example/android/build.gradle#L4

**Comment by mycoberago** [comment]
@mikehardy Thank you so much for the reply and for the "best practice" approach.  I was getting desperate and tried everything I could from people's suggestions and I lack knowledge when it comes to the Android codebase.  I will use this approach in my next release and get back to everyone if I run into any problem.  Thanks again!

**Comment by mikehardy** [comment]
Hope it helps - this style is relatively new in the react-native+android world (maybe a year?) but the dependency problem it solves is extraordinarily frustrating yes. So much so that pretty much *every* module immediately implemented the same "safeExtGet(library-name, fallback-version)" code once someone came up with it, so now app authors can pin the versions and save their hair. Cheers
