### ISSUE TITLE
Failed resolution of: Lcom/google/android/gms/common/util/zzu

### ISSUE THREAD

**Issue by Waltari10** [rebeccahughes/react-native-device-info#438]
Hey, we have had this package for a while in our application, but now all of a sudden it has started to give us an error. The error looks like this:

![screenshot_20180618-154508](https://user-images.githubusercontent.com/8919286/41536615-d50c51a2-730e-11e8-89a5-a2f0da3c60af.png)

What could be the cause? iOS seems to work fine.

**Version:** 0.21.5
**Affected OS:** Android
**OS Version:** 6.0 and 7.0

**Comment by machour** [comment]
Check the troubleshooting section at the bottom of the README

**Comment by jnranawedo** [comment]
Hi. i am facing the exact same issue & happen to use this library as well. Tried the solution in the troubleshooting section. Its not working either. 

![image](https://user-images.githubusercontent.com/31758038/42122986-cc6d5368-7c67-11e8-82fc-83b1f1737f7f.png)

**Comment by machour** [comment]
Don't comment on closed issues, you won't get help that way :)
