### ISSUE TITLE
Year Class Implementation

### ISSUE THREAD

**Issue by ssomnoremac** [rebeccahughes/react-native-device-info#44]
Was going to start another module but wanted to see there's interest in adding Facebook's Android [year-class](https://github.com/facebook/device-year-class) to this module.

**Comment by machour** [comment]
Hi @ssomnoremac did you ever make that module?
Also, year-class doesn't seem like it received much attention lately, not sure about integrating it:
  https://github.com/facebook/device-year-class/issues/35

**Comment by ssomnoremac** [comment]
Yeah, I don't think it's worth it. I won't be needing it myself anymore.

**Comment by machour** [comment]
Thank you for your quick feedback. Closing this.
