### ISSUE TITLE
Returns Unknown

### ISSUE THREAD

**Issue by SirPhemmiey** [rebeccahughes/react-native-device-info#444]
Hi,
`getDeviceId`() returns `unknown`

"react-native": "^0.55.4",
react-native-device-info": "^0.21.5",

**Comment by machour** [comment]
Hi

On what device are you testing?

**Comment by vanlight** [comment]
me too, emulator: Pixel_XL_API_25(AVD) - 7.1.1. When i get name, it return unknown

**Comment by machour** [comment]
Did you grant the android.permission.BLUETOOTH permission as stated in the README file?

**Comment by MarcBrout** [comment]
android.permission.BLUETOOTH is not specified for getDeviceId(), but for getDeviceName()

**Comment by kostyaVyrodov** [comment]
Same for me. I use ```react-native: 0.55.2``` and MODAT-532 as a device for development.

**Comment by lyseiha** [comment]
+1

**Comment by mxhryvo** [comment]
same for me.
using react-native: 0.55.4 and react-native-device-info 0.24.3

**Comment by MinaFSedrak** [comment]
Any update !!!

**Comment by mikehardy** [comment]
I can't reproduce this on any of my devices. Make a clean app (`react-native init ...`), integrate this module, and try it and post full details of devices and what the actual device name should be (by checking your sharing / hotspot settings on the device) if it is still failing

**Comment by machour** [comment]
Closing this as OP didn't report back.

Please open a new issue if you still encounter this problem.
