### ISSUE TITLE
java.lang.NoClassDefFouindError : Failed resolution of: Lcom/google/android/gms/common/util/zzu

### ISSUE THREAD

**Issue by jnranawedo** [rebeccahughes/react-native-device-info#445]
Have been using this package since December'17 and it was working perfect till now. 
Now suddenly facing this issue. It has something to do with Google Play service i guess. Not able to resolve this. 

![image](https://user-images.githubusercontent.com/31758038/42123978-dbe9ba6e-7c78-11e8-9785-9b5a9f7685c5.png)

Tried the solution given in the troubleshooting section (implemented below in build.gradle) of the repo. Its not working either. 
![image](https://user-images.githubusercontent.com/31758038/42124002-3aee1fc8-7c79-11e8-878f-57a1ba12e43d.png)

react-native : 0.50.3
react-native-device-info : 0.13.0
Affected OS : android 
OS version : 8.0

**Comment by prometheansacrifice** [comment]
Adding the following to build.gradle fixed the issue for me

```
        maven {
            url "https://dl.google.com/dl/android/maven2/"
        }
```

**Comment by SteFF1997** [comment]
it helped me but i'm not sure what is right
react-native-device-info/src/main/java/RNDeviceModule
![2018-11-02 5 04 41](https://user-images.githubusercontent.com/14296974/47923194-689d6500-dec1-11e8-82d2-094ae121ef7d.png)

**Comment by mikehardy** [comment]
@machour closable - another failure to install correctly, but the library definitely works according to instructions (I just installed it...) - this one is for dependency resolution, people need to define the ext versions in their android/build.gradle so they don't get collisions from other modules
