### ISSUE TITLE
Android: RNDeviceModule.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by realtebo** [rebeccahughes/react-native-device-info#447]
## Summary

|             |     |
| ----------- | --- |
| Version     | 0.21.5   |
| Affected OS | Android  |
| OS Version  | any  |

## Current behavior

Running `gradlew assembleRelease`  for my project, I got this, it's only an info, but I prefer to report to you

```
:react-native-device-info:compileReleaseJavaWithJavac
Note: [cut] \node_modules\react-native-device-info\android\src\main\java\com\learnium\RNDeviceInfo\RNDeviceModule.java 
        uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

## Expected behavior

No warning about use of deprecated API

## PS

Thank your for developing and mantaining this project.

**Comment by ismavg55** [comment]
+1

**Comment by machour** [comment]
Thank you so much for opening this issue @realtebo, this problem is already logged in #325, so I'm closing this bug report.

Cheers!
