### ISSUE TITLE
Failed resolution of: Lcom/google/android/gms/common/util/zzv

### ISSUE THREAD

**Issue by InteliCare** [rebeccahughes/react-native-device-info#448]
## Summary

|             |     |
| ----------- | --- |
| Version     | 0.21.5   |
| Affected OS | Android   |
| OS Version  | 7   |

## Current behavior

After app compiles it fails to load the app on the device with the error.
![screenshot_20180711-162219](https://user-images.githubusercontent.com/40415206/42559599-2b2324c4-8527-11e8-8faf-ef3c0d1be17b.png)

## Expected behavior

It should load the app

**Comment by machour** [comment]
Hi, please check the troubleshooting section and the readme and the many closed bug reports about this issue.

**Comment by InteliCare** [comment]
I have tried the fix in the read me as well as the fix from [issue](https://github.com/rebeccahughes/react-native-device-info/issues/445). That issue may seem the same but the errors are different. The issue still remains.

**Comment by InteliCare** [comment]
[android/build.gradle](https://github.com/rebeccahughes/react-native-device-info/files/2184000/build.gradle.txt)

[android/app/build.gradle](https://github.com/rebeccahughes/react-native-device-info/files/2184002/build.gradle.txt)

**Comment by InteliCare** [comment]
This issue was not due to device info. Managed to get past it

**Comment by MattyK14** [comment]
@InteliCare what was your resolution?
