### ISSUE TITLE
WifiService: Neither user 10054 nor current process has android.permission.ACCESS_WIFI_STATE

### ISSUE THREAD

**Issue by MatheusLima7** [rebeccahughes/react-native-device-info#449]
## Summary
|             |     |
| ----------- | --- |
| Version     |  v0.21.1  |
| Affected OS | Android   |
| OS Version  | 5.1  |

## Error

![image](https://user-images.githubusercontent.com/15960654/42582643-1592e2b4-8506-11e8-85d2-e9f874e915b0.png)

Can someone help me?

**Comment by namanyayg** [comment]
I have the same error. I'm trying to use:

```
DeviceInfo.getIPAddress()
      .then(ip => {})
```

**Comment by machour** [comment]
Hi, as mentioned in the documentation, you should request the ACCESS_WIFI_STATE to be able to use getIpAddress or getMacAddress: https://github.com/rebeccahughes/react-native-device-info#getipaddress

**Comment by qayyummdnoor** [comment]
why do you close this, the link you gave is just to put permission at android manifest. i did it and still show up the same error. 
`DeviceInfo.getIPAddress()
      .then(ip => {})`

**Comment by machour** [comment]
Hi @qayyummdnoor, I'm closing this issue because the initial reporter clearly didn't add the required permission to his Manifest, see the screenshot.

Feel free to open your own issue describing your problem, along with the error log.
