### ISSUE TITLE
Android getDeviceInfo() returning undefined

### ISSUE THREAD

**Issue by ssomnoremac** [rebeccahughes/react-native-device-info#45]
noticing this one method is broken. Reviewed the code and it looks like it might be related to #14. @Bhullnatik , any chance you can confirm that this?

**Comment by Bhullnatik** [comment]
What method are you talking about? `getDeviceInfo()` doesn't exist in this module.

**Comment by peteclark3** [comment]
I believe he's referring to getDeviceId().  We've confirmed it as well.

**Comment by machour** [comment]
Is this still happening with the latest version?

**Comment by machour** [comment]
Closing this old issue, please open a new one if this still happens.
