### ISSUE TITLE
RCTFatal + 400 on iOS

### ISSUE THREAD

**Issue by ntphong1990** [rebeccahughes/react-native-device-info#450]
I got this error log from my last release app.

<img width="1036" alt="screen shot 2018-07-13 at 09 20 40" src="https://user-images.githubusercontent.com/14165753/42669315-e6f7474a-867e-11e8-8547-45cf6ef0a6f1.png">
<img width="838" alt="screen shot 2018-07-13 at 09 21 06" src="https://user-images.githubusercontent.com/14165753/42669322-ebbe26b8-867e-11e8-9153-d848e0f00410.png">

Version : 0.21.5
Affected OS : iOS
OS Version  | ?   |

## Current behavior
Open app and it  immediately crash. Next open is ok (not crash). Sometime it's happen

**Comment by machour** [comment]
Hey @ntphong1990, #442 may just be the fix you need, as tested in #455.

If you have the time, could you confirm that the PR fixes this for you too?

**Comment by machour** [comment]
No feedback provided.

**Comment by judemanutd** [comment]
Same issue here using 
```
    "react": "^16.5.0",
    "react-native": "0.55.4",
```

**Comment by ckOfor** [comment]
:( any solution

**Comment by ckOfor** [comment]
?

**Comment by mikehardy** [comment]
@ckOfor this issue has been closed nearly a year, please log a new issue with as much info as you can provide (versions etc)
