### ISSUE TITLE
MobSF issue (com.learnium.RNDeviceInfo.RNDeviceReceiver) is not Protected.

### ISSUE THREAD

**Issue by ButuzGOL** [rebeccahughes/react-native-device-info#452]
Did some check of my apk in MobSF
and got
(com.learnium.RNDeviceInfo.RNDeviceReceiver) is not Protected. [android:exported=true]

A Broadcast Receiver is found to be shared with other apps on the device therefore leaving it accessible to any other application on the device.
<img width="956" alt="screen shot 2018-07-19 at 5 10 14 pm" src="https://user-images.githubusercontent.com/196564/42948919-39b4ee7a-8b79-11e8-91d3-b56c63740629.png">

**Comment by machour** [comment]
@ButuzGOL Thank you for this report. Any clues on how to fix that? I'll gladly accept a PR.

**Comment by ButuzGOL** [comment]
as i understand they suggest to change 
android:exported="true" to false
will it break something ?

**Comment by machour** [comment]
No feedback provided.

**Comment by isaaclem** [comment]
> We are using that Broadcast Receiver to listen to com.android.vending.INSTALL_REFERRER to be able to read it in getInstallReferer. So this needs to stay exported, according to the documentation.
> I'd say it's a false-positive from MobSF.

Hi @machour : I'm trying to locate method of `getInstallReferer`, wondering if it's still available? If it's not, can I simply update `android:exported` to false?

**Comment by mikehardy** [comment]
Sure - you can probably do a manifest merge or similar to override it via your app AndroidManifest.xml, or use patch-package if needed

**Comment by sorokinpf** [comment]
Possible solution is to add `android.permission.INSTALL_PACKAGES` permission on `receiver` element of AndroidManifest. This restricts receiver from processing Intents from any application.

Example: https://developers.google.com/android/reference/com/google/android/gms/tagmanager/InstallReferrerReceiver?hl=ru
