### ISSUE TITLE
getMACAddress return "02:00:00:00:00:00" ANDROID

### ISSUE THREAD

**Issue by qayyummdnoor** [rebeccahughes/react-native-device-info#458]
## Summary

|             |     |
| ----------- | --- |
| Version     | 0.22.1  |
| Affected OS | Android   |
| OS Version  | 6.0.1 Android   |

## Current behavior

getMACAddress return "02:00:00:00:00:00" ANDROID 
my code : 

> componentWillMount()
 {  
    this.setState({ mac: false });
    DeviceInfo.getMACAddress().then(mac => this.setState({ mac }));
  }

> render()
{
const { mac } = this.state;
    return (
      `<View style={styles.container}>
<Text>IP: {mac}</Text>
      </View>`
    );
  }

## Expected behavior

Supposed show current MAC address. 
Please Help!! Thanks in advance!!

**Comment by machour** [comment]
Hi, did you add the permissions in your manifest as mentioned in the documentation?

**Comment by machour** [comment]
Could you try with android.permission.INTERNET ?

**Comment by qayyummdnoor** [comment]
I had tried with android.permission.INTERNET. Still return 02:00:00:00:00:00

**Comment by machour** [comment]
https://developer.android.com/about/versions/marshmallow/android-6.0-changes#behavior-hardware-id

**Comment by AnasEspl** [comment]
what is solution of throw bydefault 02:00:00:00:00:00
