### ISSUE TITLE
undefined is not an object (evaluating 'RNDeviceInfo.uniqueId')

### ISSUE THREAD

**Issue by gyurobenjamin** [rebeccahughes/react-native-device-info#462]
## Summary

|             |     |
| ----------- | --- |
| Version     | 0.22.2   |
| Affected OS | iOS / Android  |
| OS Version  | iOS 11, Android Oreo  |

## Current behavior

If I call any of the methods, I got an error message:
```undefined is not an object (evaluating 'RNDeviceInfo.uniqueId')```

## Expected behavior

Not get an error message, but see the results from the methods as in the documentation.

**Comment by x0fma** [comment]
Hey, have you linked the library ? Was having the same problem as you yesterday and I had just read too fast the Readme file :p

**Comment by gyurobenjamin** [comment]
@x0fma yes I tried to link it with the react-native link ... I'm thinking it's might be a cache problem or something similar. I'm using expo.

**Comment by gyurobenjamin** [comment]
I'm trying in simulator without build, and I haven't detached it yet.

**Comment by x0fma** [comment]
You must detach your expo so you can link to packages that use native code.
See that thread, https://github.com/expo/expo/issues/56, hope it helps ^^

**Comment by dihan** [comment]
My issue was that linking didnt work so did it manually 

https://github.com/rebeccahughes/react-native-device-info#linking

**Comment by ropy** [comment]
Importing instead of requiring worked for me.

```
~~let DeviceInfo = require('react-native-device-info');~~
import DeviceInfo from 'react-native-device-info';
```

**Comment by mmccartney** [comment]
Is this Android or iOS or both?  If it's only on Android, maybe this is your fix?  
https://github.com/rebeccahughes/react-native-device-info/issues/488#issuecomment-432372215

**Comment by dineshlt** [comment]
I am getting this same issue **undefined is not an object (evaluating 'RNDeviceInfo.uniqueId')**. its working fine in android and successfully getting unique id. But in IOS only am getting this error.

Kindly give need full suggestion

**Comment by Dezainer** [comment]
After you guys installed it and executed the `react-native link`, try to rebuild the app so it applies the native code changes, it may work.

**Comment by vin7974** [comment]
Its something wrong with your GoogleInfo.plist, make sure your budleID is same with googleplist file. Open Xcode project and check bundleID and check package.json also have the same bundle ID

**Comment by nikhilboranaarit** [comment]
![screenshot 2019-01-18 at 6 33 48 pm](https://user-images.githubusercontent.com/39380554/51388608-04994d00-1b50-11e9-94c2-092a4e139f2b.png)
in IOS.

**Comment by mikehardy** [comment]
@machour this should be closed, the app installs and links correctly - these errors are always linking issues and the affected users should try a clean react-native init sample app to see how things are supposed to look

**Comment by ajjubbal** [comment]
I had to run `pod install` within the `ios` folder in my project to resolve this.

**Comment by mikehardy** [comment]
If using pods, pod install (and or pod update occasionally, but being careful of what dependencies are okay to upgrade) should become reflexive. You have to do it as part of any CI, and as part of a normal build process just like npm i or yarn install

**Comment by ajjubbal** [comment]
Sure, but when I build my project I run `npm run install:pods` but was seeing this issue in spite of that. Hence my comment to actually run `pod install` "manually" within the `ios` folder.

**Comment by mikehardy** [comment]
Anything in an npm `run` script is custom, fully defined by the project. No one else will share that command - I'd always assume I need to `cd ios && pod install`

**Comment by ajjubbal** [comment]
Good to know, thanks for sharing.

**Comment by JakinTayo** [comment]
I am still getting this error in android. I have done everything suggested.
