### ISSUE TITLE
Device info is not working in simulator

### ISSUE THREAD

**Issue by manju-ms** [rebeccahughes/react-native-device-info#470]
## Summary
| Version     | 0.17.4   |
| Affected OS | Android And Ios   |
| OS Version  | Android 5 and above, ios 10 and above |

## Current behavior
Device info is not working in simulator and it is working in real device.

## Expected behavior

It must work both in simulator and device.

**Comment by machour** [comment]
Hi, could you give a little more information? "Is not working" doesn't really say anything..

**Comment by manju-ms** [comment]
It will give the error undefined is not a object for DeviceInfo.

For Example in my component i am using the below code
var DeviceInfo = require('react-native-device-info');
DeviceInfo.getUniqueID() will give undefined is not an object.

**Comment by robertkeizer** [comment]
<img width="258" alt="screen shot 2018-08-08 at 10 59 50" src="https://user-images.githubusercontent.com/339303/43849105-3d5377dc-9afa-11e8-8911-75d75c2a7639.png">

Similar thing happening. 

```
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.11.3
  Yarn: 1.9.2
  npm: 6.3.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.1 => 0.55.1
```

**Comment by manju-ms** [comment]
After updating to 0.22.2 it is working fine. Thank you @machour.

**Comment by SM-Wistful** [comment]
This is still an issue! I installed the latest version and it did not work on the simulator with the same error described above. I then attempted to revert to @0.22.2 and it still did not work.

**Comment by jbrumwell** [comment]
Having similar issue as well in an emulator, `TypeError: Cannot read property 'uniqueId' of undefined at Object.getUniqueID`

**Comment by ventr1x** [comment]
Same issue here on ios simulator

**Comment by degamer106** [comment]
Still seeing the same issue in 2019!  Using the latest version on iOS simulator running OS 12.1.

**Comment by Senocico** [comment]
The same issue... 😒

**Comment by AishwaryaSurana** [comment]
Anybody able to resolve it?

**Comment by machour** [comment]
Could you open a new issue describing your exact setup and problem?
I'm afraid commenting on a closed issue won't really help

**Comment by deckyfx** [comment]
Still crash in 10.12.0 in Android Emulator
Weirdly, it works in 8.1.3
