### ISSUE TITLE
uses or overrides a deprecated API. Recompile with -Xlint:deprecation for details.

### ISSUE THREAD

**Issue by mrkhanakia** [rebeccahughes/react-native-device-info#472]
I am getting error during Gradle build

/Volumes/D/www/js/uc_js/uc_reactnative/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java:
uses or overrides a deprecated API.
Recompile with -Xlint:deprecation for details.

**Comment by machour** [comment]
Duplicate of #325
