### ISSUE TITLE
Possible unhandled promise rejection (id:0): TypeError: undefined is not an object

### ISSUE THREAD

**Issue by xiechuanyu** [rebeccahughes/react-native-device-info#475]
## Summary

|             |     |
| ----------- | --- |
| Version     | ^0.22.3 |
| Affected OS | Android   |
| OS Version  | 7.0.0  |

## Current behavior
when i use ``const deviceId = DeviceInfo.getDeviceId();'``,it shows me the following messages :
 
**``Possible unhandled promise rejection (id:0): TypeError: undefined is not an object``**
![_20180810100838](https://user-images.githubusercontent.com/12131262/43935319-f04f4528-9c85-11e8-9206-3fff53b70614.jpg)

**Comment by machour** [comment]
Is the problem present in 0.22.2 ?

**Comment by greyexpert** [comment]
Looks like the reason of this issue is in this commit:
https://github.com/rebeccahughes/react-native-device-info/commit/0a2c91fcaad32f9c7e748776975f47445441b3c4

It is not safe to replace
```
module.exports = {};
```
with 
```
export default {};
```

since it breaks backward compatibility

**Comment by greyexpert** [comment]
To fix the issue, I had to replace this:
```js
import { getUniqueID } from 'react-native-device-info';

const id = getUniqueID();
```
with this:
```js
import DeviceInfo from 'react-native-device-info';

const id = DeviceInfo.getUniqueID();
```

**Comment by echap** [comment]
Can't make it work with 0.22.5, same message.

**Comment by SM-Wistful** [comment]
Same problem on the iOS simulator #470

**Comment by xstable** [comment]
Didn't work for me... not the old way, and not the new one @greyexpert suggest.
So I do it the manual way with: 
```
import { NativeModules } from 'react-native';
const { RNDeviceInfo } = NativeModules;

const hereIsTheMagicDeviceID = RNDeviceInfo.uniqueId;
```

**Comment by MelanieJourne** [comment]
I had the same problem on Android and was able to solve it by changing MainApplication.java like this
```
  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
    return Arrays.<ReactPackage>asList(
            // eg. new VectorIconsPackage()
            new RNDeviceInfo()
    );
  }
```

```
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
              new MainReactPackage(),
              new RNI18nPackage()
      );
    }
  };
```

**Comment by fgagneten** [comment]
The solution for me was running the following command

    react-native link react-native-device-info

**Comment by sllvn** [comment]
I had the same problem with `0.24.3` and RN 0.57. Solution for me was to manually link (without Cocoapods). Neither `react-native link` or `pod install` methods worked for me.

**Comment by vishal-km** [comment]
`react-native link react-native-device-info`
This saved me

**Comment by mikehardy** [comment]
@machour closable - another failure to install correctly
