### ISSUE TITLE
compile warning: RNDeviceInfo.o was built for newer iOS version (8.0) than being linked (7.0)

### ISSUE THREAD

**Issue by npomfret** [rebeccahughes/react-native-device-info#48]
I'm seeing this warning:

`ld: warning: object file (/Users/nickpomfret/Library/Developer/Xcode/DerivedData/pomochat-cvkhcsdfxgmgokbegzcqhdxmcngh/Build/Products/Debug-iphonesimulator/libRNDeviceInfo.a(RNDeviceInfo.o)) was built for newer iOS version (8.0) than being linked (7.0)`

Would it be possible to release it linking to version 7?

**Comment by sbefort** [comment]
+1

**Comment by machour** [comment]
Closing this old issue, please open a new one if this still happens.
