### ISSUE TITLE
IOS  getIpAddress    Display under Network.  

### ISSUE THREAD

**Issue by JslinSir** [rebeccahughes/react-native-device-info#481]
it look like this 
![image](https://user-images.githubusercontent.com/30678791/44614468-c2e1d000-a857-11e8-84c6-da2c6f6f8853.png)

But  under wifi it normal  

And how  to get truIpAdress?

**Comment by machour** [comment]
It's a promise, you need to use .then()
It will always return your local IP address, this is normal. 
To get your external IP, try fetching http://whatsmyip.com or something similar
