### ISSUE TITLE
Not working on Huawei

### ISSUE THREAD

**Issue by baselbj** [rebeccahughes/react-native-device-info#485]
Hi,

Some features, at least DeviceInfo.getModel(), is not working on Huawei.

any suggestions on how to solve this issue?

**Comment by machour** [comment]
Hi, what do you mean by not working ? Can you give some sample outputs ?

**Comment by baselbj** [comment]
Thank for your replay ... I forgot this post and didn't update it with last information.

I find that  DeviceInfo.getModel() for Huawei only gets Model name in other devices it gets Brand name and model name.

I fixed the issue by creating this function:

const getDeviceModel = () => {
    let model = DeviceInfo.getModel();
    if (!model.startsWith(DeviceInfo.getBrand())) {
        model = `${DeviceInfo.getBrand()} ${model}`
    }
    return model
}

**Comment by machour** [comment]
Well, ¯\_(ツ)_/¯ 

Feel free to open a PR if you want to address this for Huawei phones, closing this issue since you found a workaround.
