### ISSUE TITLE
0.22.5 broke typescript

### ISSUE THREAD

**Issue by ethanneff** [rebeccahughes/react-native-device-info#486]
## Summary

0.22.5 broke Typescript.
https://github.com/rebeccahughes/react-native-device-info/pull/478/files

## Current behavior

```
src/containers/App/index.tsx:123:5 - error TS2554: Expected 1 arguments, but got 0.

123     DeviceInfo.isPinOrFingerprintSet()((isPinOrFingerprintSet: boolean) =>
```

## Expected behavior

Not throw an error.

**Comment by machour** [comment]
Is this still broken with last version?
I'll gladly accept a PR fixing this.

**Comment by jsochurek** [comment]
this is still broken in 0.26.2 @machour

**Comment by machour** [comment]
Any chance you could provide a PR for this?
