### ISSUE TITLE
Device info returning : undefined is not an object

### ISSUE THREAD

**Issue by nikuslas** [rebeccahughes/react-native-device-info#488]
### Summary
| Version (react-native) | 0.55.4 |
| Affected OS | Android Only |
| OS Version | Android 8.0 |

First of all, I installed react-native-navigation and react-redux.
| Version (react-native-navigation) | 1.1.484 |
| Version (react-redux) | 5.0.7 |

Afterwards, I installed react-native-device-info and followed all steps to link the lib (i did both, manually and automatically).
| Version (react-native-device-info) | 0.22.5 |

One last thing, i run the app on an emulator.

### Current behavior

I declare the module like this : 
import DeviceInfo from 'react-native-device-info';

When I call the getModel() (DeviceInfo.getModel()) function in a render i got an error : 

![capture d ecran 2018-09-04 a 17 47 41](https://user-images.githubusercontent.com/15159803/45042659-81c59900-b06b-11e8-8548-1e1bf9b5c382.png)

Thank you!

**Comment by to175** [comment]
Please send your code.

**Comment by Ahmednagyyy** [comment]
@to175 send eh w arf eh el bata3a bayza

**Comment by alleniver** [comment]
hello,i have same issue,the follow code in ios simulator,android has well
import {getDeviceLocale} from 'react-native-device-info';
let lan = getDeviceLocale(); 

get this errors:
Unhandled JS Exception: (0, _reactNativeDeviceInfo.getDeviceLocale) is not a function. (In '(0, _reactNativeDeviceInfo.getDeviceLocale)()', '(0, _reactNativeDeviceInfo.getDeviceLocale)' is undefined)
2018-09-06 16:57:38.454 [error][tid:com.facebook.react.JavaScript] Module AppRegistry is not a registered callable module (calling runApplication)

**Comment by timt** [comment]
Experiencing the same issue using RN 0.55.3 and react-native-device-info 0.22.5

Every method on DeviceInfo throws an `undefine d is not an object` exception

**Comment by sseppola** [comment]
I'm getting the same error, but for every single call (12 total). I'm basically doing:
```
import DeviceInfo from 'react-native-device-info';

class SomeClass {
  getDeviceInfo() {
    return {
        app: {
          name: DeviceInfo.getApplicationName(),
          build: DeviceInfo.getBuildNumber(),
        },
        device: {
          name: DeviceInfo.getDeviceName(),
          manufacturer: DeviceInfo.getManufacturer(),
        },
        locale: DeviceInfo.getDeviceLocale(),
        location: {
          country: DeviceInfo.getDeviceCountry(),
        },
        network: {
          carrier: DeviceInfo.getCarrier(),
        },
        os: {
          name: DeviceInfo.getSystemName(),
          version: DeviceInfo.getSystemVersion(),
        },
        referrer: {
          name: DeviceInfo.getInstallReferrer(),
        },
        screen: {
          density: PixelRatio.get().toString(),
          height: Dimensions.get('window').height.toString(),
          width: Dimensions.get('window').width.toString(),
        },
        timezone: DeviceInfo.getTimezone(),
        userAgent: DeviceInfo.getUserAgent(),
      }
  }
}
```

I'm running it in a local development environment, but on my iPhone 8
```
$ react-native info

Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.11.3
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4907809

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ^0.55 => 0.55.4
```

**Comment by nfacha** [comment]
Same problem as described above happens here

**Comment by iceagency-lukehopkins** [comment]
Same as above

![screen shot 2018-09-14 at 16 29 16](https://user-images.githubusercontent.com/41051284/45559815-63198c00-b83b-11e8-8e2d-9ac7677f448e.png)

**Comment by nfacha** [comment]
@iceagency-lukehopkins Manual linking fixed the issue on Android too :smile:

**Comment by MelanieJourne** [comment]
I add the same error as you and was able to solve it by changing MainApplication.java as following 

```
  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
    return Arrays.<ReactPackage>asList(
            // eg. new VectorIconsPackage()
            new RNDeviceInfo()
    );
  }
```

```
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
              new MainReactPackage(),
              new RNI18nPackage()
      );
    }
  };
```

**Comment by ropy** [comment]
Importing instead of requiring worked for me.

~~let DeviceInfo = require('react-native-device-info');~~

```
import DeviceInfo from 'react-native-device-info';
```

**Comment by mmccartney** [comment]
Like @nikuslas , I am also using `react-native-navigation`.  

I had the same problem as many others (i.e. `import DeviceInfo from 'react-native-device-info'` was returning `undefined`) but after reading all these comments, I figured out what was going wrong.

If you start your project with `react-native init`, you will have a `MainApplication.java` with a `getPackages()` method that is part of the `ReactNativeHost` implementation.  If you later do step 5 of [RNN's Android instructions](https://wix.github.io/react-native-navigation/#/installation-android), you will get a **_second_** `getPackages()` method.  This second method is called by `createAdditionalReactPackages()` (which is an _abstract method_ in RNN's base class `NavigationApplication`).

When you run `react-native link react-native-device-info`, it adds `new RNDeviceInfo()` to the _first_ `getPackages()` method.  I was able to fix this `import` problem by adding `new RNDeviceInfo()` to the _second_ `getPackages()` method -- the one called from `createAdditionalReactPackages()`.

I hope this helps everyone!

**Comment by Jobeso** [comment]
I encountered the error on iOS and fixed the error by changing the import from destructured

```
import { getModel } from 'react-native-device-info'
```

to a default import

```
import DeviceInfo from 'react-native-device-info'
```

and used it with `DeviceInfo.getModel()`

**Comment by NelGarbuzova** [comment]
Same here. I solved this by replacing all 
`var DeviceInfo = require('react-native-device-info');`
with
`import DeviceInfo from 'react-native-device-info';`

**Comment by iyogeshjoshi** [comment]
I think document needs to be updated `react-native link react-native-device-info` doesn't link libraries to project, you need to manually add them here are the steps: 

* right click on `Libraries` > `Add files to <app name>`
* select `RNDeviceInfo.xcodeproj`
* select `Copy items if needed` and add
* then under `Linked frameworks and libraries` add `libRNDeviceInfo.a`

build and run, it worked for me hope will work for you too 😃

**Comment by mikehardy** [comment]
@machour closable - another failure to install correctly, but the library definitely works according to instructions (I just installed it...)

**Comment by arsomjin** [comment]
To confirm @NeliHarbuzava solution.
Solved this by replacing all
var DeviceInfo = require('react-native-device-info');
with
import DeviceInfo from 'react-native-device-info';
works for me.

**Comment by azharuddinkhan8898** [comment]
`DeviceInfo.default.getBuildNumber()` worked for me.

**Comment by MaffooBristol** [comment]
I believe my issue is related to react-native-navigation too. Perhaps something to do with the default behaviour of `NavigationApplication`

I had to add the following to my `android/app/src/main/java/com/foo/MainApplication.java` file:

```
import com.learnium.RNDeviceInfo.RNDeviceInfo;
```

```
public class MainApplication extends NavigationApplication {
    protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
           new RNFirebasePackage(), // for example
            new RNDeviceInfo()
        );
    }
}
```

@mikehardy - I understand your frustration with the sheer number of "RNDeviceInfo is null" style issues, but there's nowhere that mentioned manually adding the import and package to the MainApplication file. I did a test new project and it worked fine, and as someone mentioned above it's a clash with rnn. I wonder whether this is something that needs to be documented?

**Comment by mikehardy** [comment]
It's possible something needs to be documented, but what? If you look in this repo there are two scripts - refresh-example-rn59.sh and refresh-example.sh - both of which automagically create the example app for the repo, from scratch. If some modification to those scripts (perhaps just including react-native-navigation via yarn add or similar?) can demonstrate a failure, then a doc update would be gratefully accepted. But I've not seen a clean demo of a problem yet

**Comment by MaffooBristol** [comment]
Just adding RNN won't cause the issue, I don't believe. I think it's when the class that the MainApplication extends changes that causes the issue. I'm quite a newbie when it comes to react native so I don't know too much about it and whether the issue lies with RNN's changes to the MainApplication file or not. But if there's a troubleshooting section then perhaps it can be added?

Or hopefully people would just find my comment on this thread! But I didn't realise for a long time that it'd be due to mixing with RNN, so I wouldn't have searched for that.

If I get a spare moment I'll see if I can create a test case

**Comment by mikehardy** [comment]
I see nothing in here that would conflict https://wix.github.io/react-native-navigation/#/docs/Installing?id=_7-update-mainapplicationjava - at least not in a react-native 0.60+ world with auto-linking etc.

**Comment by MaffooBristol** [comment]
Well yeah I had assumed that autolinking would take care of it, but adding the imports seems to be the only way I could get it to finally work. Also quite a few other packages (such as firebase) seem to require adding the packages that way. My test react-native app without react-native-navigation worked fine without it. So unless I'm missing something, it seems that RNN's paradigm requires specifying those packages manually...?

Although that's  probably on RNN's shoulders, perhaps it would be good to show somewhere that you'd need to add `import com.learnium.RNDeviceInfo.RNDeviceInfo;` and `new RNDeviceInfo()` if nothing else is working. Because it took some delving into the repo to find what the full package name was.

**Comment by mikehardy** [comment]
react-native-firebase is an interesting beast. If you look carefully it does not require you to manually link *the main package*. It's all the little sub-packages you have to link. And even then only for react-native-firebase v5, not in v6. I support that repo and demo same here: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

Auto-linking should handle everything for react-native-device-info, I still assert. If react-native-navigation is perturbing that in any way, that is definitely on them

**Comment by cherucole** [comment]
This is what worked for me.
1. Do the npm install
2. Linking the installed library
3. cd ios and do pod install
4. Kill the running app and do a fresh react-native run-ios to rebuild the project. 
after that:
`import DeviceInfo from 'react-native-device-info';
`
works

**Comment by Maqsood007** [comment]
Not wroked:
`import {DeviceInfo} from 'react-native-device-info';`

Worked:
`import DeviceInfo from 'react-native-device-info';`
