### ISSUE TITLE
TypeError: Cannot read property 'deviceName' of undefined

### ISSUE THREAD

**Issue by kunalkp** [rebeccahughes/react-native-device-info#489]
Summary
| Version     | 0.22.5   |
| Affected OS | iOS   |
| OS Version  | 11.4.1  |

Current behavior
Declared the module like this :
import DeviceInfo from 'react-native-device-info';

Used 2 API
const deviceName = DeviceInfo.getDeviceName();
const uniqueID_android = DeviceInfo.getUniqueID();

Getting the following error:
TypeError: Cannot read property 'deviceName' of undefined
TypeError: Cannot read property 'uniqueID_android' of undefined

Getting the same error for every other API.

**Comment by tylerjbainbridge** [comment]
Did you find a solution for this?

**Comment by kunalkp** [comment]
Somehow automatic linking didn't worked for ios. So, I had to manually link it to pods and it worked.
