### ISSUE TITLE
build android fail because of 'compile' and 'implementation'

### ISSUE THREAD

**Issue by truongluong1314520** [rebeccahughes/react-native-device-info#497]
## Summary

I simply write `npm install react-native-device-info` and `react-native link react-native-device-info`. Everything works like a charm until I run the `react-native run-android`. I cannot build the project because of this error:

_"Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html"_

| Platform        |     |
| ----------- | --- |
| Android | Yes   |
| iOS | No   |

|                     | Version    |
| ----------- | --- |
 React Native | 0.57   |

## Current behavior

Android project cannot be built because _"Configuration 'compile' is obsolete"_

## Expected behavior

Android project can be built without changing `compile` to `implementation` in `build.gradle` file.

## Suggestion for fixing this issue

Change `compile` to `implementation` in `build.gradle` file

**Comment by recepkocur** [comment]
+1

**Comment by tapz** [comment]
"It will be removed at the end of 2018."

**Comment by machour** [comment]
Removed in 0.24.1
