### ISSUE TITLE
unnecessary requirements on play store

### ISSUE THREAD

**Issue by lucasfeliciano** [rebeccahughes/react-native-device-info#50]
If I add this module my app start to require unnecessary permissions.

I thought it was because the `BLUETOOTH` permission but even after removing it the behaviour continues.

The only things that I need permission are:
- take pictures 
- precise location

this is what i have on my manifest:

```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
```

And this are the permissions:

![screen shot 2016-06-09 at 13 44 44](https://cloud.githubusercontent.com/assets/968014/15928632/593bb1e2-2e48-11e6-918c-c68e1bee293f.png)

**Comment by huntharo** [comment]
Did you figure this out?  I suspect that it was not related to this module but rather to something else.  Is that correct?

**Comment by antoinerousseau** [comment]
I think it's related to React Native itself.

In your `AndroidManifest.xml`, try adding `xmlns:tools="http://schemas.android.com/tools"` to your root tag attributes (`<manifest>`) and then add this:

```xml
<uses-permission android:name="android.permission.READ_PHONE_STATE" tools:node="remove" />
```

**Comment by machour** [comment]
READ_PHONE_STATE is necessary to get the device phone number for example. 
Draw over other apps is required by react-native.

Closing this issue as it's quiet old, please open a new one if you still think that we're doing something wrong.
