### ISSUE TITLE
Does not support React Native Windows v0.57 

### ISSUE THREAD

**Issue by jmcginty** [rebeccahughes/react-native-device-info#505]
## React native windows has increased the minimum target version, and this causes compile time errors if associated projects are targeting a lower version. 

|             |     |
| ----------- | --- |
| Version     | 0.22.6   |
| Affected OS | Windows   |
| OS Version  | 10   |

## Current behavior

React Native Windows has changed it's minimum target version to 10.0.14393, so it will not compile.

## Expected behavior

Can compile the project and run

**Comment by kgstew** [comment]
I'm having the same issue. I was able to work around it by updating `<TargetPlatformMinVersion>10.0.10586.0</TargetPlatformMinVersion>` in `RNDeviceInfo.csproj` to 10.0.14393.

**Comment by machour** [comment]
Fixed in 0.24.3 by @jmcginty
