### ISSUE TITLE
getModel for iPhone XS

### ISSUE THREAD

**Issue by alexgomezalanis** [rebeccahughes/react-native-device-info#506]
## Summary

|             |     |
| ----------- | --- |
| Version     |  0.21.5  |
| Affected OS | iOS  |
| OS Version  | 10.12  |

## Current behavior

DeviceInfo.getModel() only returns "iPhone" when using an iPhone XS

## Expected behavior

The expected behaviour would be to return "iPhone XS"

**Comment by alexgomezalanis** [comment]
This is resolved in version 0.22.6

**Comment by TashaRolland92** [comment]
> This is resolved in version 0.22.6

Only took me a day to find this 😍and it works - not that I ever doubted 😀
