### ISSUE TITLE
react-native-device-info cannot run in android

### ISSUE THREAD

**Issue by faizulhadijamil** [rebeccahughes/react-native-device-info#508]
when I run the react-native run-android, I receive this error
<img width="566" alt="screen shot 2018-10-07 at 11 50 18 pm" src="https://user-images.githubusercontent.com/33046264/46583562-cc339e80-ca8b-11e8-8ea5-4b058c17aa6f.png">
Anyone having this problem? its only happen in android,
I use react-native version 0.52.3

**Comment by zsaraf** [comment]
I'm having the same issue.

**Comment by machour** [comment]
Hi, please follow the instructions in the error message in order to provide us with more logs about the issue.

**Comment by Flavien** [comment]
Also having the same issue since yesterday.

**Comment by mmccartney** [comment]
I've seen this related to other projects.  I'm pretty sure it's a compatibility issue with `appcompat` library.  Make sure your `supportLibVersion` matches across your entire project.  Easiest way to do this is to use the `ext` convention recommended in the **Manual > Android** section [here](https://github.com/rebeccahughes/react-native-device-info#linking).

Hope this helps!

**Comment by mikehardy** [comment]
@machour closable - another failure to install correctly, but the library definitely works according to instructions (I just installed it...) - same android/build.gradle + android/app/build.gradle version pinning issue. The whole react-native ecosystem changed style to kill these problems...
