### ISSUE TITLE
Can't install into an existing project, double installs React

### ISSUE THREAD

**Issue by tclarke-scottlogic** [rebeccahughes/react-native-device-info#515]
## Summary
Installed into an existing "ejected" project that had react-native at the node_modules level via `yarn install`

When I ran pod install, it added RNDeviceInfo, but also React.

When I then 

| Version     | 0.24   |
| Affected OS | iOS   |
| OS Version  | 12.0  |

## Current behavior
```
yarn add react-native-device-info
yarn install
react-native link react-native-device-info
cd ios && pod install & cd ..
```
It installs RNDeviceInfo, but also React as a dependency?

yarn ios

System fails with:

```
This warning is caused by a @providesModule declaration with the same name across two different files.
Loading dependency graph, done.
error: bundling failed: ambiguous resolution: module `/Users/thomasclarke/dev/mobile-notifications-native/index.js` tries to require `react-native`, but there are several files providing this module. You can delete or fix them: 

  * `/Users/thomasclarke/dev/mobile-notifications-native/ios/Pods/React/package.json`
  * `/Users/thomasclarke/dev/mobile-notifications-native/node_modules/react-native/package.json`
```

## Expected behavior
No ambiguous resolution warning

**Comment by tclarke-scottlogic** [comment]
Solution:
I didn't need to run `react-native link react-native-device-info`

**Comment by tclarke-scottlogic** [comment]
Fixed my problem thus:
https://stackoverflow.com/questions/52737251/how-do-i-prevent-react-native-device-info-causing-react-ambiguity-on-my-setup/52776146#52776146

**Comment by krionoah69** [comment]
I have the same problem, any solutions ?

**Comment by tclarke-scottlogic** [comment]
@krionoah69 
https://github.com/rebeccahughes/react-native-device-info/issues/515#issuecomment-429259774

**Comment by sanchapereira** [comment]
@tclarke-scottlogic were you really able to fix your problem? I keep getting a failed build on `Check dependencies`
