### ISSUE TITLE
Library failed to compile for Android after upgrade to react native 0.56.0

### ISSUE THREAD

**Issue by lucassus** [rebeccahughes/react-native-device-info#522]
## Summary

|             |     |
| ----------- | --- |
| Version     | 0.24.3   |
| Affected OS | Android   |
| OS Version  | osx   |

## Current behavior

After I upgraded my app to react-native 0.56.0 I'm not able to compile it for Android platform.
It worked fine before and I'm 100% sure that the library is properly linked.
My current configuration could be found here (package.json, build.gradle, MainApplication.java etc) - https://gist.github.com/lucassus/d40cd8bcca7997df1b9cf1c9871c3edb

```
[...]
:app:generateReleaseSources
:app:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:app:javaPreCompileRelease
:app:compileReleaseJavaWithJavac
:app:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/lucassus/Projects/Airsorted/housekeeping-app/android/app/src/main/java/com/airsorted/housekeeping/MainApplication.java:7: error: package com.learnium.RNDeviceInfo does not exist
import com.learnium.RNDeviceInfo.RNDeviceInfo;
                                ^
/Users/lucassus/Projects/Airsorted/housekeeping-app/android/app/src/main/java/com/airsorted/housekeeping/MainApplication.java:31: error: cannot find symbol
                new RNDeviceInfo(),
                    ^
  symbol:   class RNDeviceInfo
  location: class MainApplication
2 errors
:app:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
```

**Comment by machour** [comment]
Hi, the error message do seems to say that there's a problem with linking.
Did you dry linking again, resetting your cache, removing and reinstalling node_modules, and cast some druidic spells like that ?

**Comment by lucassus** [comment]
I've tried everything and I ran out of all my mana ;)

But it seems that change

```
implement 'com.facebook.react:react-native:+'
implement "com.google.android.gms:play-services-gcm:$googlePlayServicesVersion"
```

to

```
compile 'com.facebook.react:react-native:+'
compile "com.google.android.gms:play-services-gcm:$googlePlayServicesVersion"
```

...fixes the issue.

**Comment by machour** [comment]
Oh, sorry for the inconvenience. This was changed in 0.24.1 

You can find the motivations in this PR: https://github.com/rebeccahughes/react-native-device-info/pull/520. Shall I cast rollback ? 🤔

**Comment by lucassus** [comment]
I'm not sure how it will affect other RN versions.
For now I casted downgrade `"react-native-device-info": "^0.23.0"` in my package.json
Thank you for help!
