### ISSUE TITLE
XR|XS* models show wrong result on getModel and hasNotch

### ISSUE THREAD

**Issue by alvelig** [rebeccahughes/react-native-device-info#531]
## Summary

|             |     |
| ----------- | --- |
| Version     |  v0.24.3   |
| Affected OS | iOS  |
| OS Version  | v12.0  |
Tested on simulator iPhone XR

## Current behavior
```
console.log(DeviceInfo.getModel());
--> iPhone

console.log(DeviceInfo.getDeviceName());
--> iPhone XR

console.log(DeviceInfo.hasNotch())
--> false
```
## Expected behavior
```
console.log(DeviceInfo.getModel());
--> iPhone XR

console.log(DeviceInfo.getDeviceName());
--> iPhone XR

console.log(DeviceInfo.hasNotch())
--> true
```

**Comment by machour** [comment]
Hi,

The collection of phones with notches is here: 
   https://github.com/rebeccahughes/react-native-device-info/blob/master/deviceinfo.js#L12

And the detection occurs here: https://github.com/rebeccahughes/react-native-device-info/blob/master/deviceinfo.js#L210

Could you show us the output of DeviceInfo.getBrand() ?

**Comment by alvelig** [comment]
Thanks for the quick reply! Here's the output:
<img width="313" alt="screen shot 2018-10-30 at 10 13 01 am" src="https://user-images.githubusercontent.com/4231544/47720451-ab92da80-dc2c-11e8-924f-f910190214fe.png">


The problem occurs here: https://github.com/rebeccahughes/react-native-device-info/blob/master/ios/RNDeviceInfo/RNDeviceInfo.m#L145

Thus getModel returns "iPhone" and `hasNotch` detection fails

For some reason it doesn't catch the dictionary value by key.

**Comment by alvelig** [comment]
Sorry, my fault with the linking.
I removed and added again RNDeviceInfo.xcodeproj to Libraries and it worked.
