### ISSUE TITLE
TypeError:Deviceinfo.getBrand is not a function

### ISSUE THREAD

**Issue by ingviso** [rebeccahughes/react-native-device-info#532]
When using react-native-device-info on my Mac I run into TypeError: Deviceinfo.getBrand is not a function. This issue comes up on both android and ios This does not happen on a pc running an android. 

## Summary

Runnning this on a mac with MacOs Mojave and Xcode 10 and Android Studio 3.2.1 (with ndk r17c) 

| Version     | 0.24.3   |
| Affected OS | ios and android   |
| OS Version  | 0.55.2  |

## Current behavior

Building the app which is a camera app works, but when running it this comes up
![img_1028](https://user-images.githubusercontent.com/8041943/47725262-26b9b800-dc50-11e8-9ccf-fb5be896c69d.PNG)

I have tried older versions of device-info or down to 0.24.0 but still this comes up. When I remove the loading of the device-info I'm able to run the app and everything works which is not dependent on this.

## Expected behavior
Able to run the app and view phones camera

**Comment by machour** [comment]
How do you load the library in your script ?
Could you show some code?

**Comment by ingviso** [comment]
Just found out what the issue was, it because I was requiring the package instead of importing it. It has always worked requiring before and that works on my coworkers pc for some strange reason this was the reason for the bug.

Changed 
const DeviceInfo = require('react-native-device-info');
to
import DeviceInfo from 'react-native-device-info';

**Comment by NelGarbuzova** [comment]
Have this too. By strange way, few days ago require stopped to work correctly, but always worked before.
