### ISSUE TITLE
Execution failed for task ':app:preDebugBuild'.

### ISSUE THREAD

**Issue by julienJean99** [rebeccahughes/react-native-device-info#551]
## Summary

|             |     |
| ----------- | --- |
| Version     | 24   |
| Affected OS | android   |

when i instaled react-native-devise-info i did:

`npm install react-native-devise-info
react-native link react-native-devise-info`

i tryed using 

`implementation ("com.google.android.gms:play-services-basement:15.0.1") {force = true;}`

then ./gradlew :app:dependencies ask me for the following
`implementation ("com.google.android.gms:play-services-tasks:15.0.1") {force = true;}`

and now :app:dependencies worked but react-native run-android is still not working and i have no idea why

## Current behavior
when i try to compile with the current vertion of react-native-device-info i get this error:

`    The library com.google.android.gms:play-services-basement is being requested by various other       libraries at [[15.0.1,15.0.1]], but resolves to 16.0.1.`
## Expected behavior
bing abeld to start react-native run-android

**Comment by Foohx** [comment]
Hi @julienJean99 

Just add **googlePlayServicesVersion = "15.0.1"** in the **ext** part of you **build.gradle**.

👍

**Comment by Aung-Myint-Thein** [comment]
Hi 

I have googlePlayServicesVersion but for me the error message is as following: 

```
Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: com.reactnativecommunity.netinfo.BroadcastReceiverConnectivityReceiver$ConnectivityBroadcastReceiver
```

Anyone face the problem before?

**Comment by Aung-Myint-Thein** [comment]
Oh it is running now after I remove the whole build folder and run again. Thanks!
