### ISSUE TITLE
hasNotch() is not working properly.

### ISSUE THREAD

**Issue by jariwalabhavesh** [rebeccahughes/react-native-device-info#556]
## Summary
hasNotch() is not working properly. I am getting hasNotch() value true in iphoneX but in Iphone Xs Max it is giving false. It should return true for all the latest iphones notch devices.

| Version     | 0.24.3   |
| Affected OS | IOS   |
| OS Version  | 12.1   |
| React-Native | 0.55.1 | 
## Current behavior

hasNotch() is giving false in iphone Xs Max. 

## Expected behavior

hasNotch() should return true for iphone Xs Max. For iphoneX it is working perfectly.

**Comment by lapto** [comment]
Try running DeviceInfo.getDeviceName() and check if the device name is different than "iPhone XS Max".  There is a custom version of MAX and XR for the Asia Market that might have a different deviceName. 

Heres the list of devices that hasNotch() will return "true" on

https://github.com/rebeccahughes/react-native-device-info/blob/65374808dc8aea1d6b989927a8f42c4732eaab60/deviceinfo.js

**Comment by jariwalabhavesh** [comment]
@lapto : getDeviceName is giving **iPhone XS Max**
Now i am receiving hasNotch : **true**

I think there was an issue with my installed react-native-device-info or I was using an old version.

**Comment by mohak1990** [comment]
Returning promise on DeviceInfo.hasNotch() check and not a Boolean value.

**Comment by danieltran3110** [comment]
> Try running DeviceInfo.getDeviceName() and check if the device name is different than "iPhone XS Max". There is a custom version of MAX and XR for the Asia Market that might have a different deviceName.
> 
> Heres the list of devices that hasNotch() will return "true" on
> 
> https://github.com/rebeccahughes/react-native-device-info/blob/65374808dc8aea1d6b989927a8f42c4732eaab60/deviceinfo.js

Hi Lapto

I can not get the hasNotch: **true** 
in the android devices 

Do you have any Ideas about it. I'm using the nokia X7 and It can change the status bar from notch to full bezel.

**Comment by mikehardy** [comment]
@danieltran3110 if you don't see the device in the list of devices that will return true, then it will not return true. Propose a PR that adds the device and we can release an update

**Comment by maduraherath8** [comment]
Hi Please add Huwawei Y6P to the has notch list. 
Modal - MED-LX9

**Comment by mikehardy** [comment]
@maduraherath8 propose a PR
