### ISSUE TITLE
package com.learnium.RNDeviceInfo does not exist

### ISSUE THREAD

**Issue by magrinj** [rebeccahughes/react-native-device-info#564]
## Summary

Hello, I got an error every time I try to build my app on Android, I check all the similar issues, and try to downgrade to 0.23.0 and replace "implementation" by "compile" but that doesn't change anything.

|             |     |
| ----------- | --- |
| Version     |  0.25.1  |
| Affected OS |  Android  |
| OS Version  | SDK 27  |

## Current behavior

Every time I run the build I got:

```
:app:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/magrin_j/Documents/Work/Cookomix/Cookomix-mobile/android/app/src/main/java/com/cookomix/mobile/MainApplication.java:27: error: package com.learnium.RNDeviceInfo does not exist
import com.learnium.RNDeviceInfo.*;
^
/Users/magrin_j/Documents/Work/Cookomix/Cookomix-mobile/android/app/src/main/java/com/cookomix/mobile/MainApplication.java:46: error: cannot find symbol
                new RNDeviceInfo(),
                    ^
  symbol:   class RNDeviceInfo
  location: class MainApplication
2 errors
:app:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

I don't really understand why that's happening, if someone can help me !
The library is correctly linked! I try to link it manually and with `react-native link`

## Expected behavior

No compilation error

**Comment by vladrozhnev** [comment]
@magrinj just change `import com.learnium.RNDeviceInfo.*;` to `import com.learnium.RNDeviceInfo.RNDeviceInfo;` in the `MainApplication.java` file and everything will be fine.

**Comment by mikehardy** [comment]
The app links fine if you use `react-native link react-native-device-info` but it looks like something in that step failed. You should create a fresh sample app and follow the integration instructions to see how it works. This looks like your app's android/settings.gradle didn't get linked in correctly:

```
include ':react-native-device-info'
project(':react-native-device-info').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-device-info/android')
```

so the symbols don't exist in the android/java namespace.

@machour this should be closed as a not-a-bug, the module installs fine in apps if linked in correctly. A PR for a sample app showing correct usage would probably minimize these issues

**Comment by machour** [comment]
@mikehardy it would be great indeed, don't hesitate to submit one :)
