### ISSUE TITLE
Huawei P20 Lite not detecting notch

### ISSUE THREAD

**Issue by andreifilip123** [rebeccahughes/react-native-device-info#568]
## Summary

|             |     |
| ----------- | --- |
| Version     | 0.26.1   |
| Affected OS | Android   |
| OS Version  | Not relevant  |

## Current behavior

The hasNotch() function returns false on Huawei P20 Lite. I tested and the function getModel() returns ANE-LX1. Can you add this device to the devicesWithNotch list ? 

## Expected behavior

The hasNotch() function should return true but it returns false.

**Comment by machour** [comment]
Fixed in #569
