### ISSUE TITLE
hasNotch() is not working properly on LG G7 ThinQ

### ISSUE THREAD

**Issue by beaulieufrancois** [rebeccahughes/react-native-device-info#572]
Hi, 

 DeviceInfo.getDeviceName() on LG G7 ThinQ return LM-G710 and it's a similar pattern for all LG phones. 
 :)

**Comment by machour** [comment]
Hi @beaulieufrancois 

could you open a PR to fix this?

**Comment by beaulieufrancois** [comment]
https://github.com/rebeccahughes/react-native-device-info/pull/573

**Comment by GiladR1979** [comment]
This is still happening on 5.4.0. hasNotch() returns false.
DeviceInfo.getBrand() returns "lge" and not "lg".
