### ISSUE TITLE
null is not an object (evaluating 'RNDeviceInfo.deviceId')

### ISSUE THREAD

**Issue by MatheusLima7** [rebeccahughes/react-native-device-info#575]
## Summary

|             |     |
| ----------- | --- |
| Version     | 0.26.4  |
| Affected OS |  IOS |
| OS Version  |  IOS   |

## Current behavior

// import
import DeviceInfo from 'react-native-device-info';

// componentDidMount
DeviceInfo.getDeviceId()

Error
Message: null is not an object (evaluating 'RNDeviceInfo.deviceId')
Nothing works

**Comment by saraervik** [comment]
I got this error as well.

The same behavior, only difference is the function call, I used
`DeviceInfo.getDeviceLocale()`

**Comment by saraervik** [comment]
Update: @MatheusLima7 try linking suggested in #510 , it solved the problem for me.

I ran the command:
`react-native link react-native-device-info`

**Comment by sagargulati** [comment]
I even linked them. Tried the manual linking as well, still no luck.
Anyone who can help? I'm running it with the expo.
react-native info
```
  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 16.04.6 LTS (Xenial Xerus)
      Memory: 12.02 GB / 31.28 GB
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 10.15.1 - /usr/bin/node
      Yarn: 1.13.0 - /usr/bin/yarn
      npm: 6.4.1 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 24, 25, 26, 27, 28
        Build Tools: 23.0.2, 27.0.3, 28.0.3
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

```

**Comment by mikehardy** [comment]
I just linked this module into an app and everything is fine - this must be a problem with the installation.

The module doesn't include a sample app but I suggest you do a clean test app from `react-native init` then `npm install react-native-device-info` and `npx react-native link react-native-device-info`

Note I did say `npx` there as you want to make sure you have an up to date react-native-cli package from `npm install -g react-native-cli` to do the init, but then after that you want to use the one in your app's node_modules.

@machour this should be closed with a user help / not a bug tag or similar, the app installs and links correctly. A PR for a sample app demonstrating correct behavior on iOS and Android would be awesome though...

**Comment by appli-intramuros** [comment]
You have to run 'pod install' after linking library.

**Comment by mikehardy** [comment]
@appli-intramuros that is not necessarily correct. Did you make sure the reporter was using pods first? If they are not, this would do nothing except give an error that there was no command "pod" because it wasn't installed.

**Comment by Nagibaba** [comment]
if you are only facing this issue on Android close the emulator, wipe emulator data from Android Studio and try again 
<img width="1293" alt="Screenshot 2019-05-20 at 1 19 07 PM" src="https://user-images.githubusercontent.com/22720833/58010697-ed6c6b00-7b01-11e9-893d-75d86b9e7730.png">
