### ISSUE TITLE
General API improvements and possible room for expansion

### ISSUE THREAD

**Issue by mehcode** [rebeccahughes/react-native-device-info#62]
Just some ideas I want to jot down for this package:

 - Talk to @GertjanReynaert of https://github.com/GertjanReynaert/react-native-device and merge efforts. 

 - Rename package to `react-native-device` or `rn-device` (see above)

 - Add activity lifecycle events ~ `device.addEventListener("suspend", ...)` -- I have this in my current app and I'm looking to open source it (its not much) and all I can find is IOS only or Android only plugins; it's not a ton of code.

 - Change API to be more javascript and less java -- eg.. 

```
import {systemVersion, instanceID, model, userAgent} from "react-native-device";
```

---

Just some ideas. I can publish another package for the events if we think its out-of-scope here.

@GantMan ?

**Comment by mehcode** [comment]
@joanbarros 
@jeroenbourgois
@rebeccahughes 
@lilach 
@GantMan 

Any feedback on the direction? I'd like to get this module forward a few iterations for my own projects.

**Comment by GantMan** [comment]
this week I'm teaching and working.  I can review this next week.   Long week bud!  Updates soon :)

**Comment by joanbarros** [comment]
1. Merge sounds good if both projects have the same purpose.
2. On the renaming of the package. Is there any convention in the React Native world?
3. Would need to review and comment in a couple of hours.
4. Sounds good.

I'll post later with more detailed opinions.

**Comment by mehcode** [comment]
I went ahead and published https://github.com/mehcode/rn-device-activity as a separate module
