### ISSUE TITLE
Difference between uniqueId and instanceId

### ISSUE THREAD

**Issue by almasakchabayev** [rebeccahughes/react-native-device-info#67]
From README I understand that uniqueId corresponds to IDFV on iOS, is it null on android? 
Do I need instanceId library to make it work on iOS, otherwise is it going to be null?

**Comment by mehcode** [comment]
The UniqueID is meant to be a _persistent_, unique identifier. It is that way currently on Android. #58 makes it that way on iOS.

InstanceID is meant to be scoped to the installation (unique, but non persistent identifier).

**Comment by almasakchabayev** [comment]
Thanks
