### ISSUE TITLE
Installing in Android gives  "package com.learnium does not exist"

### ISSUE THREAD

**Issue by nbastoWM** [rebeccahughes/react-native-device-info#7]
```
error: package com.learnium does not exist
import com.learnium.RNDeviceInfo;
                   ^
````

**Comment by rebeccahughes** [comment]
You are missing the .* at the end of RNDeviceInfo:

```
import com.learnium.RNDeviceInfo.*;
```

**Comment by nbastoWM** [comment]
In MainActivity.java I included the .* but when the error appears the .* doesn't show.

**Comment by rebeccahughes** [comment]
Have you included it in build.gradle?

**Comment by nbastoWM** [comment]
OK, I uninstalled it, did all the steps again and now it's fine.
Maybe some problem with npm install..
Thanks!
