### ISSUE TITLE
Does a persistent device ID exist for iOS?

### ISSUE THREAD

**Issue by kevando** [rebeccahughes/react-native-device-info#72]
I want my app to authenticate via unique device identifier so that as long as they're on the same device, they don't need to create an account. 

I am open to other ways of accomplishing this, device ID just seemed the best - however the `DeviceInfo.getUniqueID()` keeps changing on the same device.

**Comment by mehcode** [comment]
@kevando https://github.com/rebeccahughes/react-native-device-info/pull/58

That PR makes `.getUniqueID` actually unique.

**Comment by kevando** [comment]
Awesome, thanks @mehcode Just so I'm understanding this repo correctly, this was not actually merged into the master yet, correct?

**Comment by kevando** [comment]
I merged this PR with the latest master branch and followed the manual instructions and I am getting this error:

``Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_DeviceUID", referenced from:
      objc-class-ref in libRNDeviceInfo.a(RNDeviceInfo.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)``

Not sure if this is something wrong on my end (in the xcode settings) or something else.. I will report back

**Comment by mehcode** [comment]
It looks like I forgot to go back and finish that PR. Someone needs to add those two files to the xcode project.

**Comment by mehcode** [comment]
For the record this is done
