### ISSUE TITLE
rnpm install doesn't work on Android

### ISSUE THREAD

**Issue by alexHlebnikov** [rebeccahughes/react-native-device-info#74]
```rnpm install ``` installs package only on iOS. 
The only I find to install it on Android is the manual installation.

**Comment by GantMan** [comment]
This is likely your version of react native.  As of 0.29, `rnpm` will not work on Android.  `rnpm` is being sunsetted as it is consumed by the `react-native-cli`

**Comment by alexHlebnikov** [comment]
I'm using RN 0,30.0 and 0.31.0.
So we need to upgrade installation instruction.

**Comment by GantMan** [comment]
Would you like to file the PR?  I'll happily merge it.

**Comment by alexHlebnikov** [comment]
@GantMan yep, I'll do it :)

**Comment by alexHlebnikov** [comment]
Here is the PR: https://github.com/rebeccahughes/react-native-device-info/pull/75

**Comment by antoinerousseau** [comment]
```
npm install --save react-native-device-info
react-native link react-native-device-info
```
