### ISSUE TITLE
Please don't pin your play-services dependency at a particular version

### ISSUE THREAD

**Issue by christocracy** [rebeccahughes/react-native-device-info#78]
It causes issues **with other libs** when a 3rd-party library, like yours, pins its `play-services` dependencies at a particular version.

eg:
```
Unknown source file : com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/iid/MessengerCompat$1;
Unknown source file : 	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Unknown source file : 	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file : 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file : 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file : 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file : 	at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file : 	at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file : 	at com.android.dx.command.Main.main(Main.java:106)
```

You have
```Gradle
compile 'com.google.android.gms:play-services-gcm:8.3.0'
```

You need to change it to:
```Gradle
compile 'com.google.android.gms:play-services-gcm:+'
```

**Comment by jerson** [comment]
same here :/ , cc @rebeccahughes  change it

**Comment by christocracy** [comment]
In addition, I question the wisdom of including the entire ‘play-services-gcm` just to fetch the gym identifier.  This should be the responsibility of some other module which is doing Push requests.  This module has no business dealing with this.

**Comment by GantMan** [comment]
Please issue a PR with this fix.

**Comment by antoinerousseau** [comment]
what is it used for? I don't see any "get gcm identifier" in the doc...
i can make the PR anyway

**Comment by christocracy** [comment]
https://github.com/rebeccahughes/react-native-device-info/blob/master/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L83

**Comment by antoinerousseau** [comment]
I suppose it's the same for `com.facebook.react:react-native:0.11.+` that can be replaced by `com.facebook.react:react-native:+`?
https://github.com/rebeccahughes/react-native-device-info/blob/master/android/build.gradle#L22

**Comment by esutton** [comment]
This caused me much lost time searching for solutions after I upgraded my packages.  Will a fix be released soon?

**Comment by christocracy** [comment]
12 open PRs and the author hasn't even commented on this thread.

In the meantime, pin this plugin dep in your app 0.9.3

**Comment by GantMan** [comment]
I'm at React Rally, but I can help.   Link me to the PR that fixes this.   Rebecca is not actively maintaining this repo, she identified she had to move on to other tasks.   As a community we're aiming to keep this live.

**Comment by antoinerousseau** [comment]
the PR that fixes this is in this thread just above... it's #82

**Comment by GantMan** [comment]
ty @antoinerousseau

**Comment by mebowen** [comment]
Hi @antoinerousseau - it seems like [this line](https://github.com/rebeccahughes/react-native-device-info/blob/master/android/build.gradle#L23) is always getting the latest version of play services, which is actually causing recurrent problems for me. My app spontaneously starts crashing when a new version of play services comes out, and I keep having to update my play services version (which is not ideal due to other libraries and tools I am using). When I hardcode this line to `11.6.2`, I no longer see the crashes. Rather than fork this project just so I can hardcode a play services version, can you recommend another solution to this issue? This library is very useful to me, but it's causing some instability in my app due to the issue described above. I'd really appreciate any advice you might be able to offer. Thank you!

**Comment by antoinerousseau** [comment]
Hi @mebowen, after reading [this](https://github.com/react-community/react-native-maps/pull/731#discussion_r85857550), it seems that specifying `+` as a gradle version is indeed a bad practice. We should pin the required minimum version instead.

**Comment by mebowen** [comment]
@antoinerousseau you have made me so happy! The question is, how do we agree on a version to use? 😄

**Comment by mebowen** [comment]
For example, I am _pretty sure_ I need `11.6.2` because of a version of the google maps API that I'm using. Not sure that will work for everyone. I can keep looking into this, but am wondering if you have a version in mind.

**Comment by mebowen** [comment]
@antoinerousseau you've made me so happy! I will test out `9.6.1` and will open a PR if that fixes my problem. Thanks!

**Comment by mebowen** [comment]
`9.6.1` does not work for me, but from the link you posted, I found another solution: 

adding something like
```
allprojects {
    .
    .
    .
    configurations.all {
        resolutionStrategy {
            force 'com.google.android.gms:play-services-gcm:11.6.2'
        }
    }
}
``` to my android project's `build.gradle` file seems to fix the issue.
