### ISSUE TITLE
Get Error on react-native run-android

### ISSUE THREAD

**Issue by Dzheky** [rebeccahughes/react-native-device-info#87]
`C:\Users\Evgeny\Documents\programming\ReactChat\android\app\src\main\java\com\reactchat\MainApplication.java:7: error: package com.learnium.RNDeviceInfo does not exist
import com.learnium.RNDeviceInfo.RNDeviceInfo;
                                ^
C:\Users\Evgeny\Documents\programming\ReactChat\android\app\src\main\java\com\reactchat\MainApplication.java:27: error: cannot find symbol
          new RNDeviceInfo(),
              ^
  symbol: class RNDeviceInfo
3 errors
 FAILED
`

**Comment by krishbhattacharyya** [comment]
Hi @Dzheky , I face the problem today & solve this but the build was mine. It can help you but I am not sure. If "react-native-device-info" is installed in your packages please uninstall this & remove the added portion as mentioned in the link "MainActivity.java & AndroidManifest.xml". Please go through the link - https://github.com/rebeccahughes/react-native-device-info. You will get the idea. And one very important thing is that- if  "import com.learnium.RNDeviceInfo.RNDeviceInfo;" & "new RNDeviceInfo()" is added multiple times it can create problem.

**Comment by Dzheky** [comment]
@krishbhattacharyya thank you, I removed packages, and removed everything that react-native-device-info has added to the project including MainActivity.java and AdnroidManifest.xml entries. After all of this build is working, but when I install it again if shows me the same error. So seems like I am not able to use it.

**Comment by krishbhattacharyya** [comment]
Can you share the screen shot of the simulator & the npm error? Then I can try to help you or may be other person can help you.

**Comment by Dzheky** [comment]
I get this if I dont do `react-native link react-native-device-info`
![2](https://cloud.githubusercontent.com/assets/10736974/18025592/1d83ae66-6c37-11e6-8eba-61e466ee66b6.png)

And this if I do `react-native link react-native-device-info`
![1](https://cloud.githubusercontent.com/assets/10736974/18025599/3af1ef58-6c37-11e6-9897-5246268965a6.png)

**Comment by krishbhattacharyya** [comment]
You have told me that you have uninstalled the "react-native-device-info" but you have import this in your  package.  So please remove this from package may be this will run. One thing but you are going to remove the device info which is major part of your app. 

I thing you are using this ( let me try at home ) -
https://github.com/tonyspiro/react-chat-app

Please have a look in  this is already a open bug- 
https://github.com/rebeccahughes/react-native-device-info/issues/52#issuecomment-240333618

**Comment by Dzheky** [comment]
Like I said if I completely remove 'react-native-device-info' my application works, but obviously I cannot use 'react-native-device-info' then because I removed it.

**Comment by krishbhattacharyya** [comment]
Then you should close this issue. This is temporary solution to remove the device info. Developers are working on device info.
https://github.com/rebeccahughes/react-native-device-info/issues/52#issuecomment-240333618 So as per my knowledge this is a known issue. Thanks.
