### ISSUE TITLE
Request: detect the device connection (wifi, cellular...)

### ISSUE THREAD

**Issue by Zianwar** [rebeccahughes/react-native-device-info#88]
Hello, 

Is there a way to integrate the connection info into this module?

**Comment by antoinerousseau** [comment]
the current code is generating a map of constants once at load time, but the device connection can be changing, so it needs dynamic getters and maybe event listeners.
it doesn't mean it's impossible though ;)

**Comment by L3V147H4N** [comment]
RN API already provides something similar, is this not enough?
https://facebook.github.io/react-native/docs/netinfo.html
