### ISSUE TITLE
Runtime failure - crash on UIWebView

### ISSUE THREAD

**Issue by pospetur** [rebeccahughes/react-native-device-info#89]
Followed the instructions for installing 0.9.4 and tried both automatic and manual install. But it will crash when I run the app on my iPhone with these messages =>
(will you help?)

**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[10]'
**\* First throw call stack:
(0x18246adb0 0x181acff80 0x18235377c 0x182353614 0x10058f45c 0x1004447c8 0x10045eb24 0x1004446a8 0x1004361e8 0x100cbda7c 0x100cbda3c 0x100cc34e4 0x182420d50 0x18241ebb8 0x182348c50 0x183c30088 0x187632088 0x100034f94 0x181ee68b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by M1chaelTran** [comment]
i'm getting the same error.

would be good if someone could help us out.

**Comment by machour** [comment]
Is this still happening with 0.14.0 ?

**Comment by patmisch** [comment]
I'm still seeing this with 0.14.0

**Comment by machour** [comment]
@patmisch how did you do the linking ? what is the call that is provoking the runtime error ? Thanks!

**Comment by simonheys** [comment]
@machour The crash is this line: https://github.com/rebeccahughes/react-native-device-info/blob/1ec397f306317751fe0754a93c804da6756c9280/RNDeviceInfo/RNDeviceInfo.m#L175

UIWebView does not initialise (not clear why), so userAgent function returns nil, which causes an attempt to insert nil into the dictionary here: https://github.com/rebeccahughes/react-native-device-info/blob/1ec397f306317751fe0754a93c804da6756c9280/RNDeviceInfo/RNDeviceInfo.m#L262

...which results in the error

**Comment by machour** [comment]
Thank you for the feedback.. any clues on how to fix this one? 🤔

**Comment by machour** [comment]
Should be fixed in 0.15.3 🎉

**Comment by ntphong1990** [comment]
I facing it in 0.21.5
I back to 0.15.3 and it's gone

**Comment by machour** [comment]
Please open a new issue.
