### ISSUE TITLE
C++ Exception in 'nativeRequireModuleConfig'

### ISSUE THREAD

**Issue by L3V147H4N** [rebeccahughes/react-native-device-info#90]
I'm getting this error when importing the package:

I'm running an Emulator with Android 4.1.1 and using React Native 0.32

![image](https://cloud.githubusercontent.com/assets/5846479/18088158/6164fba8-6e8f-11e6-8816-6a0545e88acf.png)

**Comment by L3V147H4N** [comment]
The same error appears on my phone with android 6.0.1

**Comment by L3V147H4N** [comment]
another error, simply by including the project in the build makes the debug crash

**Comment by abdallahm** [comment]
i fixed it temporarily by replacing 
`compile 'com.google.android.gms:play-services-gcm:+'`
with
`compile ('com.google.android.gms:play-services-gcm:9.0.1') { force = true; }`
in node_modules/react-native-device-info/android/build.gradle file

**Comment by ospfranco** [comment]
@abdallahm solution does not work for me, any other idea on how to solve this?

**Comment by ospfranco** [comment]
as mentioned by @L3V147H4N this only crashes on debug builds, release builds seem to build just fine

**Comment by alfonsodev** [comment]
similar error here 
`C++ Exception in 'nativeRequireModuleConfig': java.lang.IllegalAccessError: Method 'void android.support.v4.content.ContextCompat.<init>()' is inaccessible to class 'com.google.android.gms.iid.zzd' (declaration of 'com.google.android.gms.iid.zzd' appears in /data/app/com.myapp-1/base.apk)`

**Comment by superandrew213** [comment]
Getting same error as @alfonsodev on release builds

**Comment by swaroopa94** [comment]
Hi I am  getting the same error but the solution did not work for me  any other idea on how to solve this?

**Comment by CodyMcArthur** [comment]
I wasted a day on this and just got it fixed up. In case it helps anyone - mine was all about the compile 'com.google.android.gms:play-services-gcm:+' ...like abdallahm was saying. 

You will only need to change these lines in the build.gradle of their respective package, not the main project build gradle. 

Mine originally looked like this: 
compile 'com.google.android.gms:play-services-gcm:8.4.3'

I changed it to this:
compile ('com.google.android.gms:play-services-gcm:9.0.1') ..note the brackets and new version:

I also had some other packages in my project that were using things like (this is a package that includes a map):
compile 'com.google.android.gms:play-services-maps:8.4.3'
compile 'com.google.android.gms:play-services-location:8.4.3'

So I changed them to: 
compile 'com.google.android.gms:play-services-maps:9.0.1' ..just changed the version
compile 'com.google.android.gms:play-services-location:9.0.1'

Also, if you use compile this line in any packages, make sure the version number matches:
compile 'com.android.support:appcompat-v7:23.1.1'

Sync -Clean - Make Project - Run and bask in the glory!

**Comment by ospfranco** [comment]
@CodyMcArthur if you change it on their respective projects it will only work on your machine, next time you install the dependencies (or on other peoples machines) you won't have the changes, or am I understanding this incorrectly?

**Comment by machour** [comment]
Documented how to disable com.google.android.gms in the [troubleshooting]( https://github.com/rebeccahughes/react-native-device-info#troubleshooting) section.
Will probably be dropped with next BC breaking release.

Closing this old issue that was about something else.
