### ISSUE TITLE
can not  get the "com.learnium.RNDeviceInfo"

### ISSUE THREAD

**Issue by liwanchong04719** [rebeccahughes/react-native-device-info#91]
i follow the advise ,but i can't  get the com.learnium.RNDeviceInfo ,i don't know  how to expand it

**Comment by BigPun86** [comment]
What do you mean, that u can not get it?

**Comment by xiaoyangzi** [comment]
前提是保证正确link了react native device info到项目中。
在项目的build.gradle文件中把compile 'com.facebook.react:react-native:+' react native 的依赖去掉然后重新build下。因为device info 项目已经依赖了这个，不需要重复引用进来。你可以查看react native device info的build.gradle文件，确实已经依赖了react-native。

**Comment by machour** [comment]
Closing this old issue, please open a new one if you're still facing this problem.
