### ISSUE TITLE
getTimezone() not included in current version

### ISSUE THREAD

**Issue by bharrell** [rebeccahughes/react-native-device-info#98]
It looks like the getTimezone method was added the day after the last version number bump. (see "Merge pull request #83 from antoinerousseau/timezone-getter "). Could you bump the version number so that an npm install gets this method added?

**Comment by GantMan** [comment]
will do.  @bharrell - would you let me know if there are any other PRs that you think would best be evaluated in his release, before the version is bumped?

**Comment by bharrell** [comment]
None in particular. I'm just using this for getUniqueId, getUserAgent and getTimezone. If you're waiting on some other PRs first, that's cool, no rush. We're able to get getTimezone to run for now by adding getTimezone to deviceinfo.js by hand. Just wanted to make sure version eventually got bumped to include it.

**Comment by bharrell** [comment]
Version has been bumped to 0.9.6 and issue is fixed. Thanks!
