### ISSUE TITLE
getUniqueID() new UUID each type app reopened in ios simulator

### ISSUE THREAD

**Issue by ck-alpha** [rebeccahughes/react-native-device-info#99]
A React-Native app I'm developing in IOS simulator, if I double home click and swipe close my app, then reopen it, getUniqueID() returns a brand new UUID.

Is this expected behaviour?

Is it just a quirk of the simulator / react environment?

**Comment by skylarmb** [comment]
FWIW im not seeing this behavior. I have relaunched the app/simulator many times and always get the same UUID

**Comment by ck-alpha** [comment]
I will have to take a look in more detail sometime. Anyway I went round the issue by saving the first UUID generated into a localstorage database and using that from then on.

**Comment by aksonov** [comment]
I have the same issue.

**Comment by MajidAzizSc** [comment]
@skylarmb can you please send me your code, if possible

**Comment by skylarmb** [comment]
@MajidAzizSc I didn't do anything special. 

```
import DeviceInfo from 'react-native-device-info';
...
const deviceId = DeviceInfo.getUniqueID();
```

**Comment by MajidAzizSc** [comment]
can you do that for me if I send you my sample app code ?

**Comment by MajidAzizSc** [comment]
can you do that for me please

**Comment by MajidAzizSc** [comment]
Please have a look at the sample app.
thanks

**Comment by luco** [comment]
Updates on this?

**Comment by machour** [comment]
Is this still happening with 0.14.0 ?

**Comment by machour** [comment]
Closing this old issue, please open a new one if you're still facing this problem.
